In [1]:
import numpy as np
import pandas as pd
import random
import uuid

# Blok name generator

In [ ]:
cluster = ['Kemayoran','Menteng', 'Ancol', 'Darmawangsa', 'Senayan', 'Thamrin' ]
cluster_code = ['01','02','03','04','05','06']
blok = ['A', 'B', 'C', 'D', 'E', 'F']#, 'G']#, 'H']
nomor_A = [str(i) for i in range(1,21)]
nomor_B = [str(i) for i in range(1,19)]
nomor_C = [str(i) for i in range(1,15)]
nomor_D = [str(i) for i in range(1,30)]
nomor_E = [str(i) for i in range(1,22)]
nomor_F = [str(i) for i in range(1,18)]
#nomor_G = [str(i) for i in range(1,19)]
#nomor_H = [str(i) for i in range(1,26)]

In [ ]:
blk_gabung_thamrin = []
for nomor in nomor_A:
  blk_gabung_thamrin.append(blok[0]+nomor)

for nomor in nomor_B:
  blk_gabung_thamrin.append(blok[1]+nomor)

for nomor in nomor_C:
  blk_gabung_thamrin.append(blok[2]+nomor)

for nomor in nomor_D:
  blk_gabung_thamrin.append(blok[3]+nomor)

for nomor in nomor_E:
  blk_gabung_thamrin.append(blok[4]+nomor)

for nomor in nomor_F:
  blk_gabung_thamrin.append(blok[5]+nomor)

#for nomor in nomor_G:
  #blk_gabung_thamrin.append(blok[6]+nomor)

#for nomor in nomor_H:
  #blk_gabung_senayan.append(blok[7]+nomor)

In [ ]:
import random
acak_thamrin = blk_gabung_thamrin
random.shuffle(acak_thamrin)
#acak_thamrin

['C2',
 'D29',
 'E17',
 'E9',
 'A2',
 'A6',
 'A5',
 'D7',
 'C1',
 'E6',
 'B9',
 'E16',
 'A15',
 'D10',
 'A11',
 'E13',
 'B4',
 'F8',
 'D27',
 'E18',
 'D18',
 'D15',
 'E14',
 'B11',
 'C8',
 'A7',
 'D13',
 'F12',
 'D12',
 'E19',
 'A3',
 'D20',
 'E1',
 'E15',
 'C5',
 'E2',
 'C4',
 'D8',
 'E7',
 'D5',
 'A8',
 'B17',
 'D26',
 'A12',
 'C9',
 'A13',
 'D23',
 'A9',
 'A20',
 'F9',
 'F11',
 'E12',
 'B15',
 'D11',
 'E21',
 'E11',
 'B13',
 'E10',
 'A17',
 'A16',
 'E20',
 'C14',
 'D25',
 'D1',
 'B12',
 'F3',
 'D16',
 'C12',
 'F5',
 'B8',
 'F10',
 'B6',
 'B5',
 'F1',
 'A14',
 'B2',
 'D2',
 'F13',
 'A19',
 'C3',
 'E8',
 'D28',
 'F4',
 'C7',
 'C10',
 'B16',
 'C11',
 'D22',
 'D9',
 'A18',
 'D3',
 'D19',
 'D24',
 'B3',
 'E4',
 'D6',
 'F2',
 'B18',
 'B10',
 'E5',
 'F6',
 'D4',
 'B1',
 'D17',
 'D21',
 'F17',
 'F14',
 'E3',
 'C13',
 'A4',
 'F7',
 'A1',
 'F16',
 'B7',
 'C6',
 'F15',
 'A10',
 'B14',
 'D14']

In [ ]:
len(acak_thamrin)

119

In [ ]:
df_nama = pd.read_csv('indonesian-names.csv')
df_nama

                             name gender
0                 hafizhan shidqi      m
1                   gandhi wibowo      m
2     aldio mahendra purwandrarto      m
3                     benny putra      m
4            vicky vernando dasta      m
...                           ...    ...
1955                      hadimah      f
1956          aprillia rahma wati      f
1957        muhamad khoirunisa. m      m
1958                      sukandi      m
1959                          eem      f

[1960 rows x 2 columns]

In [ ]:
nama_thamrin = df_nama['name'][675:794]
gender_thamrin = df_nama['gender'][675:794]
np.array(nama_thamrin)
np.array(gender_thamrin)

array(['f', 'f', 'm', 'f', 'm', 'm', 'f', 'f', 'm', 'f', 'm', 'm', 'f',
       'f', 'm', 'f', 'f', 'm', 'm', 'f', 'm', 'm', 'f', 'f', 'm', 'f',
       'f', 'f', 'f', 'm', 'f', 'f', 'f', 'm', 'f', 'm', 'm', 'm', 'f',
       'f', 'm', 'f', 'm', 'm', 'm', 'f', 'f', 'f', 'm', 'm', 'f', 'm',
       'f', 'm', 'f', 'f', 'm', 'f', 'f', 'f', 'm', 'f', 'm', 'm', 'm',
       'f', 'm', 'f', 'm', 'm', 'm', 'm', 'f', 'm', 'm', 'f', 'm', 'm',
       'f', 'm', 'm', 'f', 'm', 'f', 'f', 'm', 'm', 'f', 'm', 'f', 'm',
       'f', 'f', 'm', 'f', 'f', 'f', 'm', 'f', 'm', 'm', 'f', 'm', 'f',
       'm', 'f', 'm', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f',
       'm', 'm'], dtype=object)

In [ ]:
np.array(gender_thamrin).shape

(119,)

In [ ]:
cluster_thamrin = np.array([cluster[5]]*119)
cluster_thamrin

array(['Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin',
       'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin', 'Thamrin'], dtype='<U7')

In [ ]:
res_thamrin= np.c_[nama_thamrin, gender_thamrin, acak_thamrin, cluster_thamrin]
res_thamrin

array([['nadhirotul khusniah', 'f', 'C2', 'Thamrin'],
       ['dewi masitoh', 'f', 'D29', 'Thamrin'],
       ['ach. moehaimin alwi', 'm', 'E17', 'Thamrin'],
       ['siti aisyah', 'f', 'E9', 'Thamrin'],
       ['muhammad faizin alwi', 'm', 'A2', 'Thamrin'],
       ['sarno', 'm', 'A6', 'Thamrin'],
       ['giyem', 'f', 'A5', 'Thamrin'],
       ['siti khasanah', 'f', 'D7', 'Thamrin'],
       ['andrianto', 'm', 'C1', 'Thamrin'],
       ['tri purwanti', 'f', 'E6', 'Thamrin'],
       ['fajri syahdan naufal', 'm', 'B9', 'Thamrin'],
       ['wahidi', 'm', 'E16', 'Thamrin'],
       ['jasiah', 'f', 'A15', 'Thamrin'],
       ['eliyuswisnawaty', 'f', 'D10', 'Thamrin'],
       ['sukijan', 'm', 'A11', 'Thamrin'],
       ['sudarmi', 'f', 'E13', 'Thamrin'],
       ['siti zaenap', 'f', 'B4', 'Thamrin'],
       ['sodikin', 'm', 'F8', 'Thamrin'],
       ["mas' ud", 'm', 'D27', 'Thamrin'],
       ['sutinem', 'f', 'E18', 'Thamrin'],
       ["ahmad safi'i", 'm', 'D18', 'Thamrin'],
       ['habibi nurrohim', 'm', 'D15', 'Thamrin'],
       ['sulasikin nasukah', 'f', 'E14', 'Thamrin'],
       ['jamilatun azizah', 'f', 'B11', 'Thamrin'],
       ['suparlan', 'm', 'C8', 'Thamrin'],
       ['sulastri', 'f', 'A7', 'Thamrin'],
       ['widyo wati', 'f', 'D13', 'Thamrin'],
       ['wiwit widia wati', 'f', 'F12', 'Thamrin'],
       ['wulandari', 'f', 'D12', 'Thamrin'],
       ['kirno yudi', 'm', 'E19', 'Thamrin'],
       ['lilik mujiati', 'f', 'A3', 'Thamrin'],
       ['shofiyyatun dzakiroh', 'f', 'D20', 'Thamrin'],
       ['wulan maratussholikha', 'f', 'E1', 'Thamrin'],
       ['aris tiono', 'm', 'E15', 'Thamrin'],
       ['sitti julaeha', 'f', 'C5', 'Thamrin'],
       ['ibnu mirza hamizan alfaeyza', 'm', 'E2', 'Thamrin'],
       ['apri hantoro', 'm', 'C4', 'Thamrin'],
       ['suratman', 'm', 'D8', 'Thamrin'],
       ['mucharomatun', 'f', 'E7', 'Thamrin'],
       ['rensy herwinda', 'f', 'D5', 'Thamrin'],
       ['sukarmin', 'm', 'A8', 'Thamrin'],
       ['saniri', 'f', 'B17', 'Thamrin'],
       ['firda ramadan', 'm', 'D26', 'Thamrin'],
       ['fauzi hidayat', 'm', 'A12', 'Thamrin'],
       ['ahmad suyadi', 'm', 'C9', 'Thamrin'],
       ['nuriah', 'f', 'A13', 'Thamrin'],
       ['irma lestari', 'f', 'D23', 'Thamrin'],
       ['nur kholifah', 'f', 'A9', 'Thamrin'],
       ['muhammad abdul rohman', 'm', 'A20', 'Thamrin'],
       ['yendra putra', 'm', 'F9', 'Thamrin'],
       ['reni sriyati', 'f', 'F11', 'Thamrin'],
       ['rudi saputra', 'm', 'E12', 'Thamrin'],
       ['ervi lidya wati', 'f', 'B15', 'Thamrin'],
       ['agus setiawan', 'm', 'D11', 'Thamrin'],
       ['tesa rismiani', 'f', 'E21', 'Thamrin'],
       ['ellenna yuliani putri. s', 'f', 'E11', 'Thamrin'],
       ['saiman', 'm', 'B13', 'Thamrin'],
       ['surti', 'f', 'E10', 'Thamrin'],
       ['pirawati', 'f', 'A17', 'Thamrin'],
       ['triani', 'f', 'A16', 'Thamrin'],
       ['darma sahputra', 'm', 'E20', 'Thamrin'],
       ['supriani', 'f', 'C14', 'Thamrin'],
       ['rhamasya damar', 'm', 'D25', 'Thamrin'],
       ['supratman', 'm', 'D1', 'Thamrin'],
       ['nanang mujahid', 'm', 'B12', 'Thamrin'],
       ['siti imaroh', 'f', 'F3', 'Thamrin'],
       ['rizal kurniawan', 'm', 'D16', 'Thamrin'],
       ['nur laila', 'f', 'C12', 'Thamrin'],
       ['hamdan muzakir', 'm', 'F5', 'Thamrin'],
       ['hadi mardiansah', 'm', 'B8', 'Thamrin'],
       ['aziz', 'm', 'F10', 'Thamrin'],
       ['suyoto', 'm', 'B6', 'Thamrin'],
       ['binar', 'f', 'B5', 'Thamrin'],
       ['alek susanto', 'm', 'F1', 'Thamrin'],
       ['aris setianto', 'm', 'A14', 'Thamrin'],
       ['siti zaenab', 'f', 'B2', 'Thamrin'],
       ['teguh adi wijaya', 'm', 'D2', 'Thamrin'],
       ['suwarmin', 'm', 'F13', 'Thamrin'],
       ['wulandari', 'f', 'A19', 'Thamrin'],
       ['iqbal akbar ghofur', 'm', 'C3', 'Thamrin'],
       ['mardani satra', 'm', 'E8', 'Thamrin'],
       ['fitria wulandari', 'f', 'D28', 'Thamrin'],
       ['bastiur', 'm', 'F4', 'Thamrin'],
       ['endah susanti', 'f', 'C7', 'Thamrin'],
       ['olivvia febby santika', 'f', 'C10', 'Thamrin'],
       ['al hakim januario barens', 'm', 'B16', 'Thamrin'],
       ['amal fatullah', 'm', 'C11', 'Thamrin'],
       ['ayu kusmini', 'f', 'D22', 'Thamrin'],
       ['yusman', 'm', 'D9', 'Thamrin'],
       ['alfia santi sahputri', 'f', 'A18', 'Thamrin'],
       ['waluyo', 'm', 'D3', 'Thamrin'],
       ['nuraini', 'f', 'D19', 'Thamrin'],
       ['madha leli', 'f', 'D24', 'Thamrin'],
       ['rudianto', 'm', 'B3', 'Thamrin'],
       ['istiani', 'f', 'E4', 'Thamrin'],
       ['vega miftaqul rizka', 'f', 'D6', 'Thamrin'],
       ['meilany putri sakinah', 'f', 'F2', 'Thamrin'],
       ['akbar rizki saputra', 'm', 'B18', 'Thamrin'],
       ['safira cantika fitriani', 'f', 'B10', 'Thamrin'],
       ['slamet teguh santoso', 'm', 'E5', 'Thamrin'],
       ['solehan', 'm', 'F6', 'Thamrin'],
       ['komsidah', 'f', 'D4', 'Thamrin'],
       ['yuli adi putra', 'm', 'B1', 'Thamrin'],
       ['ria rasela', 'f', 'D17', 'Thamrin'],
       ['solehan', 'm', 'D21', 'Thamrin'],
       ['suryani', 'f', 'F17', 'Thamrin'],
       ["muhammad ahsanul mubtadi'in", 'm', 'F14', 'Thamrin'],
       ['muhammad rifki irawan', 'm', 'E3', 'Thamrin'],
       ['intan nurul aini', 'f', 'C13', 'Thamrin'],
       ['sarno', 'm', 'A4', 'Thamrin'],
       ['rubini', 'f', 'F7', 'Thamrin'],
       ['pursito', 'm', 'A1', 'Thamrin'],
       ['rita fitri mulyasih', 'f', 'F16', 'Thamrin'],
       ['saikun', 'm', 'B7', 'Thamrin'],
       ['sutiti', 'f', 'C6', 'Thamrin'],
       ['jefri setiadi', 'm', 'F15', 'Thamrin'],
       ['dwi maryani', 'f', 'A10', 'Thamrin'],
       ['krisno tri widodo', 'm', 'B14', 'Thamrin'],
       ['katiman', 'm', 'D14', 'Thamrin']], dtype=object)

In [ ]:
df_thamrin = pd.DataFrame(res_thamrin, columns=['Name','Gender','Block','Cluster'])
df_thamrin

                     Name Gender Block  Cluster
0     nadhirotul khusniah      f    C2  Thamrin
1            dewi masitoh      f   D29  Thamrin
2     ach. moehaimin alwi      m   E17  Thamrin
3             siti aisyah      f    E9  Thamrin
4    muhammad faizin alwi      m    A2  Thamrin
..                    ...    ...   ...      ...
114                sutiti      f    C6  Thamrin
115         jefri setiadi      m   F15  Thamrin
116           dwi maryani      f   A10  Thamrin
117     krisno tri widodo      m   B14  Thamrin
118               katiman      m   D14  Thamrin

[119 rows x 4 columns]

In [ ]:
df_thamrin.to_csv('thamrin.csv', index=False)

# Create resident block data

In [2]:
ancol = pd.read_csv('ancol.csv')
darma = pd.read_csv('darmawangsa.csv')
kemayoran = pd.read_csv('kemayoran.csv')
menteng = pd.read_csv('menteng.csv')
senayan = pd.read_csv('senayan.csv')
thamrin = pd.read_csv('thamrin.csv')

In [3]:
df_resident = pd.concat([ancol, darma, kemayoran, menteng, senayan, thamrin], ignore_index=True)
df_resident

                   Name Gender Block  Cluster
0            ridha ulva      f   A14    Ancol
1    rizqi wahyuningsih      f   B19    Ancol
2        ruwadi saputra      m   C12    Ancol
3       sugeng hermawan      m    D3    Ancol
4              suliatun      f    C1    Ancol
..                  ...    ...   ...      ...
784              sutiti      f    C6  Thamrin
785       jefri setiadi      m   F15  Thamrin
786         dwi maryani      f   A10  Thamrin
787   krisno tri widodo      m   B14  Thamrin
788             katiman      m   D14  Thamrin

[789 rows x 4 columns]

In [4]:
rumah = ['Owner','Rent']
own_status_code = ['01','02']

cluster = ['Kemayoran','Menteng', 'Ancol', 'Darmawangsa', 'Senayan', 'Thamrin' ]
cluster_code = ['01','02','03','04','05','06']

In [5]:
# add year of inhabited
tahun = [2022, 2023, 2024]
tmp_year = random.choices(tahun, weights=[316, 166, 307], k=789)

#add rent category
tmp_own = random.choices(rumah, weights=[671, 118], k=789)

# add year_of_inhabited & own_status
df_resident['year_of_inhabited'] = tmp_year
df_resident['own_status'] = tmp_own

In [ ]:
df_resident

                   Name Gender Block  Cluster  year_of_inhabited own_status
0            ridha ulva      f   A14    Ancol               2022      Owner
1    rizqi wahyuningsih      f   B19    Ancol               2022       Rent
2        ruwadi saputra      m   C12    Ancol               2023      Owner
3       sugeng hermawan      m    D3    Ancol               2024       Rent
4              suliatun      f    C1    Ancol               2022      Owner
..                  ...    ...   ...      ...                ...        ...
784              sutiti      f    C6  Thamrin               2023      Owner
785       jefri setiadi      m   F15  Thamrin               2022      Owner
786         dwi maryani      f   A10  Thamrin               2023      Owner
787   krisno tri widodo      m   B14  Thamrin               2022      Owner
788             katiman      m   D14  Thamrin               2023       Rent

[789 rows x 6 columns]

In [ ]:
df_resident_list = df_resident.values.tolist()

In [ ]:
df_resident_list

[['ridha ulva', 'f', 'A14', 'Ancol', 2022, 'Owner'],
 ['rizqi wahyuningsih', 'f', 'B19', 'Ancol', 2022, 'Rent'],
 ['ruwadi saputra', 'm', 'C12', 'Ancol', 2023, 'Owner'],
 ['sugeng hermawan', 'm', 'D3', 'Ancol', 2024, 'Rent'],
 ['suliatun', 'f', 'C1', 'Ancol', 2022, 'Owner'],
 ['tomi ismeidianto', 'm', 'G12', 'Ancol', 2022, 'Owner'],
 ['usthalay putra', 'm', 'H12', 'Ancol', 2023, 'Owner'],
 ['winggo aga septian', 'm', 'G15', 'Ancol', 2022, 'Owner'],
 ['yunaldi rizki putra', 'm', 'D25', 'Ancol', 2024, 'Owner'],
 ['arif fasetyo', 'm', 'G11', 'Ancol', 2023, 'Owner'],
 ['arie rahman satria', 'm', 'B20', 'Ancol', 2024, 'Owner'],
 ['arinda oktaviana', 'f', 'D8', 'Ancol', 2023, 'Rent'],
 ['asri jakawendra', 'm', 'H25', 'Ancol', 2023, 'Owner'],
 ['astri stiawaty', 'm', 'H1', 'Ancol', 2023, 'Owner'],
 ['aszani', 'f', 'F1', 'Ancol', 2022, 'Owner'],
 ['boby rahman', 'm', 'A16', 'Ancol', 2022, 'Owner'],
 ['dewi cahyati', 'f', 'D18', 'Ancol', 2022, 'Owner'],
 ['dimas aditya perdana', 'm', 'C4', 'Ancol', 2023, 'Owner'],
 ['dinda afani', 'f', 'C8', 'Ancol', 2023, 'Rent'],
 ['doni sanjaya', 'm', 'B11', 'Ancol', 2024, 'Owner'],
 ['fitri yanti', 'f', 'D27', 'Ancol', 2024, 'Owner'],
 ['hendri eka saputra', 'm', 'A5', 'Ancol', 2022, 'Owner'],
 ['irwan ahmad gafur', 'm', 'B17', 'Ancol', 2024, 'Owner'],
 ['isa ismail', 'm', 'D6', 'Ancol', 2022, 'Owner'],
 ['kurniawan rosman a', 'm', 'A9', 'Ancol', 2023, 'Owner'],
 ['muhammad azmy', 'm', 'F5', 'Ancol', 2022, 'Owner'],
 ['muhammad ilham', 'm', 'E4', 'Ancol', 2022, 'Owner'],
 ['muhammad sholihan', 'm', 'B4', 'Ancol', 2024, 'Owner'],
 ['novita dewi', 'f', 'H21', 'Ancol', 2024, 'Owner'],
 ['novri sabli saputra', 'm', 'D24', 'Ancol', 2024, 'Owner'],
 ['pajar bahari', 'm', 'D12', 'Ancol', 2023, 'Owner'],
 ['redha fauziah aziz', 'f', 'G16', 'Ancol', 2024, 'Owner'],
 ['ridho', 'm', 'D11', 'Ancol', 2024, 'Owner'],
 ['ridho fajri', 'm', 'G9', 'Ancol', 2024, 'Owner'],
 ['ridho rismayanda', 'm', 'H23', 'Ancol', 2022, 'Rent'],
 ['ridwan candra', 'm', 'A10', 'Ancol', 2022, 'Owner'],
 ['rosdina', 'f', 'H3', 'Ancol', 2023, 'Owner'],
 ['supriadi', 'm', 'G6', 'Ancol', 2023, 'Owner'],
 ['suriyani', 'f', 'E5', 'Ancol', 2022, 'Owner'],
 ['tommy zul hidayat', 'm', 'B16', 'Ancol', 2022, 'Owner'],
 ['umi riyani', 'f', 'D13', 'Ancol', 2022, 'Owner'],
 ['wiwik sumarmi', 'f', 'D1', 'Ancol', 2022, 'Owner'],
 ['yuni dwi hastuti', 'f', 'H5', 'Ancol', 2023, 'Owner'],
 ['aulia rahman', 'm', 'B9', 'Ancol', 2022, 'Owner'],
 ['agung kurniawan', 'm', 'A12', 'Ancol', 2022, 'Owner'],
 ['ahmad fauzi paturusi', 'm', 'A7', 'Ancol', 2024, 'Owner'],
 ['arie biola gunti masuko', 'm', 'H20', 'Ancol', 2024, 'Owner'],
 ['ayu andira', 'f', 'F9', 'Ancol', 2022, 'Owner'],
 ['ayu dwi septiana arta', 'f', 'H22', 'Ancol', 2024, 'Owner'],
 ['azwar anas', 'm', 'H15', 'Ancol', 2022, 'Rent'],
 ['azwir irfan nanda', 'm', 'D14', 'Ancol', 2022, 'Owner'],
 ['budi setiawan', 'm', 'E9', 'Ancol', 2024, 'Owner'],
 ['donna febriani', 'f', 'C13', 'Ancol', 2023, 'Owner'],
 ['dwi widiastuti', 'f', 'B5', 'Ancol', 2022, 'Owner'],
 ['dwiki apsyarin', 'm', 'E3', 'Ancol', 2024, 'Rent'],
 ['dwiza indri', 'm', 'C7', 'Ancol', 2022, 'Owner'],
 ['frans b jaya zalukhu', 'm', 'B21', 'Ancol', 2023, 'Owner'],
 ['fuad harisfa', 'm', 'F2', 'Ancol', 2024, 'Owner'],
 ['herman efendi', 'm', 'H14', 'Ancol', 2024, 'Rent'],
 ['ichsyan rizky adi p', 'm', 'D15', 'Ancol', 2023, 'Owner'],
 ['ivo oktavianti', 'f', 'C10', 'Ancol', 2022, 'Owner'],
 ['lailatul izzati', 'f', 'C16', 'Ancol', 2024, 'Owner'],
 ['muhammad oki', 'm', 'C14', 'Ancol', 2024, 'Rent'],
 ['muhammad ridho ardonis', 'm', 'H6', 'Ancol', 2023, 'Owner'],
 ['muhammad rizqi muttaqin', 'm', 'D22', 'Ancol', 2024, 'Owner'],
 ['muhammad setyo', 'm', 'D2', 'Ancol', 2022, 'Owner'],
 ['nur aulia hasanah', 'f', 'H7', 'Ancol', 2022, 'Rent'],
 ['nurfatrianti', 'f', 'D16', 'Ancol', 2024, 'Owner'],
 ['pikril islami', 'm', 'A15', 'Ancol', 2023, 'Rent'],
 ['rikal', 'm', 'A3', 'Ancol', 2024, 'Owner'],
 ['riyan hidayat', 'm', 'A13', 'Ancol', 2022, 'Owner'],
 ['rizki fatama', 'm', 'H10', 'Ancol', 2023, 'Rent'],
 ['rizkie hafizzah', 'f', 'G4', 'Ancol', 2024, 'Rent'],
 ['syaiful akbar', 'm', 'A1', 'Ancol', 2024, 'Owner'],
 ["nu' in sofyan", 'm', 'B3', 'Ancol', 2024, 'Rent'],
 ['sumirah', 'm', 'C15', 'Ancol', 2024, 'Owner'],
 ['ade surahman', 'm', 'C6', 'Ancol', 2022, 'Rent'],
 ['kasnanto', 'm', 'B8', 'Ancol', 2023, 'Owner'],
 ['sumirah', 'm', 'F4', 'Ancol', 2023, 'Owner'],
 ['teguh wahyudi', 'm', 'H16', 'Ancol', 2022, 'Owner'],
 ['sakiyo', 'm', 'D7', 'Ancol', 2022, 'Owner'],
 ['dwi kasmini', 'm', 'B1', 'Ancol', 2022, 'Owner'],
 ['laily mufarokah', 'm', 'B23', 'Ancol', 2022, 'Owner'],
 ['sigit nugroho', 'm', 'B10', 'Ancol', 2024, 'Owner'],
 ['linda rusmi wardani', 'm', 'B13', 'Ancol', 2022, 'Rent'],
 ['m. charly iman nugroho', 'm', 'F15', 'Ancol', 2024, 'Owner'],
 ['untung sugiono', 'm', 'C17', 'Ancol', 2022, 'Owner'],
 ['sarminah', 'm', 'B2', 'Ancol', 2022, 'Owner'],
 ['wiwik purwanti', 'm', 'A8', 'Ancol', 2024, 'Owner'],
 ['saputra', 'm', 'H2', 'Ancol', 2022, 'Rent'],
 ['sufiyani', 'f', 'H4', 'Ancol', 2024, 'Owner'],
 ['zenika pradea', 'f', 'E8', 'Ancol', 2023, 'Owner'],
 ['adelia agustin', 'f', 'F13', 'Ancol', 2023, 'Rent'],
 ['desi aulia rahma', 'f', 'B15', 'Ancol', 2024, 'Owner'],
 ['muhammad fajar maulana', 'm', 'D5', 'Ancol', 2022, 'Owner'],
 ['muliadi', 'm', 'D20', 'Ancol', 2022, 'Owner'],
 ['nuriyati', 'f', 'F6', 'Ancol', 2022, 'Owner'],
 ['andreyan saputra', 'm', 'H18', 'Ancol', 2022, 'Rent'],
 ['afrianda', 'm', 'H9', 'Ancol', 2022, 'Owner'],
 ['surya ramadani', 'm', 'A2', 'Ancol', 2022, 'Owner'],
 ['suhendri', 'm', 'B12', 'Ancol', 2024, 'Owner'],
 ['dewi wulan sari', 'f', 'H19', 'Ancol', 2022, 'Owner'],
 ['reza andika ramadhan', 'm', 'B14', 'Ancol', 2022, 'Owner'],
 ['slamet', 'm', 'G3', 'Ancol', 2023, 'Owner'],
 ['erna', 'f', 'D19', 'Ancol', 2024, 'Owner'],
 ['gilang aditia', 'm', 'G7', 'Ancol', 2022, 'Owner'],
 ['suherianto', 'm', 'F10', 'Ancol', 2024, 'Owner'],
 ['sugianti', 'f', 'D23', 'Ancol', 2023, 'Owner'],
 ['aris pratama putra', 'm', 'F14', 'Ancol', 2022, 'Owner'],
 ['adella', 'f', 'D10', 'Ancol', 2024, 'Owner'],
 ['widyo sudiro', 'm', 'G10', 'Ancol', 2022, 'Rent'],
 ['kusniah', 'f', 'E1', 'Ancol', 2023, 'Rent'],
 ['riza feri handoko', 'm', 'B24', 'Ancol', 2022, 'Owner'],
 ['angga adhy surya', 'm', 'D28', 'Ancol', 2023, 'Rent'],
 ['nelvin adhy renata', 'm', 'H8', 'Ancol', 2022, 'Owner'],
 ['titis brigida silva', 'f', 'F16', 'Ancol', 2022, 'Owner'],
 ['suroso', 'm', 'C2', 'Ancol', 2023, 'Owner'],
 ['sukati', 'f', 'E7', 'Ancol', 2022, 'Rent'],
 ['depri selamet ariadi', 'm', 'F11', 'Ancol', 2023, 'Owner'],
 ['isti nurjanah', 'f', 'G13', 'Ancol', 2024, 'Owner'],
 ['ruswantoro', 'm', 'H24', 'Ancol', 2024, 'Rent'],
 ['juli anggraeni', 'f', 'D17', 'Ancol', 2024, 'Owner'],
 ['muhammad prayoga winata', 'm', 'G5', 'Ancol', 2023, 'Owner'],
 ['heru setyono', 'm', 'F7', 'Ancol', 2024, 'Owner'],
 ['sri mulyani', 'f', 'G2', 'Ancol', 2022, 'Rent'],
 ['galih subekti', 'm', 'F8', 'Ancol', 2022, 'Owner'],
 ['ageng kurniawan', 'm', 'F3', 'Ancol', 2024, 'Owner'],
 ['auliya shobrina', 'f', 'A4', 'Ancol', 2024, 'Owner'],
 ['slamet', 'm', 'A6', 'Ancol', 2022, 'Owner'],
 ['suparmi', 'f', 'A11', 'Ancol', 2024, 'Rent'],
 ['tri agus susilo', 'm', 'F17', 'Ancol', 2022, 'Owner'],
 ['junaeri', 'm', 'D9', 'Ancol', 2024, 'Rent'],
 ['daryono', 'm', 'F18', 'Ancol', 2023, 'Owner'],
 ['poniyem', 'f', 'B18', 'Ancol', 2024, 'Owner'],
 ['fajar setiawan', 'm', 'D4', 'Ancol', 2024, 'Owner'],
 ['nabilatul dwi seftiani', 'f', 'B22', 'Ancol', 2024, 'Owner'],
 ['jaimin', 'm', 'E10', 'Ancol', 2023, 'Owner'],
 ['rohatun', 'f', 'E2', 'Ancol', 2024, 'Owner'],
 ['dewi safitri', 'f', 'C11', 'Ancol', 2024, 'Owner'],
 ['dian elok nur cahyati', 'f', 'G1', 'Ancol', 2024, 'Owner'],
 ['m. amrijen nur rohman', 'm', 'E6', 'Ancol', 2023, 'Rent'],
 ['rosidin', 'm', 'G8', 'Ancol', 2022, 'Owner'],
 ['suwarti', 'f', 'D21', 'Ancol', 2022, 'Owner'],
 ['krisdan fauzi', 'm', 'G14', 'Ancol', 2023, 'Rent'],
 ['khasanah dwi fauziah', 'f', 'D26', 'Ancol', 2022, 'Owner'],
 ['ainun isnaini fauziati', 'f', 'C9', 'Ancol', 2024, 'Owner'],
 ['m. rais tri wahyudi', 'm', 'H17', 'Ancol', 2024, 'Owner'],
 ['sri mudrikoh', 'f', 'B7', 'Ancol', 2022, 'Owner'],
 ['ihsan baedowi', 'm', 'F12', 'Ancol', 2023, 'Owner'],
 ['rahmad erwin wibisono', 'm', 'H13', 'Ancol', 2022, 'Owner'],
 ['muhamad fiki wahyudi', 'm', 'B6', 'Ancol', 2022, 'Owner'],
 ['agus salim', 'm', 'C5', 'Ancol', 2022, 'Owner'],
 ['mardiana', 'f', 'C3', 'Ancol', 2023, 'Owner'],
 ['mustika sari', 'f', 'H11', 'Ancol', 2022, 'Rent'],
 ['muhammad zamzari', 'm', 'D19', 'Darmawangsa', 2022, 'Owner'],
 ['air murya', 'f', 'F9', 'Darmawangsa', 2024, 'Owner'],
 ['sumardi', 'm', 'B4', 'Darmawangsa', 2024, 'Owner'],
 ['surni', 'f', 'H13', 'Darmawangsa', 2024, 'Owner'],
 ['wahid suprayitno', 'm', 'H9', 'Darmawangsa', 2024, 'Owner'],
 ['sutramiati', 'f', 'H15', 'Darmawangsa', 2022, 'Owner'],
 ['susanti lestari', 'f', 'F8', 'Darmawangsa', 2022, 'Owner'],
 ['rasman', 'm', 'B19', 'Darmawangsa', 2022, 'Owner'],
 ['riya ningsih', 'f', 'D6', 'Darmawangsa', 2022, 'Owner'],
 ['uji ifandy saputra', 'm', 'G15', 'Darmawangsa', 2024, 'Owner'],
 ['hana aida sahila', 'm', 'D28', 'Darmawangsa', 2024, 'Owner'],
 ['mufizar ilyas', 'm', 'D27', 'Darmawangsa', 2023, 'Rent'],
 ['nora', 'm', 'C2', 'Darmawangsa', 2024, 'Owner'],
 ['ulviana agustina', 'm', 'B8', 'Darmawangsa', 2022, 'Owner'],
 ['erina ramadhani', 'm', 'C18', 'Darmawangsa', 2023, 'Owner'],
 ['sumono', 'm', 'E4', 'Darmawangsa', 2024, 'Owner'],
 ['khoirul zaki', 'm', 'F3', 'Darmawangsa', 2023, 'Owner'],
 ['warsini', 'm', 'A4', 'Darmawangsa', 2023, 'Owner'],
 ['alif al barrak zaki', 'm', 'E8', 'Darmawangsa', 2022, 'Owner'],
 ['sulistiyono', 'm', 'F12', 'Darmawangsa', 2023, 'Owner'],
 ['jekri wiralis', 'm', 'C20', 'Darmawangsa', 2022, 'Owner'],
 ['nirmanto', 'm', 'B20', 'Darmawangsa', 2024, 'Owner'],
 ['rasmini', 'm', 'C1', 'Darmawangsa', 2023, 'Owner'],
 ['bejo hutanto', 'm', 'E5', 'Darmawangsa', 2022, 'Rent'],
 ['desi tri astuti', 'm', 'C9', 'Darmawangsa', 2022, 'Owner'],
 ['okta ionika', 'm', 'D20', 'Darmawangsa', 2023, 'Owner'],
 ['muhyidin', 'm', 'C5', 'Darmawangsa', 2024, 'Rent'],
 ['meriyanti', 'm', 'E7', 'Darmawangsa', 2023, 'Owner'],
 ['erna lestari', 'm', 'H19', 'Darmawangsa', 2024, 'Owner'],
 ['asef saifulloh', 'm', 'G5', 'Darmawangsa', 2022, 'Owner'],
 ['jonianto', 'm', 'D26', 'Darmawangsa', 2024, 'Owner'],
 ['mujiati', 'm', 'C7', 'Darmawangsa', 2023, 'Rent'],
 ['riko hari prasetyo', 'm', 'G18', 'Darmawangsa', 2022, 'Owner'],
 ['diva al farizky', 'm', 'C21', 'Darmawangsa', 2022, 'Owner'],
 ['parjo', 'm', 'H20', 'Darmawangsa', 2022, 'Owner'],
 ['rumsiyah', 'm', 'G1', 'Darmawangsa', 2024, 'Owner'],
 ['dewi sumarni', 'm', 'A6', 'Darmawangsa', 2022, 'Owner'],
 ['efi sulastri', 'm', 'G6', 'Darmawangsa', 2022, 'Owner'],
 ['wagimun', 'm', 'D4', 'Darmawangsa', 2022, 'Owner'],
 ['girah', 'm', 'A3', 'Darmawangsa', 2023, 'Owner'],
 ['feni safitri', 'm', 'G11', 'Darmawangsa', 2024, 'Owner'],
 ['sumarno', 'm', 'H6', 'Darmawangsa', 2023, 'Owner'],
 ['nurimah', 'm', 'H22', 'Darmawangsa', 2024, 'Owner'],
 ['noviana anggraeni', 'm', 'F2', 'Darmawangsa', 2022, 'Owner'],
 ['aissyah dwi zhaskia', 'm', 'H11', 'Darmawangsa', 2024, 'Owner'],
 ['hariri', 'm', 'H4', 'Darmawangsa', 2024, 'Owner'],
 ['ida budiani', 'm', 'B15', 'Darmawangsa', 2022, 'Owner'],
 ['rizki pratama', 'm', 'B24', 'Darmawangsa', 2022, 'Rent'],
 ['yanto', 'm', 'B22', 'Darmawangsa', 2024, 'Owner'],
 ['puji lestari', 'f', 'G14', 'Darmawangsa', 2022, 'Owner'],
 ['dewi wulan ningsih', 'f', 'G2', 'Darmawangsa', 2022, 'Rent'],
 ['aril aji alania', 'm', 'H7', 'Darmawangsa', 2024, 'Owner'],
 ['amalia chechy anggia', 'f', 'C6', 'Darmawangsa', 2022, 'Rent'],
 ['suranto', 'm', 'A7', 'Darmawangsa', 2023, 'Rent'],
 ['suprihatin', 'f', 'H25', 'Darmawangsa', 2022, 'Owner'],
 ['bangkit syuhada', 'm', 'A8', 'Darmawangsa', 2022, 'Owner'],
 ['tri anindita aurellia', 'f', 'G9', 'Darmawangsa', 2023, 'Owner'],
 ['kasturi', 'm', 'D7', 'Darmawangsa', 2022, 'Owner'],
 ['epran', 'm', 'B3', 'Darmawangsa', 2022, 'Owner'],
 ['suwarsih', 'f', 'H17', 'Darmawangsa', 2022, 'Owner'],
 ['dwi astika sari', 'f', 'B1', 'Darmawangsa', 2024, 'Owner'],
 ['trio hamdani', 'm', 'H8', 'Darmawangsa', 2024, 'Owner'],
 ['a. solikhin', 'm', 'H18', 'Darmawangsa', 2023, 'Rent'],
 ['sumiati', 'f', 'G16', 'Darmawangsa', 2023, 'Owner'],
 ['sugiat bagus hermawan', 'm', 'C12', 'Darmawangsa', 2024, 'Owner'],
 ['sukma liyana dewi', 'f', 'A2', 'Darmawangsa', 2022, 'Owner'],
 ['dzul helmi affan ridho', 'm', 'E16', 'Darmawangsa', 2024, 'Rent'],
 ['nugroho', 'm', 'B9', 'Darmawangsa', 2022, 'Owner'],
 ['kusriyati', 'f', 'A13', 'Darmawangsa', 2024, 'Owner'],
 ['vika apriliana n. a', 'f', 'D10', 'Darmawangsa', 2024, 'Owner'],
 ['bela octavia ramadani', 'f', 'C4', 'Darmawangsa', 2023, 'Owner'],
 ['pri santoso', 'm', 'H23', 'Darmawangsa', 2022, 'Owner'],
 ['miyanto', 'm', 'E13', 'Darmawangsa', 2022, 'Owner'],
 ['samiyah', 'f', 'E1', 'Darmawangsa', 2023, 'Owner'],
 ['wahyu pratama', 'm', 'H3', 'Darmawangsa', 2024, 'Owner'],
 ['devina tria ananda', 'f', 'A12', 'Darmawangsa', 2022, 'Owner'],
 ['masruri', 'm', 'D1', 'Darmawangsa', 2023, 'Owner'],
 ['siti romlah', 'f', 'C11', 'Darmawangsa', 2024, 'Owner'],
 ['ricky prayoga', 'm', 'F13', 'Darmawangsa', 2024, 'Rent'],
 ['shafa mutia nurhaliza', 'f', 'F10', 'Darmawangsa', 2022, 'Owner'],
 ['abdul malik', 'm', 'D24', 'Darmawangsa', 2022, 'Owner'],
 ['kardi', 'm', 'A9', 'Darmawangsa', 2024, 'Owner'],
 ['sumini', 'f', 'B12', 'Darmawangsa', 2024, 'Owner'],
 ['andika saputra', 'm', 'A14', 'Darmawangsa', 2023, 'Owner'],
 ['habib hidayaturrohman', 'm', 'H14', 'Darmawangsa', 2022, 'Owner'],
 ['wiwik wulandari', 'f', 'E11', 'Darmawangsa', 2022, 'Owner'],
 ['m. souvil anam', 'm', 'D17', 'Darmawangsa', 2022, 'Rent'],
 ['anin khamidah', 'f', 'G3', 'Darmawangsa', 2024, 'Owner'],
 ['diram', 'm', 'B2', 'Darmawangsa', 2024, 'Rent'],
 ['muslimah', 'f', 'H5', 'Darmawangsa', 2022, 'Owner'],
 ['eko kurniawan', 'm', 'A1', 'Darmawangsa', 2022, 'Owner'],
 ['romadon nur hidayat', 'm', 'C15', 'Darmawangsa', 2022, 'Owner'],
 ['siti masliah', 'f', 'F5', 'Darmawangsa', 2024, 'Rent'],
 ['tri adi eko lestanto', 'm', 'F15', 'Darmawangsa', 2022, 'Owner'],
 ['eva setia ningrum', 'f', 'E15', 'Darmawangsa', 2022, 'Rent'],
 ['suyono', 'm', 'D18', 'Darmawangsa', 2022, 'Owner'],
 ['nurtriana yuliastuti', 'f', 'D5', 'Darmawangsa', 2023, 'Owner'],
 ['sazim saputra', 'm', 'F4', 'Darmawangsa', 2023, 'Owner'],
 ['rozakiah', 'f', 'F16', 'Darmawangsa', 2024, 'Owner'],
 ['alifia yuliani', 'f', 'F17', 'Darmawangsa', 2023, 'Owner'],
 ['hamzah maulana', 'm', 'E10', 'Darmawangsa', 2023, 'Owner'],
 ['akbar maulana', 'm', 'D14', 'Darmawangsa', 2024, 'Owner'],
 ['supriyadi', 'm', 'G12', 'Darmawangsa', 2022, 'Owner'],
 ['supiyah', 'f', 'A17', 'Darmawangsa', 2022, 'Owner'],
 ['alfajar efendi', 'm', 'C17', 'Darmawangsa', 2024, 'Owner'],
 ['ahmad saprudin', 'm', 'F7', 'Darmawangsa', 2024, 'Owner'],
 ['anwar sholeh', 'm', 'C3', 'Darmawangsa', 2024, 'Owner'],
 ['umi muslimah', 'f', 'C16', 'Darmawangsa', 2022, 'Owner'],
 ['elisa anjani', 'f', 'G17', 'Darmawangsa', 2022, 'Owner'],
 ['meila nurhidayati', 'f', 'B5', 'Darmawangsa', 2024, 'Owner'],
 ['santoso', 'm', 'B14', 'Darmawangsa', 2024, 'Owner'],
 ['tumi', 'f', 'A5', 'Darmawangsa', 2023, 'Rent'],
 ['mira mustika', 'f', 'H1', 'Darmawangsa', 2022, 'Rent'],
 ['edi suyoto', 'm', 'H12', 'Darmawangsa', 2022, 'Owner'],
 ['rikana nurmala desi', 'f', 'B11', 'Darmawangsa', 2024, 'Owner'],
 ['zidane dhevan pratama', 'm', 'B10', 'Darmawangsa', 2022, 'Owner'],
 ['mariyamah', 'f', 'B16', 'Darmawangsa', 2024, 'Owner'],
 ['setiawan', 'm', 'C8', 'Darmawangsa', 2023, 'Owner'],
 ['sutiono', 'm', 'D23', 'Darmawangsa', 2022, 'Owner'],
 ['nurhayati', 'f', 'D2', 'Darmawangsa', 2022, 'Owner'],
 ['oki aditia saputra', 'm', 'A15', 'Darmawangsa', 2024, 'Owner'],
 ['hendrio junior', 'm', 'F1', 'Darmawangsa', 2022, 'Owner'],
 ['giatno', 'm', 'F11', 'Darmawangsa', 2024, 'Owner'],
 ['siti ngaisah', 'f', 'D11', 'Darmawangsa', 2023, 'Owner'],
 ['ahmad rasyid', 'm', 'A19', 'Darmawangsa', 2024, 'Owner'],
 ['gilang nur bekti', 'm', 'D16', 'Darmawangsa', 2022, 'Owner'],
 ['abas suyatno', 'm', 'A11', 'Darmawangsa', 2023, 'Owner'],
 ['kholipah', 'f', 'C19', 'Darmawangsa', 2022, 'Owner'],
 ['abdul kholik', 'm', 'D25', 'Darmawangsa', 2024, 'Owner'],
 ['dede adiyanto', 'm', 'B13', 'Darmawangsa', 2023, 'Owner'],
 ['handani nurul hidayah', 'f', 'H24', 'Darmawangsa', 2022, 'Owner'],
 ['mustofa', 'm', 'A18', 'Darmawangsa', 2024, 'Owner'],
 ['luhur gunawan', 'm', 'G10', 'Darmawangsa', 2024, 'Owner'],
 ['tri mandrasih', 'f', 'F6', 'Darmawangsa', 2022, 'Owner'],
 ['manisem', 'f', 'B23', 'Darmawangsa', 2023, 'Owner'],
 ['r. widodo', 'm', 'D21', 'Darmawangsa', 2024, 'Owner'],
 ['ismanto', 'm', 'H2', 'Darmawangsa', 2022, 'Owner'],
 ['tri lestari', 'f', 'E12', 'Darmawangsa', 2022, 'Owner'],
 ['kurniawan zam zami', 'm', 'C10', 'Darmawangsa', 2023, 'Owner'],
 ['raditia saputri', 'm', 'D3', 'Darmawangsa', 2022, 'Owner'],
 ['mabruro', 'm', 'C13', 'Darmawangsa', 2022, 'Owner'],
 ['mukaromah', 'f', 'B17', 'Darmawangsa', 2023, 'Rent'],
 ['vina nailatul izzah', 'f', 'H10', 'Darmawangsa', 2023, 'Owner'],
 ['muhammad arwin', 'm', 'D13', 'Darmawangsa', 2022, 'Owner'],
 ['ulil amri', 'm', 'G8', 'Darmawangsa', 2022, 'Owner'],
 ['nurul mubarokah', 'f', 'H21', 'Darmawangsa', 2023, 'Owner'],
 ['nurisya amara putri', 'f', 'G4', 'Darmawangsa', 2022, 'Owner'],
 ['karno', 'm', 'A16', 'Darmawangsa', 2024, 'Owner'],
 ['asmunah', 'f', 'D9', 'Darmawangsa', 2022, 'Owner'],
 ['danang wahyu ananda', 'm', 'B21', 'Darmawangsa', 2023, 'Owner'],
 ['syamsul huda', 'm', 'E6', 'Darmawangsa', 2022, 'Owner'],
 ['tumirah', 'f', 'A10', 'Darmawangsa', 2022, 'Rent'],
 ['nur qasanah', 'f', 'G7', 'Darmawangsa', 2024, 'Rent'],
 ['andika dwi pangestu', 'm', 'D8', 'Darmawangsa', 2023, 'Owner'],
 ['mhd. yunus', 'm', 'G13', 'Darmawangsa', 2024, 'Owner'],
 ['juminah', 'f', 'D12', 'Darmawangsa', 2023, 'Owner'],
 ['dwi yuliani', 'f', 'B7', 'Darmawangsa', 2024, 'Owner'],
 ['chyndi erliani', 'f', 'D22', 'Darmawangsa', 2022, 'Owner'],
 ['eka putra', 'm', 'E2', 'Darmawangsa', 2024, 'Owner'],
 ['sri martini', 'f', 'E9', 'Darmawangsa', 2024, 'Owner'],
 ['fadilla rahmadani', 'f', 'C14', 'Darmawangsa', 2024, 'Owner'],
 ['ananda reyhan pradipta', 'm', 'F14', 'Darmawangsa', 2022, 'Owner'],
 ['masinah', 'f', 'E14', 'Darmawangsa', 2024, 'Owner'],
 ['d. maulana', 'm', 'B18', 'Darmawangsa', 2024, 'Owner'],
 ['kasri', 'm', 'B6', 'Darmawangsa', 2022, 'Owner'],
 ['salami', 'f', 'H16', 'Darmawangsa', 2022, 'Owner'],
 ['eko rudiyanto', 'm', 'E3', 'Darmawangsa', 2024, 'Owner'],
 ['desi susanti', 'f', 'D15', 'Darmawangsa', 2024, 'Owner'],
 ['hafizhan shidqi', 'm', 'C14', 'Kemayoran', 2022, 'Owner'],
 ['gandhi wibowo', 'm', 'F6', 'Kemayoran', 2024, 'Owner'],
 ['aldio mahendra purwandrarto', 'm', 'E2', 'Kemayoran', 2024, 'Owner'],
 ['benny putra', 'm', 'F14', 'Kemayoran', 2024, 'Owner'],
 ['vicky vernando dasta', 'm', 'G3', 'Kemayoran', 2024, 'Owner'],
 ['jufianto henri', 'm', 'C8', 'Kemayoran', 2022, 'Owner'],
 ['aan nuraini', 'f', 'A2', 'Kemayoran', 2024, 'Owner'],
 ['abdur rahman', 'm', 'F3', 'Kemayoran', 2023, 'Owner'],
 ['abdurrahman', 'm', 'D12', 'Kemayoran', 2024, 'Owner'],
 ['ade indra sukma', 'f', 'C12', 'Kemayoran', 2022, 'Rent'],
 ['ade irmayani', 'f', 'A12', 'Kemayoran', 2022, 'Owner'],
 ['bakti yoga fiyandana', 'm', 'B1', 'Kemayoran', 2024, 'Rent'],
 ['daniel sepra fatama', 'm', 'D5', 'Kemayoran', 2023, 'Rent'],
 ['dayu m sandro', 'm', 'F8', 'Kemayoran', 2023, 'Owner'],
 ['dean mareti hariani', 'f', 'E8', 'Kemayoran', 2024, 'Owner'],
 ['edi kurniawan wibowo', 'm', 'F1', 'Kemayoran', 2022, 'Rent'],
 ['fadil rahmat andini', 'm', 'C15', 'Kemayoran', 2022, 'Owner'],
 ['fahmi iqbal firmananda', 'm', 'E10', 'Kemayoran', 2024, 'Owner'],
 ['fairuzi', 'm', 'C7', 'Kemayoran', 2023, 'Owner'],
 ['gustian', 'm', 'A8', 'Kemayoran', 2023, 'Owner'],
 ["habil sabilla do'a", 'f', 'B17', 'Kemayoran', 2024, 'Owner'],

In [ ]:
# add res_id
# res_id prefix = year_of_inhabited + cluster_code + number_block + own_status_code + random number (4 digit)
# total

yoi = []
clus_code = []
num_block = []
own_code = []
rand_num = []

In [ ]:
for i in df_resident_list:
  yoi.append(i[4])

for j in df_resident_list:
  ind = cluster.index(j[3])
  clus_code.append(cluster_code[ind])

for i in df_resident_list:
  num_block.append(i[2])

for k in df_resident_list:
  ind = rumah.index(k[5])
  own_code.append(own_status_code[ind])

for i in range(789):
  rand_num.append(str(uuid.uuid4().int)[:6])

In [ ]:
id_fix = []
id = np.c_[yoi, clus_code, num_block, own_code, rand_num]

for i in id:
  id_fix.append(''.join(i))

In [ ]:
yoi

[2022,
 2022,
 2023,
 2024,
 2022,
 2022,
 2023,
 2022,
 2024,
 2023,
 2024,
 2023,
 2023,
 2023,
 2022,
 2022,
 2022,
 2023,
 2023,
 2024,
 2024,
 2022,
 2024,
 2022,
 2023,
 2022,
 2022,
 2024,
 2024,
 2024,
 2023,
 2024,
 2024,
 2024,
 2022,
 2022,
 2023,
 2023,
 2022,
 2022,
 2022,
 2022,
 2023,
 2022,
 2022,
 2024,
 2024,
 2022,
 2024,
 2022,
 2022,
 2024,
 2023,
 2022,
 2024,
 2022,
 2023,
 2024,
 2024,
 2023,
 2022,
 2024,
 2024,
 2023,
 2024,
 2022,
 2022,
 2024,
 2023,
 2024,
 2022,
 2023,
 2024,
 2024,
 2024,
 2024,
 2022,
 2023,
 2023,
 2022,
 2022,
 2022,
 2022,
 2024,
 2022,
 2024,
 2022,
 2022,
 2024,
 2022,
 2024,
 2023,
 2023,
 2024,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2023,
 2024,
 2022,
 2024,
 2023,
 2022,
 2024,
 2022,
 2023,
 2022,
 2023,
 2022,
 2022,
 2023,
 2022,
 2023,
 2024,
 2024,
 2024,
 2023,
 2024,
 2022,
 2022,
 2024,
 2024,
 2022,
 2024,
 2022,
 2024,
 2023,
 2024,
 2024,
 2024,
 2023,
 2024,
 2024,
 2024,
 2023,
 2022,
 2022,
 2023,
 2022,
 2024,
 2024,
 2022,
 2023,
 2022,
 2022,
 2022,
 2023,
 2022,
 2022,
 2024,
 2024,
 2024,
 2024,
 2022,
 2022,
 2022,
 2022,
 2024,
 2024,
 2023,
 2024,
 2022,
 2023,
 2024,
 2023,
 2023,
 2022,
 2023,
 2022,
 2024,
 2023,
 2022,
 2022,
 2023,
 2024,
 2023,
 2024,
 2022,
 2024,
 2023,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2023,
 2024,
 2023,
 2024,
 2022,
 2024,
 2024,
 2022,
 2022,
 2024,
 2022,
 2022,
 2024,
 2022,
 2023,
 2022,
 2022,
 2023,
 2022,
 2022,
 2022,
 2024,
 2024,
 2023,
 2023,
 2024,
 2022,
 2024,
 2022,
 2024,
 2024,
 2023,
 2022,
 2022,
 2023,
 2024,
 2022,
 2023,
 2024,
 2024,
 2022,
 2022,
 2024,
 2024,
 2023,
 2022,
 2022,
 2022,
 2024,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2023,
 2023,
 2024,
 2023,
 2023,
 2024,
 2022,
 2022,
 2024,
 2024,
 2024,
 2022,
 2022,
 2024,
 2024,
 2023,
 2022,
 2022,
 2024,
 2022,
 2024,
 2023,
 2022,
 2022,
 2024,
 2022,
 2024,
 2023,
 2024,
 2022,
 2023,
 2022,
 2024,
 2023,
 2022,
 2024,
 2024,
 2022,
 2023,
 2024,
 2022,
 2022,
 2023,
 2022,
 2022,
 2023,
 2023,
 2022,
 2022,
 2023,
 2022,
 2024,
 2022,
 2023,
 2022,
 2022,
 2024,
 2023,
 2024,
 2023,
 2024,
 2022,
 2024,
 2024,
 2024,
 2022,
 2024,
 2024,
 2022,
 2022,
 2024,
 2024,
 2022,
 2024,
 2024,
 2024,
 2024,
 2022,
 2024,
 2023,
 2024,
 2022,
 2022,
 2024,
 2023,
 2023,
 2024,
 2022,
 2022,
 2024,
 2023,
 2023,
 2024,
 2024,
 2022,
 2022,
 2024,
 2022,
 2024,
 2023,
 2024,
 2022,
 2024,
 2024,
 2022,
 2023,
 2023,
 2022,
 2022,
 2022,
 2022,
 2022,
 2024,
 2024,
 2023,
 2022,
 2023,
 2024,
 2024,
 2024,
 2023,
 2024,
 2024,
 2022,
 2023,
 2024,
 2022,
 2024,
 2024,
 2023,
 2024,
 2024,
 2023,
 2024,
 2024,
 2023,
 2022,
 2023,
 2023,
 2024,
 2024,
 2022,
 2023,
 2024,
 2024,
 2024,
 2023,
 2024,
 2024,
 2023,
 2024,
 2023,
 2022,
 2022,
 2022,
 2024,
 2024,
 2024,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2024,
 2022,
 2024,
 2022,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2024,
 2023,
 2024,
 2024,
 2023,
 2024,
 2022,
 2022,
 2024,
 2022,
 2024,
 2024,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2023,
 2023,
 2023,
 2023,
 2022,
 2024,
 2022,
 2024,
 2024,
 2024,
 2024,
 2022,
 2024,
 2024,
 2024,
 2022,
 2023,
 2022,
 2023,
 2024,
 2024,
 2024,
 2022,
 2023,
 2023,
 2024,
 2023,
 2024,
 2024,
 2024,
 2022,
 2024,
 2023,
 2023,
 2023,
 2022,
 2022,
 2022,
 2022,
 2024,
 2024,
 2024,
 2022,
 2024,
 2023,
 2022,
 2023,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2024,
 2024,
 2023,
 2024,
 2024,
 2022,
 2024,
 2024,
 2022,
 2022,
 2022,
 2023,
 2023,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2024,
 2022,
 2024,
 2023,
 2024,
 2022,
 2022,
 2024,
 2024,
 2022,
 2022,
 2022,
 2023,
 2022,
 2023,
 2022,
 2022,
 2024,
 2023,
 2022,
 2024,
 2024,
 2024,
 2024,
 2022,
 2023,
 2024,
 2024,
 2024,
 2022,
 2023,
 2023,
 2022,
 2024,
 2022,
 2024,
 2022,
 2022,
 2024,
 2024,
 2022,
 2022,
 2024,
 2022,
 2022,
 2024,
 2023,
 2022,
 2022,
 2024,
 2024,
 2023,
 2022,
 2022,
 2024,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2024,
 2024,
 2024,
 2022,
 2022,
 2022,
 2022,
 2023,
 2023,
 2024,
 2022,
 2024,
 2022,
 2023,
 2022,
 2022,
 2024,
 2024,
 2022,
 2022,
 2022,
 2023,
 2024,
 2022,
 2022,
 2024,
 2023,
 2024,
 2024,
 2024,
 2024,
 2022,
 2022,
 2024,
 2022,
 2023,
 2022,
 2024,
 2023,
 2024,
 2023,
 2022,
 2024,
 2023,
 2023,
 2023,
 2023,
 2022,
 2024,
 2023,
 2023,
 2024,
 2022,
 2024,
 2022,
 2023,
 2024,
 2023,
 2022,
 2024,
 2024,
 2024,
 2022,
 2022,
 2023,
 2022,
 2023,
 2023,
 2024,
 2024,
 2022,
 2024,
 2023,
 2022,
 2022,
 2022,
 2024,
 2024,
 2022,
 2022,
 2023,
 2024,
 2024,
 2024,
 2022,
 2024,
 2022,
 2022,
 2022,
 2022,
 2024,
 2023,
 2023,
 2022,
 2022,
 2024,
 2022,
 2024,
 2022,
 2023,
 2022,
 2024,
 2022,
 2024,
 2024,
 2024,
 2024,
 2024,
 2024,
 2023,
 2023,
 2022,
 2024,
 2022,
 2022,
 2024,
 2024,
 2023,
 2024,
 2022,
 2024,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2024,
 2022,
 2024,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2022,
 2024,
 2022,
 2022,
 2024,
 2023,
 2022,
 2023,
 2024,
 2022,
 2022,
 2024,
 2024,
 2022,
 2024,
 2023,
 2022,
 2023,
 2024,
 2022,
 2024,
 2022,
 2024,
 2022,
 2022,
 2022,
 2024,
 2022,
 2024,
 2023,
 2022,
 2024,
 2024,
 2022,
 2022,
 2023,
 2023,
 2023,
 2022,
 2024,
 2023,
 2024,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2022,
 2024,
 2023,
 2024,
 2024,
 2024,
 2022,
 2024,
 2022,
 2022,
 2024,
 2023,
 2024,
 2023,
 2022,
 2023,
 2022,
 2023,
 2022,
 2023]

In [ ]:
id_fix

['202203A1401484221',
 '202203B1902780908',
 '202303C1201119547',
 '202403D302160049',
 '202203C101563316',
 '202203G1201179026',
 '202303H1201633496',
 '202203G1501690987',
 '202403D2501171004',
 '202303G1101892420',
 '202403B2001196382',
 '202303D802517421',
 '202303H2501280011',
 '202303H101141935',
 '202203F101467154',
 '202203A1601285586',
 '202203D1801112245',
 '202303C401133155',
 '202303C802103588',
 '202403B1101794392',
 '202403D2701308369',
 '202203A501112667',
 '202403B1701600697',
 '202203D601240055',
 '202303A901220966',
 '202203F501295992',
 '202203E401265238',
 '202403B401236420',
 '202403H2101178578',
 '202403D2401187867',
 '202303D1201242806',
 '202403G1601312097',
 '202403D1101263990',
 '202403G901267851',
 '202203H2302381430',
 '202203A1001314392',
 '202303H301109854',
 '202303G601652294',
 '202203E501134039',
 '202203B1601208333',
 '202203D1301227936',
 '202203D101323962',
 '202303H501220892',
 '202203B901547192',
 '202203A1201429217',
 '202403A701848730',
 '202403H2001296930',
 '202203F901664817',
 '202403H2201127609',
 '202203H1502921274',
 '202203D1401175758',
 '202403E901278975',
 '202303C1301216791',
 '202203B501449940',
 '202403E302102225',
 '202203C701165915',
 '202303B2101195205',
 '202403F201111589',
 '202403H1402273790',
 '202303D1501206345',
 '202203C1001133824',
 '202403C1601244346',
 '202403C1402295046',
 '202303H601826045',
 '202403D2201135881',
 '202203D201180421',
 '202203H702309642',
 '202403D1601803577',
 '202303A1502209362',
 '202403A301475415',
 '202203A1301148997',
 '202303H1002215830',
 '202403G402335781',
 '202403A101308923',
 '202403B302280457',
 '202403C1501165303',
 '202203C602480434',
 '202303B801972722',
 '202303F401246810',
 '202203H1601108817',
 '202203D701987639',
 '202203B101246645',
 '202203B2301133830',
 '202403B1001120987',
 '202203B1302147788',
 '202403F1501118123',
 '202203C1701179846',
 '202203B201109026',
 '202403A801658283',
 '202203H202137999',
 '202403H401873238',
 '202303E801272421',
 '202303F1302126183',
 '202403B1501324342',
 '202203D501257426',
 '202203D2001107296',
 '202203F601243393',
 '202203H1802294413',
 '202203H901431797',
 '202203A201604186',
 '202403B1201156087',
 '202203H1901209011',
 '202203B1401152918',
 '202303G301213614',
 '202403D1901263826',
 '202203G701183988',
 '202403F1001329986',
 '202303D2301123613',
 '202203F1401104557',
 '202403D1001146841',
 '202203G1002337595',
 '202303E102169870',
 '202203B2401141059',
 '202303D2802241417',
 '202203H801263500',
 '202203F1601203366',
 '202303C201338628',
 '202203E702306142',
 '202303F1101113930',
 '202403G1301219716',
 '202403H2402144237',
 '202403D1701146338',
 '202303G501210424',
 '202403F701840492',
 '202203G202891331',
 '202203F801262359',
 '202403F301173185',
 '202403A401275540',
 '202203A601206031',
 '202403A1102678244',
 '202203F1701185213',
 '202403D902457460',
 '202303F1801368209',
 '202403B1801149933',
 '202403D401113526',
 '202403B2201114740',
 '202303E1001264395',
 '202403E201571358',
 '202403C1101101630',
 '202403G101130694',
 '202303E602303076',
 '202203G801100622',
 '202203D2101228983',
 '202303G1402245116',
 '202203D2601151103',
 '202403C901487836',
 '202403H1701127409',
 '202203B701157125',
 '202303F1201241070',
 '202203H1301295709',
 '202203B601470767',
 '202203C501226794',
 '202303C301125669',
 '202203H1102316053',
 '202204D1901164765',
 '202404F901326641',
 '202404B401216705',
 '202404H1301215987',
 '202404H901425975',
 '202204H1501182617',
 '202204F801423199',
 '202204B1901256452',
 '202204D601316282',
 '202404G1501462471',
 '202404D2801741030',
 '202304D2702852366',
 '202404C201164310',
 '202204B801197239',
 '202304C1801847516',
 '202404E401308752',
 '202304F301121757',
 '202304A401278605',
 '202204E801108719',
 '202304F1201296937',
 '202204C2001148004',
 '202404B2001268674',
 '202304C101147790',
 '202204E502117549',
 '202204C901139635',
 '202304D2001277197',
 '202404C502174563',
 '202304E701884866',
 '202404H1901142516',
 '202204G501308149',
 '202404D2601331110',
 '202304C702113204',
 '202204G1801173353',
 '202204C2101131088',
 '202204H2001505193',
 '202404G101282721',
 '202204A601160608',
 '202204G601297486',
 '202204D401287097',
 '202304A301887019',
 '202404G1101322919',
 '202304H601186699',
 '202404H2201172626',
 '202204F201271209',
 '202404H1101244647',
 '202404H401238752',
 '202204B1501333159',
 '202204B2402683619',
 '202404B2201148440',
 '202204G1401291206',
 '202204G202152887',
 '202404H701171834',
 '202204C602223288',
 '202304A702905622',
 '202204H2501185854',
 '202204A801315338',
 '202304G901425924',
 '202204D701261460',
 '202204B301179861',
 '202204H1701339447',
 '202404B101303360',
 '202404H801186252',
 '202304H1802121540',
 '202304G1601313448',
 '202404C1201315933',
 '202204A201235672',
 '202404E1602247621',
 '202204B901173219',
 '202404A1301275391',
 '202404D1001829653',
 '202304C401113416',
 '202204H2301759657',
 '202204E1301848777',
 '202304E101756498',
 '202404H301954737',
 '202204A1201201535',
 '202304D101141035',
 '202404C1101120516',
 '202404F1302138965',
 '202204F1001167407',
 '202204D2401714192',
 '202404A901162794',
 '202404B1201319750',
 '202304A1401230276',
 '202204H1401266437',
 '202204E1101238248',
 '202204D1702224691',
 '202404G301688096',
 '202404B202322370',
 '202204H501102478',
 '202204A101183585',
 '202204C1501285096',
 '202404F502164267',
 '202204F1501120952',
 '202204E1502221383',
 '202204D1801293350',
 '202304D501193423',
 '202304F401153396',
 '202404F1601237891',
 '202304F1701944800',
 '202304E1001625646',
 '202404D1401222944',
 '202204G1201140324',
 '202204A1701305934',
 '202404C1701189048',
 '202404F701387887',
 '202404C301161984',
 '202204C1601627721',
 '202204G1701203205',
 '202404B501297795',
 '202404B1401281974',
 '202304A502155370',
 '202204H102127990',
 '202204H1201214717',
 '202404B1101150111',
 '202204B1001379337',
 '202404B1601128953',
 '202304C801243624',
 '202204D2301330384',
 '202204D201192978',
 '202404A1501408083',
 '202204F101231580',
 '202404F1101151351',
 '202304D1101972339',
 '202404A1901780993',
 '202204D1601588854',
 '202304A1101266245',
 '202204C1901257804',
 '202404D2501160865',
 '202304B1301147196',
 '202204H2401196089',
 '202404A1801142793',
 '202404G1001304833',
 '202204F601335078',
 '202304B2301126887',
 '202404D2101228615',
 '202204H201323800',
 '202204E1201247964',
 '202304C1001335689',
 '202204D301167570',
 '202204C1301250375',
 '202304B1702291010',
 '202304H1001113075',
 '202204D1301150619',
 '202204G801309306',
 '202304H2101895386',
 '202204G401182094',
 '202404A1601144037',
 '202204D901235040',
 '202304B2101152066',
 '202204E601281692',
 '202204A1002318087',
 '202404G702168896',
 '202304D801591748',
 '202404G1301180583',
 '202304D1201191989',
 '202404B701245270',
 '202204D2201110048',
 '202404E201198430',
 '202404E901328743',
 '202404C1401481177',
 '202204F1401319546',
 '202404E1401224636',
 '202404B1801254349',
 '202204B601171832',
 '202204H1601103639',
 '202404E301281793',
 '202404D1501118793',
 '202201C1401853179',
 '202401F601359754',
 '202401E201297920',
 '202401F1401235688',
 '202401G301101004',
 '202201C801317909',
 '202401A201191724',
 '202301F301188942',
 '202401D1201107894',
 '202201C1202809227',
 '202201A1201426948',
 '202401B102234701',
 '202301D502974343',
 '202301F801276693',
 '202401E801252445',
 '202201F102790146',
 '202201C1501199660',
 '202401E1001106670',
 '202301C701179134',
 '202301A801904281',
 '202401B1701109505',
 '202401F201202238',
 '202201G202541683',
 '202201D101158382',
 '202401F1201779217',
 '202201B601106424',
 '202401G801179356',
 '202301C201982309',
 '202401B701695024',
 '202201F902905924',
 '202401E901143075',
 '202401D601653378',
 '202201B1201113844',
 '202301B1301213627',
 '202301B201546846',
 '202201G401244245',
 '202201G1301253610',
 '202201B1001207358',
 '202201D702362677',
 '202201G1001608779',
 '202401G701246853',
 '202401C401326861',
 '202301A1502183388',
 '202201F701108260',
 '202301G901113940',
 '202401E101318264',
 '202401D301150783',
 '202401B1101243838',
 '202301C601327311',
 '202401G1201334212',
 '202401A501146235',
 '202201A901507026',
 '202301F1502154785',
 '202401A102228816',
 '202201F1101221815',
 '202401F1301173506',
 '202401C1101107649',
 '202301C1002133645',
 '202401D1101627363',
 '202401A1101190007',
 '202301D801308666',
 '202401A601280325',
 '202401E301225335',
 '202301G102216110',
 '202201D1301145223',
 '202301G501200667',
 '202301B901146591',
 '202401D201540929',
 '202401B801179872',
 '202201G1401719738',
 '202301A1001253569',
 '202401A701148881',
 '202401C501122022',
 '202401E601136387',
 '202301A401642809',
 '202401C1302208095',
 '202401E501110403',
 '202301B301224486',
 '202401C301167805',
 '202301D901176102',
 '202201B1401850401',
 '202201C901322212',
 '202201F1001217139',
 '202401D1001284240',
 '202401B1501205318',
 '202401G601112118',
 '202201A301108298',
 '202201B1601123726',
 '202401G1101107053',
 '202201E701491693',
 '202201D401300318',
 '202201F501115170',
 '202401B501203099',
 '202401F401167127',
 '202201G1501107924',
 '202401B401149207',
 '202201A1301288974',
 '202201E402758418',
 '202201C101288165',
 '202201A1402124801',
 '202402A201239827',
 '202202C701229873',
 '202202D1301552394',
 '202402A1701120005',
 '202302E302100388',
 '202402C1701143547',
 '202402C801265119',
 '202302F1302195246',
 '202402D1601872975',
 '202202D101962373',
 '202202C1201172437',
 '202402E502319942',
 '202202F1101424127',
 '202402D1501209193',
 '202402D1101596820',
 '202202C501800334',
 '202402A101166842',
 '202202A901138368',
 '202202A701333112',
 '202202E601336341',
 '202402F1502224143',
 '202302D901324382',
 '202302B1701328116',
 '202302A301633979',
 '202302C601298963',
 '202202B601299496',
 '202402B901239731',
 '202202C1001505919',
 '202402C901126143',
 '202402D202265966',
 '202402B801115149',
 '202402C1801132090',
 '202202E201297512',
 '202402E101356311',
 '202402D601307858',
 '202402E1001179160',
 '202202B501290772',
 '202302E1301521228',
 '202202D302657812',
 '202302A1801927507',
 '202402B1601131742',
 '202402F1201315533',
 '202402E901163144',
 '202202A1501230829',
 '202302B1001129721',
 '202302C1502813393',
 '202402A1201241707',
 '202302F101968479',
 '202402D801748886',
 '202402C1102254400',
 '202402B201317470',
 '202202A602207641',
 '202402B101938680',
 '202302F201244676',
 '202302C1401466789',
 '202302F901987448',
 '202202D1401138938',
 '202202B302731350',
 '202202C102223243',
 '202202C2201217456',
 '202402D1201767228',
 '202402E1201290167',
 '202402A1901159184',
 '202202A501223919',
 '202402E401651754',
 '202302A801305305',
 '202202A1002110304',
 '202302C1901335849',
 '202202B701240388',
 '202402D2001152626',
 '202202E701236217',
 '202202A1101302656',
 '202202F802987140',
 '202402F501168754',
 '202202C1301286491',
 '202402D701299670',
 '202402D1001178925',
 '202302A401113504',
 '202402F701162485',
 '202402C2001275678',
 '202202B1401226233',
 '202402E1102128092',
 '202402B1201279945',
 '202202B401384147',
 '202202F602305637',
 '202202C2101117723',
 '202302A1401622676',
 '202302C2301320839',
 '202202C1601195229',
 '202202D1701182164',
 '202402D2101203838',
 '202202C301290842',
 '202202A1301127511',
 '202202C201250005',
 '202402E1401327550',
 '202202F1402326018',
 '202202D501219378',
 '202202F1001197538',
 '202402D1801213034',
 '202202F402101679',
 '202402D402143678',
 '202202B1301492479',
 '202402A1601308211',
 '202302D1901106684',
 '202402F1601271253',
 '202202C2402312923',
 '202202B1101246542',
 '202402B1501327618',
 '202402C401424971',
 '202202F301263245',
 '202202E801189745',
 '202205F1201285985',
 '202305E1301295371',
 '202205D2601280272',
 '202305A701116633',
 '202205E1601109221',
 '202205G1302218270',
 '202405D2401218543',
 '202305C801166506',
 '202205A1902132188',
 '202405F1101100006',
 '202405G1101135940',
 '202405D1301942024',
 '202405E601225422',
 '202205B101264950',
 '202305E1901143096',
 '202405E1801312459',
 '202405E2101107242',
 '202405E101509831',
 '202205E1402246535',
 '202305B1301190727',
 '202305A1802852992',
 '202205G1202279697',
 '202405A1101349923',
 '202205E801236358',
 '202405D2901241198',
 '202205D2501144382',
 '202205D2701175617',
 '202405G1401159917',
 '202405D1402221098',
 '202205B701776582',
 '202205A1601283628',
 '202405C201742307',
 '202205F1601256348',
 '202205F1402314072',
 '202405F101738229',
 '202305D1502256196',
 '202205F1501284189',
 '202205G801109789',
 '202405G101900114',
 '202405E1501336632',
 '202305F401134483',
 '202205D2801832921',
 '202205C501321139',
 '202405G301318301',
 '202205E1001361193',
 '202205A1502216446',
 '202205G602366386',
 '202205G201787901',
 '202205G1601222543',
 '202205A1201200089',
 '202205E1101186690',
 '202405B301740155',
 '202405B501315121',
 '202405G1501196476',
 '202205B1001253528',
 '202205G1002295821',
 '202205G402280480',
 '202205D601850713',
 '202305D1701234031',
 '202305B1501329570',
 '202405E501623818',
 '202205D1101531840',
 '202405E401207239',
 '202205D1901102592',
 '202305A401283221',
 '202205A301113441',
 '202205E901197032',
 '202405C302446920',
 '202405C701140964',
 '202205F301332759',
 '202205B801111631',
 '202205A1701526396',
 '202305A101308240',
 '202405E202112760',
 '202205E1701140408',
 '202205D1001560152',
 '202405G1701145656',
 '202305D1601150735',
 '202405A802133750',
 '202405D2002141807',
 '202405F901292073',
 '202405D2302117470',
 '202205D301288532',
 '202205C1001480756',
 '202405A501461539',
 '202205D2101461062',
 '202305F201111697',
 '202205F1301207251',
 '202405C1401265608',
 '202305B1402169207',
 '202405G1802152074',
 '202305A601188975',
 '202205B201199793',
 '202405B1601121577',
 '202305G901277825',
 '202305G701174259',
 '202305E2001336624',
 '202305C101495013',
 '202205F802178239',
 '202405F501327312',
 '202305C1101330232',
 '202305C601277661',
 '202405C401119285',
 '202205A901273746',
 '202405F602312162',
 '202205D701240051',
 '202305D1801316217',
 '202405B1701321590',
 '202305D902220197',
 '202205B1201263787',
 '202405C1301493744',
 '202405A1001116809',
 '202405F1702232944',
 '202205B601145862',
 '202205C901167922',
 '202305E301366610',
 '202205D801632854',
 '202305D1201575549',
 '202305A1401246523',
 '202405A1301163228',
 '202405F1001240087',
 '202205D2202159875',
 '202405B1101324358',
 '202305E701166824',
 '202205B401648434',
 '202205D201232212',
 '202205C1201237014',
 '202405D101234747',
 '202405F701297344',
 '202205G501188148',
 '202205E1201125278',
 '202305A2001271174',
 '202405D502112396',
 '202405B1801142744',
 '202405A201105583',
 '202205B901102355',
 '202405D401187664',
 '202206C202130077',
 '202206D2901210426',
 '202206E1702128836',
 '202206E901169493',
 '202406A201144730',
 '202306A601106544',
 '202306A501336471',
 '202206D702780727',
 '202206C101559067',
 '202406E602319818',
 '202206B901124420',
 '202406E1601259473',
 '202206A1501283043',
 '202306D1001176872',
 '202206A1102254803',
 '202406E1301239003',
 '202206B401226126',
 '202406F801229024',
 '202406D2702336165',
 '202406E1801595594',
 '202406D1801201195',
 '202406D1501233222',
 '202406E1401186634',
 '202306B1101122700',
 '202306C801324025',
 '202206A701138450',
 '202406D1301203708',
 '202206F1201303738',
 '202206D1201923432',
 '202406E1901234715',
 '202406A301778260',
 '202306D2001184176',
 '202406E102237069',
 '202206E1502287930',
 '202406C501192063',
 '202206E201339961',
 '202206C401350998',
 '202206D801254703',
 '202206E701171270',
 '202206D501839185',
 '202206A802223259',
 '202406B1701679487',
 '202206D2601316002',
 '202406A1201167551',
 '202406C901313408',
 '202206A1301465933',
 '202206D2302190663',
 '202206A901269732',
 '202406A2001143554',
 '202206F901264793',
 '202206F1102132096',
 '202406E1201136649',
 '202206B1502254951',
 '202206D1101114395',
 '202406E2101215629',
 '202306E1101201702',
 '202206B1302154200',
 '202306E1001202558',
 '202406A1701251650',
 '202206A1601925302',
 '202206E2001801822',
 '202406C1401172450',
 '202406D2501255607',
 '202206D102117970',
 '202406B1201104445',
 '202306F301272813',
 '202206D1601169629',
 '202306C1201110502',
 '202406F502120811',
 '202206B801308195',
 '202406F1001214014',
 '202206B601226954',
 '202406B501144336',
 '202206F101329788',
 '202206A1401338695',
 '202206B201218297',
 '202406D201148732',
 '202206F1302338233',
 '202406A1901177085',
 '202306C302955398',
 '202206E801280652',
 '202406D2801403533',
 '202406F401113300',
 '202206C701571492',
 '202206C1001297572',
 '202306B1601181587',
 '202306C1101653287',
 '202306D2201203796',
 '202206D901196388',
 '202406A1801210953',
 '202306D301735124',
 '202406D1901170712',
 '202206D2401226968',
 '202206B301294309',
 '202206E401708348',
 '202206D601191240',
 '202206F201195965',
 '202206B1801196806',
 '202206B1001110151',
 '202206E501337440',
 '202406F601263064',
 '202306D401115813',
 '202406B101897168',
 '202406D1701301372',
 '202406D2101241196',
 '202206F1702240926',
 '202406F1401144992',
 '202206E301202951',
 '202206C1301284351',
 '202406A401298954',
 '202306F701120139',
 '202406A102244727',
 '202306F1601599036',
 '202206B701220346',
 '202306C601771793',
 '202206F1501125594',
 '202306A1001204032',
 '202206B1401296048',
 '202306D1402203158']

In [ ]:
df_resident['res_id'] = id_fix
df_resident

,Name,Gender,Block,Cluster,year_of_inhabited,own_status,res_id
0,ridha ulva,f,A14,Ancol,2022,Owner,202203A1401484221
1,rizqi wahyuningsih,f,B19,Ancol,2022,Rent,202203B1902780908
2,ruwadi saputra,m,C12,Ancol,2023,Owner,202303C1201119547
3,sugeng hermawan,m,D3,Ancol,2024,Rent,202403D302160049
4,suliatun,f,C1,Ancol,2022,Owner,202203C101563316
...,...,...,...,...,...,...,...
784,sutiti,f,C6,Thamrin,2023,Owner,202306C601771793
785,jefri setiadi,m,F15,Thamrin,2022,Owner,202206F1501125594
786,dwi maryani,f,A10,Thamrin,2023,Owner,202306A1001204032
787,krisno tri widodo,m,B14,Thamrin,2022,Owner,202206B1401296048
788,katiman,m,D14,Thamrin,2023,Rent,202306D1402203158

In [ ]:
df_resident.to_csv('resident_block.csv', index=False)

In [ ]:
df_resident_id = df_resident[['res_id','Name', 'own_status']]
df_resident_id

                res_id                Name own_status
0    202203A1401484221          ridha ulva      Owner
1    202203B1902780908  rizqi wahyuningsih       Rent
2    202303C1201119547      ruwadi saputra      Owner
3     202403D302160049     sugeng hermawan       Rent
4     202203C101563316            suliatun      Owner
..                 ...                 ...        ...
784   202306C601771793              sutiti      Owner
785  202206F1501125594       jefri setiadi      Owner
786  202306A1001204032         dwi maryani      Owner
787  202206B1401296048   krisno tri widodo      Owner
788  202306D1402203158             katiman       Rent

[789 rows x 3 columns]

In [ ]:
df_resident_id.to_csv('resident_id.csv', index=False)

# Add general resident info

In [2]:
df_resident_info = pd.read_csv('resident_id.csv')
df_resident_block = pd.read_csv('resident_block.csv')

In [3]:
# Adding age to database 
age = np.random.randint(low=25, high=46, size=789)
age

array([27, 40, 28, 45, 33, 40, 35, 37, 36, 33, 41, 25, 44, 28, 38, 33, 37,
       27, 27, 32, 43, 27, 35, 43, 26, 34, 34, 44, 28, 27, 29, 43, 41, 25,
       29, 30, 35, 29, 40, 33, 27, 38, 25, 37, 40, 27, 40, 32, 28, 33, 31,
       33, 32, 36, 29, 28, 33, 34, 26, 40, 35, 27, 45, 44, 42, 40, 32, 33,
       41, 27, 27, 43, 32, 27, 42, 37, 34, 29, 41, 41, 36, 36, 32, 33, 36,
       27, 32, 28, 44, 38, 35, 44, 25, 27, 42, 37, 31, 29, 38, 30, 25, 32,
       28, 32, 37, 25, 33, 33, 40, 40, 25, 26, 25, 32, 33, 41, 41, 39, 41,
       29, 44, 26, 43, 32, 40, 38, 40, 40, 27, 29, 36, 39, 45, 32, 28, 38,
       41, 40, 37, 38, 43, 29, 42, 36, 40, 34, 36, 35, 30, 35, 44, 27, 36,
       34, 36, 31, 45, 45, 39, 41, 44, 36, 39, 26, 42, 25, 32, 40, 29, 43,
       37, 33, 42, 28, 34, 25, 30, 42, 26, 30, 35, 36, 33, 30, 37, 34, 30,
       29, 42, 34, 39, 41, 26, 33, 40, 45, 37, 44, 44, 33, 34, 25, 42, 29,
       33, 34, 36, 36, 36, 37, 39, 27, 40, 25, 36, 44, 29, 33, 45, 31, 40,
       40, 36, 43, 43, 37, 43, 37, 25, 44, 28, 25, 25, 36, 44, 39, 37, 30,
       39, 45, 44, 34, 31, 36, 38, 25, 34, 42, 34, 29, 27, 34, 27, 32, 25,
       27, 25, 37, 34, 39, 37, 40, 43, 41, 39, 28, 28, 42, 25, 42, 30, 39,
       40, 43, 30, 37, 25, 42, 44, 27, 38, 28, 26, 27, 27, 33, 42, 38, 26,
       30, 37, 32, 25, 38, 25, 43, 36, 25, 39, 43, 44, 37, 36, 27, 43, 42,
       32, 41, 36, 31, 40, 39, 29, 37, 32, 37, 28, 38, 36, 35, 38, 26, 29,
       43, 28, 28, 43, 28, 25, 25, 41, 45, 33, 41, 40, 32, 31, 32, 40, 38,
       45, 42, 30, 39, 42, 45, 28, 32, 37, 30, 42, 45, 41, 27, 28, 33, 39,
       27, 42, 30, 38, 32, 43, 38, 43, 32, 36, 43, 36, 41, 36, 27, 43, 44,
       25, 33, 30, 25, 38, 35, 38, 34, 33, 42, 38, 41, 41, 34, 30, 38, 30,
       38, 35, 42, 41, 35, 33, 27, 28, 33, 35, 27, 39, 33, 37, 39, 36, 41,
       39, 25, 27, 28, 27, 27, 34, 25, 27, 25, 38, 34, 41, 42, 35, 44, 26,
       42, 30, 27, 38, 42, 36, 33, 25, 32, 43, 36, 38, 31, 31, 37, 30, 35,
       33, 45, 28, 43, 32, 42, 32, 43, 34, 44, 35, 32, 27, 28, 36, 35, 44,
       25, 28, 31, 26, 27, 44, 31, 31, 27, 40, 29, 36, 27, 30, 26, 44, 41,
       31, 28, 29, 29, 39, 30, 45, 44, 45, 33, 30, 28, 28, 32, 33, 38, 29,
       34, 26, 44, 36, 28, 37, 45, 35, 25, 35, 29, 28, 29, 37, 35, 26, 34,
       38, 40, 30, 29, 36, 32, 25, 36, 33, 29, 38, 35, 27, 25, 31, 26, 38,
       35, 31, 43, 26, 38, 35, 35, 44, 28, 37, 42, 27, 28, 41, 41, 35, 32,
       44, 32, 35, 39, 42, 33, 40, 29, 41, 31, 33, 25, 30, 28, 38, 37, 30,
       33, 25, 26, 39, 44, 26, 36, 34, 42, 31, 39, 42, 29, 45, 25, 39, 42,
       38, 28, 41, 37, 35, 33, 25, 27, 32, 45, 29, 36, 35, 39, 45, 28, 26,
       32, 45, 37, 29, 33, 43, 38, 44, 39, 41, 35, 28, 37, 30, 31, 30, 41,
       45, 33, 44, 29, 42, 39, 40, 45, 26, 41, 39, 44, 41, 28, 39, 38, 32,
       45, 43, 25, 31, 26, 25, 38, 43, 25, 44, 40, 40, 39, 26, 36, 33, 29,
       35, 26, 36, 45, 38, 30, 33, 36, 41, 39, 39, 37, 25, 29, 43, 30, 25,
       45, 36, 33, 34, 39, 37, 43, 29, 26, 34, 28, 45, 38, 35, 43, 31, 26,
       29, 31, 27, 26, 44, 26, 36, 45, 31, 25, 30, 33, 31, 36, 38, 34, 34,
       27, 28, 32, 26, 44, 44, 38, 28, 36, 36, 27, 25, 25, 45, 41, 42, 25,
       25, 27, 38, 30, 37, 40, 29, 37, 32, 25, 33, 35, 40, 32, 27, 28, 41,
       34, 33, 29, 31, 38, 39, 35, 33, 38, 42, 45, 41, 44, 33, 45, 36, 28,
       27, 28, 34, 32, 32, 29, 43, 39, 38, 37, 44, 44, 34, 35, 43, 34, 44,
       36, 43, 31, 28, 38, 41, 29, 28, 29, 33, 40, 31, 32, 26, 27, 40, 30,
       31, 34, 36, 36, 33, 37, 37], dtype=int32)

In [4]:
df_resident_info['age'] = age
df_resident_info

                res_id                Name own_status  age
0    202203A1401484221          ridha ulva      Owner   27
1    202203B1902780908  rizqi wahyuningsih       Rent   40
2    202303C1201119547      ruwadi saputra      Owner   28
3     202403D302160049     sugeng hermawan       Rent   45
4     202203C101563316            suliatun      Owner   33
..                 ...                 ...        ...  ...
784   202306C601771793              sutiti      Owner   36
785  202206F1501125594       jefri setiadi      Owner   36
786  202306A1001204032         dwi maryani      Owner   33
787  202206B1401296048   krisno tri widodo      Owner   37
788  202306D1402203158             katiman       Rent   37

[789 rows x 4 columns]

In [5]:
df_resident_user = df_resident_info.drop(columns=['own_status','age'])
df_resident_user

                res_id                Name
0    202203A1401484221          ridha ulva
1    202203B1902780908  rizqi wahyuningsih
2    202303C1201119547      ruwadi saputra
3     202403D302160049     sugeng hermawan
4     202203C101563316            suliatun
..                 ...                 ...
784   202306C601771793              sutiti
785  202206F1501125594       jefri setiadi
786  202306A1001204032         dwi maryani
787  202206B1401296048   krisno tri widodo
788  202306D1402203158             katiman

[789 rows x 2 columns]

In [6]:
df_resident_info['sex'] = df_resident_block['Gender']
df_resident_info

                res_id                Name own_status  age sex
0    202203A1401484221          ridha ulva      Owner   27   f
1    202203B1902780908  rizqi wahyuningsih       Rent   40   f
2    202303C1201119547      ruwadi saputra      Owner   28   m
3     202403D302160049     sugeng hermawan       Rent   45   m
4     202203C101563316            suliatun      Owner   33   f
..                 ...                 ...        ...  ...  ..
784   202306C601771793              sutiti      Owner   36   f
785  202206F1501125594       jefri setiadi      Owner   36   m
786  202306A1001204032         dwi maryani      Owner   33   f
787  202206B1401296048   krisno tri widodo      Owner   37   m
788  202306D1402203158             katiman       Rent   37   m

[789 rows x 5 columns]

In [8]:
# adding phone number 
prov = ['0812','0821','0813','0852','0856','0817','0818']
rand_prov = random.choices(prov, weights=[110, 166, 56, 74, 113, 155, 115], k=789)

rand_num = []

for i in range(789):
  rand_num.append(str(uuid.uuid4().int)[:8])
  

num_fix = []
num = np.c_[rand_prov,rand_num]

for i in num:
  num_fix.append(''.join(i))
  

df_resident_info['phone_number'] = num_fix
df_resident_info

                res_id                Name own_status  age sex  phone_number
0    202203A1401484221          ridha ulva      Owner   27   f  081226323643
1    202203B1902780908  rizqi wahyuningsih       Rent   40   f  081812892732
2    202303C1201119547      ruwadi saputra      Owner   28   m  085622339854
3     202403D302160049     sugeng hermawan       Rent   45   m  082124651008
4     202203C101563316            suliatun      Owner   33   f  081857731152
..                 ...                 ...        ...  ...  ..           ...
784   202306C601771793              sutiti      Owner   36   f  081746676774
785  202206F1501125594       jefri setiadi      Owner   36   m  081729388620
786  202306A1001204032         dwi maryani      Owner   33   f  085251719758
787  202206B1401296048   krisno tri widodo      Owner   37   m  085620695962
788  202306D1402203158             katiman       Rent   37   m  082146758427

[789 rows x 6 columns]

In [9]:
# adding  work field and company 
work_field = ['perkebunan','perikanan dan peternakan','pertambangan, minyak, dan gas','pengolahan industri','konstruksi','otomotif','logistik','teknologi dan informasi','aktifitas profesional, ilmiah, dan teknis','keuangan dan asuransi','properti','perdagangan umum','Administasi dan manajemen','transportasi','pendidikan','kesehatan', 'hukum', 'media']
occup = ['karyawan swasta','PNS','pegawai BUMN','wirausaha','dokter','perawat','pengacara','wartawan','guru']


kerjaan = {
            'perkebunan':['karyawan swasta','pegawai BUMN', 'PNS', 'wirausaha'],
            'perikanan dan peternakan': ['wirausaha','PNS', 'karyawan swasta'],
            'pertambangan, minyak, dan gas' : ['PNS','karyawan swasta', 'pegawai BUMN'],
            'pengolahan industri': ['karyawan swasta', 'pegawai BUMN', 'wirausaha'],
            'konstruksi':['karyawan swasta', 'pegawai BUMN', 'PNS', 'wirausaha'],
            'otomotif':['karyawan swasta','wirausaha'],
            'logistik':['karyawan swasta', 'pegawai BUMN', 'wirausaha'],
            'teknologi dan informasi':['PNS','karyawan swasta', 'pegawai BUMN', 'wirausaha'],
            'aktifitas profesional, ilmiah, dan teknis': ['karyawan swasta', 'wirausaha'],
            'keuangan dan asuransi':['karyawan swasta', 'pegawai BUMN', 'wirausaha', 'PNS'],
            'properti':['karyawan swasta', 'wirausaha', 'PNS'],
            'perdagangan umum':['karyawan swasta', 'wirausaha', 'pegawai BUMN'],
            'Administasi dan manajemen':['karyawan swasta','pegawai BUMN', 'PNS'],
            'transportasi':['karyawan swasta', 'pegawai BUMN', 'wirausaha'],
            'pendidikan':['karyawan swasta', 'guru'],
            'kesehatan':['dokter', 'perawat', 'PNS', 'pegawai BUMN'],
            'hukum':['pengacara', 'karyawan swasta', 'pegawai BUMN', 'PNS'], 
            'media':['karyawan swasta', 'wartawan']
          }

rand_work_field = random.choices(work_field, weights=[5, 11, 15, 70, 20, 15, 12, 138, 10, 124, 49, 57, 150, 10, 23, 30, 40, 10], k=789)

df_resident_info['work_field'] = rand_work_field

occupation = []
for i in df_resident_info['work_field']:
        occupation.append(random.choice(kerjaan[i]))
        
df_resident_info['occupation'] = occupation
df_resident_info

,res_id,Name,own_status,age,sex,phone_number,work_field,occupation
0,202203A1401484221,ridha ulva,Owner,27,f,081226323643,konstruksi,karyawan swasta
1,202203B1902780908,rizqi wahyuningsih,Rent,40,f,081812892732,pendidikan,guru
2,202303C1201119547,ruwadi saputra,Owner,28,m,085622339854,teknologi dan informasi,PNS
3,202403D302160049,sugeng hermawan,Rent,45,m,082124651008,properti,wirausaha
4,202203C101563316,suliatun,Owner,33,f,081857731152,perdagangan umum,karyawan swasta
...,...,...,...,...,...,...,...,...
784,202306C601771793,sutiti,Owner,36,f,081746676774,keuangan dan asuransi,pegawai BUMN
785,202206F1501125594,jefri setiadi,Owner,36,m,081729388620,pendidikan,guru
786,202306A1001204032,dwi maryani,Owner,33,f,085251719758,teknologi dan informasi,karyawan swasta
787,202206B1401296048,krisno tri widodo,Owner,37,m,085620695962,Administasi dan manajemen,PNS
788,202306D1402203158,katiman,Rent,37,m,082146758427,teknologi dan informasi,pegawai BUMN

In [10]:
df_info = pd.read_csv('df_resident_info.csv')

In [13]:
tel = df_info['phone_number'].apply(str)
tel = '0' + tel
tel

0      081710322699
1      081285210057
2      085218469647
3      082139816931
4      082119094223
           ...
784    081715507531
785    082117929241
786    085682060265
787    081254954600
788    081733404074
Name: phone_number, Length: 789, dtype: object

In [14]:
df_info['phone_number'] = tel 
df_info

                res_id  age sex  phone_number marital_status
0    202203A1401484221   31   f  081710322699          kawin
1    202203B1902780908   30   f  081285210057          kawin
2    202303C1201119547   39   m  085218469647     cerai mati
3     202403D302160049   30   m  082139816931          kawin
4     202203C101563316   25   f  082119094223    belum kawin
..                 ...  ...  ..           ...            ...
784   202306C601771793   35   f  081715507531          kawin
785  202206F1501125594   44   m  082117929241          kawin
786  202306A1001204032   25   f  085682060265    belum kawin
787  202206B1401296048   27   m  081254954600    belum kawin
788  202306D1402203158   40   m  081733404074          kawin

[789 rows x 5 columns]

In [15]:
df_info.to_csv('df_info.csv', index=False)