In [1]:
import pandas as pd
import numpy as np
import random
import uuid

In [77]:
merchant= {'grocery':['Indomaret','Alfamart','Idolmart','Superindo'],
           'fnb':['Mixue','Haus','Mie Gacoan','Sederhana','Fore Coffee','Kopi Kenangan'],
           'laundry':['Ceria','Si Bersih'],
           'retail':['Miniso','Nice So','Intermedia']
          }

group = []
name = []
merchant_id = []

for j in merchant.values():
    for k in j:
        name.append(k)
            
df_merchant = pd.DataFrame({'name_merchant':name})

merchant_id = ["{:02d}".format(i) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
df_merchant['merchant_id'] = merchant_id

def corresponding_key(val, dictionary):
        for k, v in dictionary.items():
            if val in v:
                return k

group = []
for i in df_merchant['name_merchant'].values.tolist():
    group.append(corresponding_key(i,merchant))

df_merchant['group']=group

df_merchant

    name_merchant merchant_id    group
0       Indomaret          00  grocery
1        Alfamart          01  grocery
2        Idolmart          02  grocery
3       Superindo          03  grocery
4           Mixue          04      fnb
5            Haus          05      fnb
6      Mie Gacoan          06      fnb
7       Sederhana          07      fnb
8     Fore Coffee          08      fnb
9   Kopi Kenangan          09      fnb
10          Ceria          10  laundry
11      Si Bersih          11  laundry
12         Miniso          12   retail
13        Nice So          13   retail
14     Intermedia          14   retail

In [13]:
rating = []

for i in range(len(df_merchant['name_merchant'].values.tolist())):
    rating.append(round(random.uniform(4.1,4.9),1))

df_merchant['rating']=rating

df_merchant

    name_merchant merchant_id    group  rating
0       Indomaret          00  grocery     4.3
1        Alfamart          01  grocery     4.8
2        Idolmart          02  grocery     4.4
3       Superindo          03  grocery     4.2
4           Mixue          04      fnb     4.4
5            Haus          05      fnb     4.5
6      Mie Gacoan          06      fnb     4.5
7       Sederhana          07      fnb     4.8
8     Fore Coffee          08      fnb     4.9
9   Kopi Kenangan          09      fnb     4.7
10          Ceria          10  laundry     4.2
11      Si Bersih          11  laundry     4.4
12         Miniso          12   retail     4.6
13        Nice So          13   retail     4.3
14     Intermedia          14   retail     4.8

In [24]:
dist_ancol = [round(random.uniform(0.3, 1.5),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_ancol

[1.3, 1.3, 1.2, 1.4, 0.9, 0.6, 1.2, 0.3, 0.5, 1.1, 0.5, 1.0, 0.8, 1.3, 0.6]

In [17]:
dist_kemayoran = [round(random.uniform(0.5, 1.7),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_kemayoran

[0.8, 1.0, 1.5, 0.9, 0.5, 0.7, 1.6, 1.6, 1.1, 0.8, 1.1, 0.9, 1.5, 1.2, 1.1]

In [18]:
dist_darmawangsa = [round(random.uniform(0.7, 1.9),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_darmawangsa

[1.2, 1.5, 1.4, 1.2, 1.2, 1.8, 0.7, 1.8, 1.3, 1.6, 1.4, 0.8, 1.7, 1.3, 0.8]

In [19]:
dist_menteng = [round(random.uniform(0.3, 1.0),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_menteng

[0.8, 0.6, 0.3, 0.8, 0.4, 0.8, 0.3, 0.9, 0.6, 0.6, 0.9, 0.5, 0.6, 0.7, 0.6]

In [20]:
dist_senayan = [round(random.uniform(0.8, 2.0),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_senayan

[1.8, 1.3, 1.4, 1.2, 1.1, 1.9, 0.8, 1.1, 1.3, 1.2, 0.9, 1.9, 1.7, 1.8, 1.8]

In [21]:
dist_thamrin = [round(random.uniform(0.1, 1.3),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]
dist_thamrin

[0.3, 0.8, 0.2, 0.4, 0.6, 0.9, 0.6, 0.2, 0.4, 0.5, 1.1, 0.2, 0.9, 0.9, 1.1]

In [27]:




col = ['dist_ancol','dist_kemayoran','dist_darmawangsa','dist_menteng','dist_senayan','dist_thamrin']
dist_data = [dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin]

for i, j in zip(col,dist_data):
    df_merchant[i] = j

df_merchant

,name_merchant,merchant_id,group,rating,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin
0,Indomaret,00,grocery,4.3,1.3,0.8,1.2,0.8,1.8,0.3
1,Alfamart,01,grocery,4.8,1.3,1.0,1.5,0.6,1.3,0.8
2,Idolmart,02,grocery,4.4,1.2,1.5,1.4,0.3,1.4,0.2
3,Superindo,03,grocery,4.2,1.4,0.9,1.2,0.8,1.2,0.4
4,Mixue,04,fnb,4.4,0.9,0.5,1.2,0.4,1.1,0.6
5,Haus,05,fnb,4.5,0.6,0.7,1.8,0.8,1.9,0.9
6,Mie Gacoan,06,fnb,4.5,1.2,1.6,0.7,0.3,0.8,0.6
7,Sederhana,07,fnb,4.8,0.3,1.6,1.8,0.9,1.1,0.2
8,Fore Coffee,08,fnb,4.9,0.5,1.1,1.3,0.6,1.3,0.4
9,Kopi Kenangan,09,fnb,4.7,1.1,0.8,1.6,0.6,1.2,0.5
10,Ceria,10,laundry,4.2,0.5,1.1,1.4,0.9,0.9,1.1
11,Si Bersih,11,laundry,4.4,1.0,0.9,0.8,0.5,1.9,0.2
12,Miniso,12,retail,4.6,0.8,1.5,1.7,0.6,1.7,0.9
13,Nice So,13,retail,4.3,1.3,1.2,1.3,0.7,1.8,0.9
14,Intermedia,14,retail,4.8,0.6,1.1,0.8,0.6,1.8,1.1

In [28]:
df_merchant.to_csv('df_merchant.csv',index=False)

In [15]:
reviews = [round(random.randint(2, 10),1) for i in range(len(df_merchant['name_merchant'].values.tolist()))]

In [87]:
df_merchant['reviews'] = reviews
df_merchant

,name_merchant,merchant_id,merchant_group,rating,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,reviews
0,Indomaret,00,grocery,4.3,1.3,0.8,1.2,0.8,1.8,0.3,18
1,Alfamart,01,grocery,4.8,1.3,1.0,1.5,0.6,1.3,0.8,16
2,Idolmart,02,grocery,4.4,1.2,1.5,1.4,0.3,1.4,0.2,11
3,Superindo,03,grocery,4.2,1.4,0.9,1.2,0.8,1.2,0.4,12
4,Mixue,04,fnb,4.4,0.9,0.5,1.2,0.4,1.1,0.6,17
5,Haus,05,fnb,4.5,0.6,0.7,1.8,0.8,1.9,0.9,10
6,Mie Gacoan,06,fnb,4.5,1.2,1.6,0.7,0.3,0.8,0.6,15
7,Sederhana,07,fnb,4.8,0.3,1.6,1.8,0.9,1.1,0.2,19
8,Fore Coffee,08,fnb,4.9,0.5,1.1,1.3,0.6,1.3,0.4,18
9,Kopi Kenangan,09,fnb,4.7,1.1,0.8,1.6,0.6,1.2,0.5,15
10,Ceria,10,laundry,4.2,0.5,1.1,1.4,0.9,0.9,1.1,12
11,Si Bersih,11,laundry,4.4,1.0,0.9,0.8,0.5,1.9,0.2,12
12,Miniso,12,retail,4.6,0.8,1.5,1.7,0.6,1.7,0.9,11
13,Nice So,13,retail,4.3,1.3,1.2,1.3,0.7,1.8,0.9,11
14,Intermedia,14,retail,4.8,0.6,1.1,0.8,0.6,1.8,1.1,14

In [36]:
df_merchant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name_merchant     15 non-null     object
 1   merchant_id       15 non-null     object
 2   group             15 non-null     object
 3   rating            15 non-null     float64
 4   dist_ancol        15 non-null     float64
 5   dist_kemayoran    15 non-null     float64
 6   dist_darmawangsa  15 non-null     float64
 7   dist_menteng      15 non-null     float64
 8   dist_senayan      15 non-null     float64
 9   dist_thamrin      15 non-null     float64
 10  reviews           15 non-null     int64
dtypes: float64(7), int64(1), object(3)
memory usage: 1.4+ KB

In [45]:
df_merchant = df_merchant.rename(columns={'group':'merchant_group'})

In [48]:
df_merchant.to_csv('df_merchant.csv',index=False)

In [95]:
# add review
import random
import pandas as pd
import datetime

def generate_random_date(start_date, end_date):
  """Generate a random date between two dates."""
  start_us = start_date.timestamp()
  end_us = end_date.timestamp()
  random_time = random.randint(start_us, end_us)
  return datetime.datetime.fromtimestamp(random_time)

def generate_synthetic_reviews():
  """Generates synthetic review data for various merchants."""

  categories = [i for i in df_merchant['merchant_group']]
  adjectives = ["baik", "buruk", "sangat baik", "sangat buruk"]
  nouns = ["pelayanan", "makanan dan minuman", "barang", "suasana"]
  review_templates = [
      " {noun} {adjective}.",
      "{noun}nya {adjective}, dimohon untuk {noun}nya ditingkatkan lagi.",
      "Saya mengalami pengalaman {adjective} secara keseluruhan.",
  
  ]

  data = []
  for category in categories:
    for _ in range(10):  # Generate 10 reviews per category
      merchant_name = f"{category} {random.randint(1, 1000)}"
      rating = random.randint(1, 5)

      # Generate review based on category
      if category == "fnb":
        nouns.extend(["penyajian", "suasana", "harga"])
      elif category == "grocery" and category == 'retail':
        nouns.extend(["produk", "harga", "kebersihan"])
      elif category == "laundry":
        nouns.extend(["kebersihan", "kualitas", "waktu pengerjaan"])

      review = random.choice(review_templates).format(
          adjective=random.choice(adjectives),
          noun=random.choice(nouns)
      )
      date = generate_random_date(datetime.datetime(2023, 1, 1), datetime.datetime(2024, 1, 1))

      # Remove category-specific nouns after generating review
      if category == "Restaurant":
        nouns.remove("penyajian")
        nouns.remove("suasana")
        nouns.remove("harga")
      elif category == "grocery" and category == 'retail':
        nouns.remove("produk")
        nouns.remove("harga")
        nouns.remove("kebersihan")
      elif category == "laundry":
        nouns.remove("kebersihan")
        nouns.remove("kualitas")
        nouns.remove("waktu pengerjaan")

      data.append([merchant_name, category, rating, review, date.strftime('%Y-%m-%d')])

  df = pd.DataFrame(data, columns=['merchant_name', 'category', 'rating', 'review', 'date'])
  return df

# Generate and save the dataset
df = generate_synthetic_reviews()

In [96]:
df

,merchant_name,category,rating,review,date
0,grocery 89,grocery,3,"makanan dan minumannya sangat baik, dimohon un...",2023-08-22
1,grocery 356,grocery,3,pelayanan baik.,2023-02-02
2,grocery 397,grocery,5,Saya mengalami pengalaman sangat baik secara k...,2023-01-03
3,grocery 455,grocery,2,"pelayanannya buruk, dimohon untuk pelayanannya...",2023-02-28
4,grocery 944,grocery,5,pelayanan baik.,2023-12-31
...,...,...,...,...,...
145,retail 144,retail,5,"harganya buruk, dimohon untuk harganya ditingk...",2023-03-13
146,retail 325,retail,2,"suasananya baik, dimohon untuk suasananya diti...",2023-07-26
147,retail 185,retail,4,"harganya sangat buruk, dimohon untuk harganya ...",2023-06-30
148,retail 701,retail,5,Saya mengalami pengalaman sangat baik secara k...,2023-08-03
149,retail 274,retail,4,harga sangat baik.,2023-08-14

In [26]:
df_review.to_csv('df_review.csv', index=False)

In [2]:
df_review = pd.read_csv('df_review.csv')
df_review

,merchant_name,category,rating,review,date
0,grocery 89,grocery,3,"makanan dan minumannya sangat baik, dimohon un...",2023-08-22
1,grocery 356,grocery,3,pelayanan baik.,2023-02-02
2,grocery 397,grocery,5,Saya mengalami pengalaman sangat baik secara k...,2023-01-03
3,grocery 455,grocery,2,"pelayanannya buruk, dimohon untuk pelayanannya...",2023-02-28
4,grocery 944,grocery,5,pelayanan baik.,2023-12-31
...,...,...,...,...,...
145,retail 144,retail,5,"harganya buruk, dimohon untuk harganya ditingk...",2023-03-13
146,retail 325,retail,2,"suasananya baik, dimohon untuk suasananya diti...",2023-07-26
147,retail 185,retail,4,"harganya sangat buruk, dimohon untuk harganya ...",2023-06-30
148,retail 701,retail,5,Saya mengalami pengalaman sangat baik secara k...,2023-08-03
149,retail 274,retail,4,harga sangat baik.,2023-08-14

In [4]:
df_review['sentiment'] = df_review['review'].str.contains('|'.join(['buruk','sangat buruk']))
df_review

,merchant_name,category,rating,review,date,sentiment
0,grocery 89,grocery,3,"makanan dan minumannya sangat baik, dimohon un...",2023-08-22,False
1,grocery 356,grocery,3,pelayanan baik.,2023-02-02,False
2,grocery 397,grocery,5,Saya mengalami pengalaman sangat baik secara k...,2023-01-03,False
3,grocery 455,grocery,2,"pelayanannya buruk, dimohon untuk pelayanannya...",2023-02-28,True
4,grocery 944,grocery,5,pelayanan baik.,2023-12-31,False
...,...,...,...,...,...,...
145,retail 144,retail,5,"harganya buruk, dimohon untuk harganya ditingk...",2023-03-13,True
146,retail 325,retail,2,"suasananya baik, dimohon untuk suasananya diti...",2023-07-26,False
147,retail 185,retail,4,"harganya sangat buruk, dimohon untuk harganya ...",2023-06-30,True
148,retail 701,retail,5,Saya mengalami pengalaman sangat baik secara k...,2023-08-03,False
149,retail 274,retail,4,harga sangat baik.,2023-08-14,False

In [8]:
df_review['sentiment'] = df_review['sentiment'].replace([True, False],['negative','positive'])

In [9]:
df_review

,merchant_name,category,rating,review,date,sentiment
0,grocery 89,grocery,3,"makanan dan minumannya sangat baik, dimohon un...",2023-08-22,positive
1,grocery 356,grocery,3,pelayanan baik.,2023-02-02,positive
2,grocery 397,grocery,5,Saya mengalami pengalaman sangat baik secara k...,2023-01-03,positive
3,grocery 455,grocery,2,"pelayanannya buruk, dimohon untuk pelayanannya...",2023-02-28,negative
4,grocery 944,grocery,5,pelayanan baik.,2023-12-31,positive
...,...,...,...,...,...,...
145,retail 144,retail,5,"harganya buruk, dimohon untuk harganya ditingk...",2023-03-13,negative
146,retail 325,retail,2,"suasananya baik, dimohon untuk suasananya diti...",2023-07-26,positive
147,retail 185,retail,4,"harganya sangat buruk, dimohon untuk harganya ...",2023-06-30,negative
148,retail 701,retail,5,Saya mengalami pengalaman sangat baik secara k...,2023-08-03,positive
149,retail 274,retail,4,harga sangat baik.,2023-08-14,positive

In [51]:
rat = []
for i,j in zip(df_review['sentiment'], df_review['rating']):
    if i == 'negative':
        rat.append(random.randint(1, 3))
    else:
        rat.append(random.randint(4, 5))

rat

[5,
 5,
 5,
 3,
 4,
 1,
 1,
 2,
 1,
 3,
 2,
 3,
 5,
 4,
 2,
 4,
 1,
 3,
 1,
 2,
 5,
 1,
 3,
 5,
 5,
 2,
 5,
 5,
 3,
 1,
 2,
 5,
 4,
 4,
 3,
 4,
 5,
 4,
 4,
 3,
 4,
 1,
 4,
 2,
 2,
 4,
 2,
 1,
 2,
 1,
 2,
 4,
 2,
 4,
 5,
 3,
 3,
 3,
 1,
 5,
 4,
 3,
 4,
 5,
 2,
 4,
 4,
 5,
 5,
 4,
 3,
 5,
 5,
 4,
 2,
 1,
 5,
 4,
 1,
 5,
 3,
 4,
 2,
 5,
 2,
 2,
 2,
 3,
 3,
 4,
 1,
 2,
 3,
 4,
 4,
 4,
 2,
 2,
 2,
 5,
 1,
 5,
 1,
 5,
 1,
 2,
 5,
 3,
 5,
 3,
 4,
 1,
 4,
 2,
 5,
 5,
 1,
 5,
 4,
 3,
 4,
 4,
 5,
 5,
 5,
 5,
 1,
 4,
 3,
 3,
 5,
 1,
 5,
 3,
 4,
 4,
 4,
 5,
 2,
 5,
 5,
 1,
 4,
 5,
 3,
 2,
 5,
 1,
 5,
 5]

In [52]:
df_review['rating'] = rat
df_review

,merchant_name,category,rating,review,date,sentiment
0,grocery 89,grocery,5,"makanan dan minumannya sangat baik, dimohon un...",2023-08-22,positive
1,grocery 356,grocery,5,pelayanan baik.,2023-02-02,positive
2,grocery 397,grocery,5,Saya mengalami pengalaman sangat baik secara k...,2023-01-03,positive
3,grocery 455,grocery,3,"pelayanannya buruk, dimohon untuk pelayanannya...",2023-02-28,negative
4,grocery 944,grocery,4,pelayanan baik.,2023-12-31,positive
...,...,...,...,...,...,...
145,retail 144,retail,2,"harganya buruk, dimohon untuk harganya ditingk...",2023-03-13,negative
146,retail 325,retail,5,"suasananya baik, dimohon untuk suasananya diti...",2023-07-26,positive
147,retail 185,retail,1,"harganya sangat buruk, dimohon untuk harganya ...",2023-06-30,negative
148,retail 701,retail,5,Saya mengalami pengalaman sangat baik secara k...,2023-08-03,positive
149,retail 274,retail,5,harga sangat baik.,2023-08-14,positive

In [149]:
df_merchant = pd.read_csv('df_merchant.csv')
df_merchant

,name_merchant,merchant_id,merchant_group,rating,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,reviews
0,Indomaret,0,grocery,4.3,1.3,0.8,1.2,0.8,1.8,0.3,18
1,Alfamart,1,grocery,4.8,1.3,1.0,1.5,0.6,1.3,0.8,16
2,Idolmart,2,grocery,4.4,1.2,1.5,1.4,0.3,1.4,0.2,11
3,Superindo,3,grocery,4.2,1.4,0.9,1.2,0.8,1.2,0.4,12
4,Mixue,4,fnb,4.4,0.9,0.5,1.2,0.4,1.1,0.6,17
5,Haus,5,fnb,4.5,0.6,0.7,1.8,0.8,1.9,0.9,10
6,Mie Gacoan,6,fnb,4.5,1.2,1.6,0.7,0.3,0.8,0.6,15
7,Sederhana,7,fnb,4.8,0.3,1.6,1.8,0.9,1.1,0.2,19
8,Fore Coffee,8,fnb,4.9,0.5,1.1,1.3,0.6,1.3,0.4,18
9,Kopi Kenangan,9,fnb,4.7,1.1,0.8,1.6,0.6,1.2,0.5,15
10,Ceria,10,laundry,4.2,0.5,1.1,1.4,0.9,0.9,1.1,12
11,Si Bersih,11,laundry,4.4,1.0,0.9,0.8,0.5,1.9,0.2,12
12,Miniso,12,retail,4.6,0.8,1.5,1.7,0.6,1.7,0.9,11
13,Nice So,13,retail,4.3,1.3,1.2,1.3,0.7,1.8,0.9,11
14,Intermedia,14,retail,4.8,0.6,1.1,0.8,0.6,1.8,1.1,14

In [150]:
df_merchant['review'] = reviews
df_merchant

,name_merchant,merchant_id,merchant_group,rating,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,reviews,review
0,Indomaret,0,grocery,4.3,1.3,0.8,1.2,0.8,1.8,0.3,18,4
1,Alfamart,1,grocery,4.8,1.3,1.0,1.5,0.6,1.3,0.8,16,3
2,Idolmart,2,grocery,4.4,1.2,1.5,1.4,0.3,1.4,0.2,11,5
3,Superindo,3,grocery,4.2,1.4,0.9,1.2,0.8,1.2,0.4,12,5
4,Mixue,4,fnb,4.4,0.9,0.5,1.2,0.4,1.1,0.6,17,10
5,Haus,5,fnb,4.5,0.6,0.7,1.8,0.8,1.9,0.9,10,3
6,Mie Gacoan,6,fnb,4.5,1.2,1.6,0.7,0.3,0.8,0.6,15,6
7,Sederhana,7,fnb,4.8,0.3,1.6,1.8,0.9,1.1,0.2,19,9
8,Fore Coffee,8,fnb,4.9,0.5,1.1,1.3,0.6,1.3,0.4,18,8
9,Kopi Kenangan,9,fnb,4.7,1.1,0.8,1.6,0.6,1.2,0.5,15,2
10,Ceria,10,laundry,4.2,0.5,1.1,1.4,0.9,0.9,1.1,12,3
11,Si Bersih,11,laundry,4.4,1.0,0.9,0.8,0.5,1.9,0.2,12,3
12,Miniso,12,retail,4.6,0.8,1.5,1.7,0.6,1.7,0.9,11,10
13,Nice So,13,retail,4.3,1.3,1.2,1.3,0.7,1.8,0.9,11,9
14,Intermedia,14,retail,4.8,0.6,1.1,0.8,0.6,1.8,1.1,14,6

In [158]:
review_merchant = []

for i,j in zip(df_merchant['review'], df_merchant['merchant_group']):
    for k in range(i):
        review_merchant.append(random.choice(df_review[['rating','review','date','sentiment']].values.tolist()))
        '''
        if j == 'grocery':
            review_merchant.append(random.choice(df_grocery['review'].values.tolist()))
        if j == 'fnb':
            review_merchant.append(random.choices(df_fnb['review'].values.tolist()))
        if j == 'laundry':
            review_merchant.append(random.choice(df_laundry['review'].values.tolist()))
        if j == 'retail':
            review_merchant.append(random.choice(df_retail['review'].values.tolist()))
       '''

In [137]:
df_merchant

    name_merchant merchant_id    group
0       Indomaret          00  grocery
1        Alfamart          01  grocery
2        Idolmart          02  grocery
3       Superindo          03  grocery
4           Mixue          04      fnb
5            Haus          05      fnb
6      Mie Gacoan          06      fnb
7       Sederhana          07      fnb
8     Fore Coffee          08      fnb
9   Kopi Kenangan          09      fnb
10          Ceria          10  laundry
11      Si Bersih          11  laundry
12         Miniso          12   retail
13        Nice So          13   retail
14     Intermedia          14   retail

In [159]:
len(review_merchant)

86

In [83]:
merchant_review = []
tmp =  df_merchant[['name_merchant','merchant_id']].values.tolist()

for i in range(len(review_merchant)):
   merchant_review.append(random.choice(tmp))

merchant_review

[['Superindo', '03'],
 ['Superindo', '03'],
 ['Nice So', '13'],
 ['Miniso', '12'],
 ['Intermedia', '14'],
 ['Haus', '05'],
 ['Ceria', '10'],
 ['Alfamart', '01'],
 ['Miniso', '12'],
 ['Kopi Kenangan', '09'],
 ['Ceria', '10'],
 ['Ceria', '10'],
 ['Haus', '05'],
 ['Kopi Kenangan', '09'],
 ['Superindo', '03'],
 ['Mie Gacoan', '06'],
 ['Intermedia', '14'],
 ['Superindo', '03'],
 ['Superindo', '03'],
 ['Nice So', '13'],
 ['Superindo', '03'],
 ['Fore Coffee', '08'],
 ['Idolmart', '02'],
 ['Kopi Kenangan', '09'],
 ['Kopi Kenangan', '09'],
 ['Fore Coffee', '08'],
 ['Mie Gacoan', '06'],
 ['Si Bersih', '11'],
 ['Kopi Kenangan', '09'],
 ['Kopi Kenangan', '09'],
 ['Alfamart', '01'],
 ['Intermedia', '14'],
 ['Ceria', '10'],
 ['Ceria', '10'],
 ['Kopi Kenangan', '09'],
 ['Idolmart', '02'],
 ['Superindo', '03'],
 ['Superindo', '03'],
 ['Sederhana', '07'],
 ['Si Bersih', '11'],
 ['Mie Gacoan', '06'],
 ['Intermedia', '14'],
 ['Superindo', '03'],
 ['Fore Coffee', '08'],
 ['Fore Coffee', '08'],
 ['Superindo', '03'],
 ['Idolmart', '02'],
 ['Kopi Kenangan', '09'],
 ['Kopi Kenangan', '09'],
 ['Nice So', '13'],
 ['Alfamart', '01'],
 ['Superindo', '03'],
 ['Sederhana', '07'],
 ['Superindo', '03'],
 ['Mie Gacoan', '06'],
 ['Haus', '05'],
 ['Ceria', '10'],
 ['Fore Coffee', '08'],
 ['Haus', '05'],
 ['Mixue', '04'],
 ['Miniso', '12'],
 ['Mie Gacoan', '06'],
 ['Miniso', '12'],
 ['Miniso', '12'],
 ['Indomaret', '00'],
 ['Si Bersih', '11'],
 ['Kopi Kenangan', '09'],
 ['Mie Gacoan', '06'],
 ['Idolmart', '02'],
 ['Fore Coffee', '08'],
 ['Alfamart', '01'],
 ['Fore Coffee', '08'],
 ['Mixue', '04'],
 ['Alfamart', '01'],
 ['Intermedia', '14'],
 ['Intermedia', '14'],
 ['Superindo', '03'],
 ['Superindo', '03'],
 ['Fore Coffee', '08'],
 ['Idolmart', '02'],
 ['Mie Gacoan', '06'],
 ['Mixue', '04'],
 ['Fore Coffee', '08'],
 ['Kopi Kenangan', '09'],
 ['Si Bersih', '11'],
 ['Nice So', '13']]

In [111]:
res_id = pd.read_csv('resident_id.csv')
non_res_id = pd.read_csv('non_resident_id.csv')

In [112]:
contrib_res = res_id[['res_id','name']].values.tolist()
contrib_non_res = non_res_id[['res_id','name']].values.tolist()

In [113]:
contrib_non_res

[[2024000000335390, 'jumali'],
 [2024000000772349, 'irma indriyani'],
 [2024000000104763, 'suratno'],
 [2024000000277479, 'nuramsah'],
 [2024000000231713, 'diana nur fhaisah'],
 [2024000000186891, 'alisa devi saputri'],
 [2024000000279430, 'fauzan adi saputra'],
 [2024000000128683, 'mariyauddin'],
 [2024000000879619, 'swarti'],
 [2024000000109060, 'reza indra saputra'],
 [2024000000614085, 'dimas dwi fadilah'],
 [2024000000141942, 'faiz ahza praditya'],
 [2024000000167763, 'sudin'],
 [2024000000226614, 'miswen'],
 [2024000000294414, "tukijo al rifa' i"],
 [2024000000325947, 'winarti'],
 [2024000000173592, 'irvan maulana'],
 [2024000000812538, "alfin akbar rifa'i"],
 [2024000000770918, 'samidi'],
 [2024000000209278, 'paijem'],
 [2024000000884925, 'salim'],
 [2024000000220545, 'tukini'],
 [2024000000241742, 'slamet'],
 [2024000000160785, 'bini suharyati'],
 [2024000000107685, 'fendi selistiawan'],
 [2024000000378938, 'kelvin naszril tri efendi'],
 [2024000000293939, 'sugianto'],
 [2024000000147805, 'novi hartini'],
 [2024000000201678, 'aisyah giovani'],
 [2024000000280518, 'arif nova baihaqi'],
 [2024000000194674, 'sutiono'],
 [2024000000621367, 'listiani'],
 [2024000000293900, 'm. ikhwan amsyahputra'],
 [2024000000259789, 'anindita keisha azzahra'],
 [2024000000128207, 'joni kartinus'],
 [2024000000322434, 'heri yeni'],
 [2024000000786666, 'febri dianisya'],
 [2024000000293010, 'rahmat tri apriliando'],
 [2024000000223348, 'sumarni'],
 [2024000000286334, 'muhammad aprila'],
 [2024000000246800, 'warhan'],
 [2024000000191286, "halima tussa'dia"],
 [2024000000109752, 'syavira hanzuneira'],
 [2024000000275525, 'irwan efendi'],
 [2024000000313688, 'sugiarto'],
 [2024000000248839, 'lasmini'],
 [2024000000325500, 'sri lestari'],
 [2024000000289560, 'mukhlis sariadin'],
 [2024000000222844, 'sukadi'],
 [2024000000140086, 'bintiah'],
 [2024000000261499, 'rudi febrianto'],
 [2024000000307737, 'sugeng pribadi'],
 [2024000000334906, 'sutiman'],
 [2024000000146928, 'ngatini'],
 [2024000000824614, 'ahmad nizam alfarizi'],
 [2024000000281053, 'syahrul'],
 [2024000000222628, 'ngadinem'],
 [2024000000298593, 'elly kumala sari'],
 [2024000000848190, 'nanda ayu nur halizzah'],
 [2024000000719752, 'muksin'],
 [2024000000457765, 'gino'],
 [2024000000936163, 'nurhayati'],
 [2024000000641330, 'cici ramadhayanti'],
 [2024000000266776, 'afni dwi lestari'],
 [2024000000101919, 'trisno'],
 [2024000000114037, 'mahdalena'],
 [2024000000149750, 'luthfi abdillah'],
 [2024000000293409, 'adiba zahara'],
 [2024000000372269, 'sucipto'],
 [2024000000280462, 'asih'],
 [2024000000316955, 'muhammad albana'],
 [2024000000164714, 'salwa unaisah'],
 [2024000000576220, 'harun fadhillah'],
 [2024000000187195, 'salma nusaybah'],
 [2024000000320786, 'shoffan al fath'],
 [2024000000147618, 'hanif fatchan mujib'],
 [2024000000708196, 'sutrisno'],
 [2024000000222818, 'purwati'],
 [2024000000137874, 'adif zaldiansyah'],
 [2024000000129718, 'nadira aulia shaki'],
 [2024000000382639, 'ujang umin ruhdiansyah'],
 [2024000000327905, 'dede rumyati'],
 [2024000000113381, 'eka rosmawati'],
 [2024000000243696, 'lely lutfiah sungkar'],
 [2024000000650052, 'ivan gustomi'],
 [2024000000174589, 'alfazola'],
 [2024000000950185, 'azza nabilla tasya'],
 [2024000000175127, 'hafsa nur hafizza'],
 [2024000000287696, 'alhadmin'],
 [2024000000955122, 'dahlia'],
 [2024000000371526, 'm. khuza alhasby'],
 [2024000000157919, 'ismail'],
 [2024000000414542, 'susiati'],
 [2024000000209075, 'qoridhotul mutakin'],
 [2024000000861643, 'khafidhotus sany'],
 [2024000000331699, 'syafia zahra aprelia'],
 [2024000000221530, 'slamet'],
 [2024000000908632, 'eka restiawati'],
 [2024000000333396, 'm. aditya hatta'],
 [2024000000648305, 'sumarno'],
 [2024000000388328, 'aris anggraini'],
 [2024000000148776, 'dian nur artika sari'],
 [2024000000216255, 'lisa tri yunita'],
 [2024000000431063, 'kasmari'],
 [2024000000285662, 'munik nurhayati'],
 [2024000000284053, 'aura afifatunnisa'],
 [2024000000211180, 'aulia mutiara cinta'],
 [2024000000318461, 'suliati'],
 [2024000000332297, 'tawirja'],
 [2024000000177173, 'bawiati'],
 [2024000000253036, 'rudianto'],
 [2024000000317411, 'siswanto'],
 [2024000000101494, 'titin fatimah'],
 [2024000000321681, 'nanda lucky firmansyah'],
 [2024000000105012, 'zulvan arfa syazwan'],
 [2024000000128047, 'handri'],
 [2024000000107433, 'maisaroh'],
 [2024000000133081, 'yusi andriyani'],
 [2024000000787095, 'rizki septiadi'],
 [2024000000280205, 'suyadi'],
 [2024000000639736, 'suryani'],
 [2024000000113243, 'tatik dwi ambarwati'],
 [2024000000175552, 'ima listiani'],
 [2024000000318818, 'sujono'],
 [2024000000786982, 'marini'],
 [2024000000155174, 'm. tolib syahbarul'],
 [2024000000249154, 'bela novitasari'],
 [2024000000152844, 'muhammad afdal affandi'],
 [2024000000277813, 'dedi iswandi'],
 [2024000000281225, 'ahmad purwito'],
 [2024000000240110, 'hadmini'],
 [2024000000199140, 'atun puji rahayu'],
 [2024000000318868, 'agus fahrizal'],
 [2024000000245292, 'tri winarti'],
 [2024000000273656, 'murdiansyah'],
 [2024000000290291, 'agustina muntikawati'],
 [2024000000331865, 'ali hamzah'],
 [2024000000278043, 'dewi'],
 [2024000000188126, 'evi alisma'],
 [2024000000172101, 'egi aulia pirdaus'],
 [2024000000152531, 'seli hapti anggara'],
 [2024000000770876, 'rasidin'],
 [2024000000147496, 'rebo'],
 [2024000000140223, 'kasih'],
 [2024000000500571, 'ilham setiaji'],
 [2024000000583312, 'muhamad aziz'],
 [2024000000368007, 'surya kusuma'],
 [2024000000307679, 'tumi setiawati'],
 [2024000000295111, 'irza syahputra'],
 [2024000000240199, 'asim'],
 [2024000000285314, 'srini'],
 [2024000000115037, 'yeni purwaningsih'],
 [2024000000308531, 'vebri kurniawan'],
 [2024000000322128, 'ahmad diinulkha'],
 [2024000000198889, 'didik siswanto'],
 [2024000000355761, 'sigit sugiyanto'],
 [2024000000877519, 'ike handayani'],
 [2024000000173073, 'ratifa naila aisha'],
 [2024000000311480, 'mukarom'],
 [2024000000879282, 'fauziyah'],
 [2024000000105578, 'alfiyatu zahroh'],
 [2024000000948704, 'miftakhul qolbi'],
 [2024000000297710, 'abdullah afif azzuhri'],
 [2024000000218080, 'afifah azzahroh'],
 [2024000000285934, 'kevin kenzi al firmansyah'],
 [2024000000192716, 'muhaimin'],
 [2024000000763424, 'dwi rukiyah'],
 [2024000000127103, 'azuwa fatkur alkholif'],
 [2024000000336819, 'binti'],
 [2024000000183048, 'andi baskoro'],
 [2024000000146104, 'muhammad habibullah'],
 [2024000000253429, 'ira afrianti'],
 [2024000000663870, 'misbahatussudury'],
 [2024000000812535, 'manto gumes'],
 [2024000000340150, 'tumirah'],
 [2024000000504760, 'ali mustopo'],
 [2024000000670168, 'siti maemunah'],
 [2024000000226973, 'aisah'],
 [2024000000380731, 'sapin'],
 [2024000000280673, 'nur khalim'],
 [2024000000123149, 'isni'],
 [2024000000292916, 'suprihatin'],
 [2024000000197324, 'peni untari'],
 [2024000000140700, 'tomi ramdani'],
 [2024000000341213, 'riki supendi'],
 [2024000000270495, 'sahid'],
 [2024000000607031, 'siti juwariyah'],
 [2024000000603603, 'miftachul huda'],
 [2024000000134371, 'nur jannah'],
 [2024000000187674, 'm. nasirudin'],
 [2024000000500384, 'choiriyah'],
 [2024000000171494, 'sagiman'],
 [2024000000493158, 'sutinah'],
 [2024000000223849, 'elisnawati'],
 [2024000000687788, 'winda aprilia'],
 [2024000000581165, 'sudadi'],
 [2024000000306283, 'supriyo susanto'],
 [2024000000306306, 'sri mulyati'],
 [2024000000321687, 'dinda dwi merliana'],
 [2024000000714069, 'ardy ramadhani'],
 [2024000000716361, 'wagino'],
 [2024000000235434, 'sri rejeki'],
 [2024000000566032, 'diky handriansyah'],
 [2024000000177997, 'giono'],
 [2024000000444692, 'ismiyati'],
 [2024000000915137, 'bayu istanto'],
 [2024000000340045, 'indah bunga hati'],
 [2024000000834687, 'waelan'],
 [2024000000686034, 'rastina'],
 [2024000000875114, 'hari kurniawan'],
 [2024000000158999, 'umi maslikhah'],
 [2024000000790197, 'lilik supriyanto'],
 [2024000000578022, 'sunarti'],
 [2024000000109078, 'revianita inka hadi'],
 [2024000000231405, 'agung susilo'],
 [2024000000168948, 'ira susanti'],
 [2024000000138627, 'silvia ayu nadira rahmawati'],
 [2024000000202151, 'ngadiman'],
 [2024000000156635, 'sriyatun'],
 [2024000000295461, 'een romlah'],
 [2024000000120713, 'abdul rahman'],
 [2024000000121146, 'm. zaenuri'],
 [2024000000290534, 'tri murtini'],
 [2024000000273484, 'leny faridhotul mutmaini'],
 [2024000000105889, 'azizah hanifatur rahma'],
 [2024000000185136, 'ahmad hasinul fikqih'],
 [2024000000331167, 'annida hasnaul atika'],
 [2024000000212280, 'jalal'],
 [2024000000100579, 'supri ani'],
 [2024000000195219, 'muhammad rikza rohmana'],
 [2024000000154734, "aila annafi'an zaini"],
 [2024000000939806, 'novi ayu sharafina'],
 [2024000000128552, 'nova ayu sharafika'],
 [2024000000285118, 'samsuri'],
 [2024000000960512, 'ani'],
 [2024000000212127, 'santi susanti'],
 [2024000000137007, 'nyaman'],
 [2024000000790281, 'rusmiyati'],
 [2024000000261381, 'taufik usman'],
 [2024000000539811, 'suci melia putri'],
 [2024000000185188, 'tumidjo'],
 [2024000000310297, 'sumarni'],
 [2024000000250303, 'aprilia rahmawati'],
 [2024000000214088, 'febi ayu lestari'],
 [2024000000659169, 'gunawan'],
 [2024000000144842, 'siti mudrikah'],
 [2024000000166045, 'indarti'],
 [2024000000324720, 'wahab maulana ramadhan'],
 [2024000000333142, 'haikal aziz kurniawan'],
 [2024000000338191, 'ahmad tona'],
 [2024000000115973, 'sutomo'],
 [2024000000336458, 'mariyem'],
 [2024000000270179, 'setio purwanto'],
 [2024000000123962, 'tri tugas'],
 [2024000000276568, 'tumiati'],
 [2024000000217575, 'hanifatun nasyroh'],
 [2024000000123645, 'sutarman'],
 [2024000000375716, 'ponirah'],
 [2024000000103898, 'slamet harianto'],
 [2024000000199239, 'sumarno'],
 [2024000000306418, 'sunarti'],
 [2024000000792641, 'lukman wibowo. s'],
 [2024000000116404, 'iman wahyudi'],
 [2024000000302967, 'hariyono'],
 [2024000000254294, 'mami hernawati'],
 [2024000000226965, 'm. irfani'],
 [2024000000263146, 'sagiyati'],
 [2024000000144216, 'andi sofyan'],
 [2024000000740450, 'fita eviyana'],
 [2024000000265745, 'ahmad priyanto'],
 [2024000000136564, 'hadi wagiman'],
 [2024000000274900, 'suparmi'],
 [2024000000297682, 'sigit widianto'],
 [2024000000440214, 'singgih adi putra'],
 [2024000000276045, 'mitro panut'],
 [2024000000247371, 'rubiyati'],
 [2024000000250925, 'supri yanto'],
 [2024000000100301, 'ani paridah'],
 [2024000000317203, 'nina ayu lestari'],
 [2024000000661189, 'tika ramawati'],
 [2024000000143278, 'paryono'],
 [2024000000737030, 'sukatmi'],
 [2024000000243224, 'eva apriyani'],
 [2024000000106687, 'asiva nur aini'],
 [2024000000285656, 'm. amin'],
 [2024000000529296, 'salpiah'],
 [2024000000336604, 'mustaqpirin'],
 [2024000000245561, 'khairudin'],
 [2024000000266830, 'khairul ilham'],
 [2024000000152869, 'yuli yanti'],
 [2024000000203262, 'shela nur diana sari'],
 [2024000000188161, 'lhailatul istamaroh'],
 [2024000000893769, 'sudirman'],
 [2024000000320478, 'atik winarni'],
 [2024000000844783, 'sofyan ali syahbana'],
 [2024000000317331, 'nur aida dwi ramadhani'],
 [2024000000101381, 'arsy muhammad al habsy'],
 [2024000000556879, 'm. zaenuri'],
 [2024000000148000, 'tri murtini'],
 [2024000000163059, 'leny faridhotul mutmaini'],
 [2024000000643158, 'azizah hanifatur rahma'],
 [2024000000114626, 'ahmad hasinul fikqih'],
 [2024000000230907, 'annida hasnaul atika'],
 [2024000000224725, 'jalal'],
 [2024000000365428, 'supri ani'],
 [2024000000703325, 'muhammad rikza rohmana'],
 [2024000000686792, "aila annafi'an zaini"],
 [2024000000285646, 'novi ayu sharafina'],
 [2024000000274971, 'nova ayu sharafika'],
 [2024000000114983, 'samsuri'],
 [2024000000250553, 'ani'],
 [2024000000892291, 'santi susanti'],
 [2024000000140970, 'nyaman'],
 [2024000000249387, 'rusmiyati'],
 [2024000000493247, 'taufik usman'],
 [2024000000218707, 'suci melia putri'],
 [2024000000275964, 'tumidjo'],
 [2024000000324382, 'sumarni'],
 [2024000000336757, 'aprilia rahmawati'],
 [2024000000460112, 'febi ayu lestari'],
 [2024000000327855, 'gunawan'],
 [2024000000300775, 'siti mudrikah'],
 [2024000000251304, 'indarti'],
 [2024000000252276, 'wahab maulana ramadhan'],
 [2024000000890499, 'haikal aziz kurniawan'],
 [2024000000235365, 'ahmad tona'],
 [2024000000137737, 'sutomo'],
 [2024000000529004, 'mariyem'],
 [2024000000686909, 'setio purwanto'],
 [2024000000155719, 'tri tugas'],
 [2024000000449166, 'tumiati'],
 [2024000000226515, 'hanifatun nasyroh'],
 [2024000000294774, 'sutarman'],
 [2024000000267687, 'ponirah'],
 [2024000000211887, 'slamet harianto'],
 [2024000000161783, 'sumarno'],
 [2024000000285476, 'sunarti'],
 [2024000000292951, 'lukman wibowo. s'],
 [2024000000281731, 'iman wahyudi'],
 [2024000000315486, 'hariyono'],
 [2024000000157171, 'mami hernawati'],
 [2024000000254102, 'm. irfani'],
 [2024000000411643, 'sagiyati'],
 [2024000000145788, 'andi sofyan'],
 [2024000000143447, 'fita eviyana'],
 [2024000000133474, 'ahmad priyanto'],
 [2024000000278128, 'hadi wagiman'],
 [2024000000181770, 'suparmi'],
 [2024000000918525, 'sigit widianto'],
 [2024000000541028, 'singgih adi putra'],
 [2024000000165286, 'mitro panut'],
 [2024000000168448, 'rubiyati'],
 [2024000000280999, 'supri yanto'],
 [2024000000278632, 'ani paridah'],
 [2024000000483883, 'nina ayu lestari'],
 [2024000000254451, 'tika ramawati'],
 [2024000000224483, 'paryono'],
 [2024000000233081, 'sukatmi'],
 [2024000000110276, 'eva apriyani'],
 [2024000000554072, 'asiva nur aini'],
 [2024000000306754, 'm. amin'],
 [2024000000335264, 'salpiah'],
 [2024000000325528, 'mustaqpirin'],
 [2024000000324963, 'khairudin'],
 [2024000000285416, 'khairul ilham'],
 [2024000000265865, 'yuli yanti'],
 [2024000000630903, 'shela nur diana sari'],
 [2024000000198518, 'lhailatul istamaroh'],
 [2024000000280513, 'sudirman'],
 [2024000000214012, 'atik winarni'],
 [2024000000934522, 'sofyan ali syahbana'],
 [2024000000271363, 'nur aida dwi ramadhani'],
 [2024000000675559, 'arsy muhammad al habsy'],
 [2024000000137369, 'pangidoan'],
 [2024000000711733, 'suwarni'],
 [2024000000309777, 'nurliani'],
 [2024000000189036, 'safiq heryanto'],
 [2024000000302117, 'rahmat'],
 [2024000000270368, 'yunersen'],
 [2024000000869088, 'ahmad muttakin'],
 [2024000000132775, 'badriah'],
 [2024000000159752, 'harisun'],
 [2024000000105075, 'hali maskur'],
 [2024000000241383, 'yusuf'],
 [2024000000232039, 'bukhori'],
 [2024000000536092, "si'in"],
 [2024000000263331, 'muhammad susanto'],
 [2024000000888447, 'anwar asnawi'],
 [2024000000300074, 'ali imron'],
 [2024000000967562, 'slamet nidun'],
 [2024000000132078, 'jaemah'],
 [2024000000477217, 'eka junita'],
 [2024000000993166, 'duwi a. fikri'],
 [2024000000246801, 'muhammad akbar rizan'],
 [2024000000326346, 'martono'],
 [2024000000230887, 'sadiah'],
 [2024000000183660, 'pitriani'],
 [2024000000281239, 'amat solekan'],
 [2024000000288102, 'iswadi'],
 [2024000000363071, 'paino'],
 [2024000000338784, 'hani atun'],
 [2024000000578537, 'riska sundari'],
 [2024000000136105, 'sabrina fatmawati'],
 [2024000000252595, 'abdul jalil'],
 [2024000000367561, 'sulastri'],
 [2024000000304935, 'abi gail'],
 [2024000000319278, 'raudati zuhriyah'],
 [2024000000306324, 'nirmala syafira'],
 [2024000000132892, 'turhadi'],
 [2024000000271410, 'konah'],
 [2024000000801121, 'hani sali sati'],
 [2024000000163525, 'alwan supangat'],
 [2024000000213148, 'sukirman'],
 [2024000000233739, 'riyanti'],
 [2024000000154077, 'rafika oktavianti'],
 [2024000000123162, 'dwi kurniasih'],
 [2024000000811558, 'm. tri ananta anugrah'],
 [2024000000149224, 'rajiman'],
 [2024000000293071, 'leginem'],
 [2024000000221923, 'suparjo'],
 [2024000000255168, 'suliyatin'],
 [2024000000157085, 'catur suroso'],
 [2024000000116385, 'rafika dewi sari'],
 [2024000000103605, 'dian nur assyfa'],
 [2024000000272351, 'abdul hamid'],
 [2024000000112969, 'siti aisah'],
 [2024000000270652, 'sariman'],
 [2024000000167698, 'tasminah'],
 [2024000000656569, 'nafiudin'],
 [2024000000228448, 'siti komariyah'],
 [2024000000236600, 'budiman syahputra'],
 [2024000000111050, 'sri nawati'],
 [2024000000229259, 'rakha fico efendi'],
 [2024000000143083, 'muji syukur'],
 [2024000000118279, 'ismini'],
 [2024000000123963, 'eka afrilia pujianti'],
 [2024000000477406, 'fikri dwi susanto'],
 [2024000000323008, 'siswanto'],
 [2024000000554343, "mu'alifah"],
 [2024000000310296, 'yuda aldiansyah'],
 [2024000000266389, 'sugianto'],
 [2024000000105220, 'deni primawan'],
 [2024000000100456, 'muhammad yusuf'],
 [2024000000998522, 'niwan'],
 [2024000000232065, 'siti masithoh'],
 [2024000000191688, 'mustofa'],
 [2024000000339602, 'somad susanto'],
 [2024000000569466, 'immatul azizah'],
 [2024000000609420, 'lamsyah purba'],
 [2024000000187840, 'roliana silalahi'],
 [2024000000339933, 'desi ratnasari'],
 [2024000000915867, 'abdul hanafi purba'],
 [2024000000262125, 'ibnu haris purba'],
 [2024000000198144, 'arif suesanto purba'],
 [2024000000170499, 'ade liyanti'],
 [2024000000309946, 'jubadi'],
 [2024000000269039, 'citra ayu wulandari'],
 [2024000000158827, 'surya dwi syahputra'],
 [2024000000325601, 'jumali'],
 [2024000000928299, 'adi widjoyo'],
 [2024000000255929, 'sudarseh'],
 [2024000000128094, 'siti juwariyah'],
 [2024000000584317, 'munirul ikhwan'],
 [2024000000339615, 'ahmad farid'],
 [2024000000335238, 'apriyani'],
 [2024000000140631, 'abdi ahmad permadani'],
 [2024000000172722, 'dinda syifa'],
 [2024000000303436, 'sutrisno'],
 [2024000000126826, 'sundari'],
 [2024000000286889, 'khoiru nisa aprilia'],
 [2024000000296322, 'supriyadi'],
 [2024000000208335, 'sri khayati'],
 [2024000000182947, 'al fathir rakha abyan'],
 [2024000000137373, 'herman'],
 [2024000000336752, 'tria ningsih'],
 [2024000000325633, 'akmal maulana teguh firmansyah'],
 [2024000000116770, 'galih setiawan dwi aldi hernanda'],
 [2024000000100760, 'bonem'],
 [2024000000127877, 'ahmad sujono'],
 [2024000000142040, 'siyami'],
 [2024000000101103, 'dion aldi setiawan'],
 [2024000000316473, 'teguh ramadhan'],
 [2024000000103995, 'nurokhmad ikhwandi'],
 [2024000000154249, 'siti maryatun'],
 [2024000000806914, 'muhammad fajri maulana'],
 [2024000000281204, 'suyatno'],
 [2024000000177734, 'sriana'],
 [2024000000129968, 'hasan sidik'],
 [2024000000110825, 'maulana mujahid'],
 [2024000000205500, 'fadhilah aini'],
 [2024000000211096, 'eria zilan putri'],
 [2024000000152594, 'kasianto'],
 [2024000000297616, 'sutrisno'],
 [2024000000104807, 'roni setyawan'],
 [2024000000171820, 'slamet'],
 [2024000000140030, 'sariani'],
 [2024000000958691, 'fahri al farisi'],
 [2024000000952128, 'imania syafa azzahrah'],
 [2024000000248186, 'sukarlan'],
 [2024000000281428, 'kokom komariah']]

In [160]:
contrib = contrib_res + contrib_non_res
contrib

[['202203A1401484221', 'ridha ulva'],
 ['202203B1902780908', 'rizqi wahyuningsih'],
 ['202303C1201119547', 'ruwadi saputra'],
 ['202403D302160049', 'sugeng hermawan'],
 ['202203C101563316', 'suliatun'],
 ['202203G1201179026', 'tomi ismeidianto'],
 ['202303H1201633496', 'usthalay putra'],
 ['202203G1501690987', 'winggo aga septian'],
 ['202403D2501171004', 'yunaldi rizki putra'],
 ['202303G1101892420', 'arif fasetyo'],
 ['202403B2001196382', 'arie rahman satria'],
 ['202303D802517421', 'arinda oktaviana'],
 ['202303H2501280011', 'asri jakawendra'],
 ['202303H101141935', 'astri stiawaty'],
 ['202203F101467154', 'aszani'],
 ['202203A1601285586', 'boby rahman'],
 ['202203D1801112245', 'dewi cahyati'],
 ['202303C401133155', 'dimas aditya perdana'],
 ['202303C802103588', 'dinda afani'],
 ['202403B1101794392', 'doni sanjaya'],
 ['202403D2701308369', 'fitri yanti'],
 ['202203A501112667', 'hendri eka saputra'],
 ['202403B1701600697', 'irwan ahmad gafur'],
 ['202203D601240055', 'isa ismail'],
 ['202303A901220966', 'kurniawan rosman a'],
 ['202203F501295992', 'muhammad azmy'],
 ['202203E401265238', 'muhammad ilham'],
 ['202403B401236420', 'muhammad sholihan'],
 ['202403H2101178578', 'novita dewi'],
 ['202403D2401187867', 'novri sabli saputra'],
 ['202303D1201242806', 'pajar bahari'],
 ['202403G1601312097', 'redha fauziah aziz'],
 ['202403D1101263990', 'ridho'],
 ['202403G901267851', 'ridho fajri'],
 ['202203H2302381430', 'ridho rismayanda'],
 ['202203A1001314392', 'ridwan candra'],
 ['202303H301109854', 'rosdina'],
 ['202303G601652294', 'supriadi'],
 ['202203E501134039', 'suriyani'],
 ['202203B1601208333', 'tommy zul hidayat'],
 ['202203D1301227936', 'umi riyani'],
 ['202203D101323962', 'wiwik sumarmi'],
 ['202303H501220892', 'yuni dwi hastuti'],
 ['202203B901547192', 'aulia rahman'],
 ['202203A1201429217', 'agung kurniawan'],
 ['202403A701848730', 'ahmad fauzi paturusi'],
 ['202403H2001296930', 'arie biola gunti masuko'],
 ['202203F901664817', 'ayu andira'],
 ['202403H2201127609', 'ayu dwi septiana arta'],
 ['202203H1502921274', 'azwar anas'],
 ['202203D1401175758', 'azwir irfan nanda'],
 ['202403E901278975', 'budi setiawan'],
 ['202303C1301216791', 'donna febriani'],
 ['202203B501449940', 'dwi widiastuti'],
 ['202403E302102225', 'dwiki apsyarin'],
 ['202203C701165915', 'dwiza indri'],
 ['202303B2101195205', 'frans b jaya zalukhu'],
 ['202403F201111589', 'fuad harisfa'],
 ['202403H1402273790', 'herman efendi'],
 ['202303D1501206345', 'ichsyan rizky adi p'],
 ['202203C1001133824', 'ivo oktavianti'],
 ['202403C1601244346', 'lailatul izzati'],
 ['202403C1402295046', 'muhammad oki'],
 ['202303H601826045', 'muhammad ridho ardonis'],
 ['202403D2201135881', 'muhammad rizqi muttaqin'],
 ['202203D201180421', 'muhammad setyo'],
 ['202203H702309642', 'nur aulia hasanah'],
 ['202403D1601803577', 'nurfatrianti'],
 ['202303A1502209362', 'pikril islami'],
 ['202403A301475415', 'rikal'],
 ['202203A1301148997', 'riyan hidayat'],
 ['202303H1002215830', 'rizki fatama'],
 ['202403G402335781', 'rizkie hafizzah'],
 ['202403A101308923', 'syaiful akbar'],
 ['202403B302280457', "nu' in sofyan"],
 ['202403C1501165303', 'sumirah'],
 ['202203C602480434', 'ade surahman'],
 ['202303B801972722', 'kasnanto'],
 ['202303F401246810', 'sumirah'],
 ['202203H1601108817', 'teguh wahyudi'],
 ['202203D701987639', 'sakiyo'],
 ['202203B101246645', 'dwi kasmini'],
 ['202203B2301133830', 'laily mufarokah'],
 ['202403B1001120987', 'sigit nugroho'],
 ['202203B1302147788', 'linda rusmi wardani'],
 ['202403F1501118123', 'm. charly iman nugroho'],
 ['202203C1701179846', 'untung sugiono'],
 ['202203B201109026', 'sarminah'],
 ['202403A801658283', 'wiwik purwanti'],
 ['202203H202137999', 'saputra'],
 ['202403H401873238', 'sufiyani'],
 ['202303E801272421', 'zenika pradea'],
 ['202303F1302126183', 'adelia agustin'],
 ['202403B1501324342', 'desi aulia rahma'],
 ['202203D501257426', 'muhammad fajar maulana'],
 ['202203D2001107296', 'muliadi'],
 ['202203F601243393', 'nuriyati'],
 ['202203H1802294413', 'andreyan saputra'],
 ['202203H901431797', 'afrianda'],
 ['202203A201604186', 'surya ramadani'],
 ['202403B1201156087', 'suhendri'],
 ['202203H1901209011', 'dewi wulan sari'],
 ['202203B1401152918', 'reza andika ramadhan'],
 ['202303G301213614', 'slamet'],
 ['202403D1901263826', 'erna'],
 ['202203G701183988', 'gilang aditia'],
 ['202403F1001329986', 'suherianto'],
 ['202303D2301123613', 'sugianti'],
 ['202203F1401104557', 'aris pratama putra'],
 ['202403D1001146841', 'adella'],
 ['202203G1002337595', 'widyo sudiro'],
 ['202303E102169870', 'kusniah'],
 ['202203B2401141059', 'riza feri handoko'],
 ['202303D2802241417', 'angga adhy surya'],
 ['202203H801263500', 'nelvin adhy renata'],
 ['202203F1601203366', 'titis brigida silva'],
 ['202303C201338628', 'suroso'],
 ['202203E702306142', 'sukati'],
 ['202303F1101113930', 'depri selamet ariadi'],
 ['202403G1301219716', 'isti nurjanah'],
 ['202403H2402144237', 'ruswantoro'],
 ['202403D1701146338', 'juli anggraeni'],
 ['202303G501210424', 'muhammad prayoga winata'],
 ['202403F701840492', 'heru setyono'],
 ['202203G202891331', 'sri mulyani'],
 ['202203F801262359', 'galih subekti'],
 ['202403F301173185', 'ageng kurniawan'],
 ['202403A401275540', 'auliya shobrina'],
 ['202203A601206031', 'slamet'],
 ['202403A1102678244', 'suparmi'],
 ['202203F1701185213', 'tri agus susilo'],
 ['202403D902457460', 'junaeri'],
 ['202303F1801368209', 'daryono'],
 ['202403B1801149933', 'poniyem'],
 ['202403D401113526', 'fajar setiawan'],
 ['202403B2201114740', 'nabilatul dwi seftiani'],
 ['202303E1001264395', 'jaimin'],
 ['202403E201571358', 'rohatun'],
 ['202403C1101101630', 'dewi safitri'],
 ['202403G101130694', 'dian elok nur cahyati'],
 ['202303E602303076', 'm. amrijen nur rohman'],
 ['202203G801100622', 'rosidin'],
 ['202203D2101228983', 'suwarti'],
 ['202303G1402245116', 'krisdan fauzi'],
 ['202203D2601151103', 'khasanah dwi fauziah'],
 ['202403C901487836', 'ainun isnaini fauziati'],
 ['202403H1701127409', 'm. rais tri wahyudi'],
 ['202203B701157125', 'sri mudrikoh'],
 ['202303F1201241070', 'ihsan baedowi'],
 ['202203H1301295709', 'rahmad erwin wibisono'],
 ['202203B601470767', 'muhamad fiki wahyudi'],
 ['202203C501226794', 'agus salim'],
 ['202303C301125669', 'mardiana'],
 ['202203H1102316053', 'mustika sari'],
 ['202204D1901164765', 'muhammad zamzari'],
 ['202404F901326641', 'air murya'],
 ['202404B401216705', 'sumardi'],
 ['202404H1301215987', 'surni'],
 ['202404H901425975', 'wahid suprayitno'],
 ['202204H1501182617', 'sutramiati'],
 ['202204F801423199', 'susanti lestari'],
 ['202204B1901256452', 'rasman'],
 ['202204D601316282', 'riya ningsih'],
 ['202404G1501462471', 'uji ifandy saputra'],
 ['202404D2801741030', 'hana aida sahila'],
 ['202304D2702852366', 'mufizar ilyas'],
 ['202404C201164310', 'nora'],
 ['202204B801197239', 'ulviana agustina'],
 ['202304C1801847516', 'erina ramadhani'],
 ['202404E401308752', 'sumono'],
 ['202304F301121757', 'khoirul zaki'],
 ['202304A401278605', 'warsini'],
 ['202204E801108719', 'alif al barrak zaki'],
 ['202304F1201296937', 'sulistiyono'],
 ['202204C2001148004', 'jekri wiralis'],
 ['202404B2001268674', 'nirmanto'],
 ['202304C101147790', 'rasmini'],
 ['202204E502117549', 'bejo hutanto'],
 ['202204C901139635', 'desi tri astuti'],
 ['202304D2001277197', 'okta ionika'],
 ['202404C502174563', 'muhyidin'],
 ['202304E701884866', 'meriyanti'],
 ['202404H1901142516', 'erna lestari'],
 ['202204G501308149', 'asef saifulloh'],
 ['202404D2601331110', 'jonianto'],
 ['202304C702113204', 'mujiati'],
 ['202204G1801173353', 'riko hari prasetyo'],
 ['202204C2101131088', 'diva al farizky'],
 ['202204H2001505193', 'parjo'],
 ['202404G101282721', 'rumsiyah'],
 ['202204A601160608', 'dewi sumarni'],
 ['202204G601297486', 'efi sulastri'],
 ['202204D401287097', 'wagimun'],
 ['202304A301887019', 'girah'],
 ['202404G1101322919', 'feni safitri'],
 ['202304H601186699', 'sumarno'],
 ['202404H2201172626', 'nurimah'],
 ['202204F201271209', 'noviana anggraeni'],
 ['202404H1101244647', 'aissyah dwi zhaskia'],
 ['202404H401238752', 'hariri'],
 ['202204B1501333159', 'ida budiani'],
 ['202204B2402683619', 'rizki pratama'],
 ['202404B2201148440', 'yanto'],
 ['202204G1401291206', 'puji lestari'],
 ['202204G202152887', 'dewi wulan ningsih'],
 ['202404H701171834', 'aril aji alania'],
 ['202204C602223288', 'amalia chechy anggia'],
 ['202304A702905622', 'suranto'],
 ['202204H2501185854', 'suprihatin'],
 ['202204A801315338', 'bangkit syuhada'],
 ['202304G901425924', 'tri anindita aurellia'],
 ['202204D701261460', 'kasturi'],
 ['202204B301179861', 'epran'],
 ['202204H1701339447', 'suwarsih'],
 ['202404B101303360', 'dwi astika sari'],
 ['202404H801186252', 'trio hamdani'],
 ['202304H1802121540', 'a. solikhin'],
 ['202304G1601313448', 'sumiati'],
 ['202404C1201315933', 'sugiat bagus hermawan'],
 ['202204A201235672', 'sukma liyana dewi'],
 ['202404E1602247621', 'dzul helmi affan ridho'],
 ['202204B901173219', 'nugroho'],
 ['202404A1301275391', 'kusriyati'],
 ['202404D1001829653', 'vika apriliana n. a'],
 ['202304C401113416', 'bela octavia ramadani'],
 ['202204H2301759657', 'pri santoso'],
 ['202204E1301848777', 'miyanto'],
 ['202304E101756498', 'samiyah'],
 ['202404H301954737', 'wahyu pratama'],
 ['202204A1201201535', 'devina tria ananda'],
 ['202304D101141035', 'masruri'],
 ['202404C1101120516', 'siti romlah'],
 ['202404F1302138965', 'ricky prayoga'],
 ['202204F1001167407', 'shafa mutia nurhaliza'],
 ['202204D2401714192', 'abdul malik'],
 ['202404A901162794', 'kardi'],
 ['202404B1201319750', 'sumini'],
 ['202304A1401230276', 'andika saputra'],
 ['202204H1401266437', 'habib hidayaturrohman'],
 ['202204E1101238248', 'wiwik wulandari'],
 ['202204D1702224691', 'm. souvil anam'],
 ['202404G301688096', 'anin khamidah'],
 ['202404B202322370', 'diram'],
 ['202204H501102478', 'muslimah'],
 ['202204A101183585', 'eko kurniawan'],
 ['202204C1501285096', 'romadon nur hidayat'],
 ['202404F502164267', 'siti masliah'],
 ['202204F1501120952', 'tri adi eko lestanto'],
 ['202204E1502221383', 'eva setia ningrum'],
 ['202204D1801293350', 'suyono'],
 ['202304D501193423', 'nurtriana yuliastuti'],
 ['202304F401153396', 'sazim saputra'],
 ['202404F1601237891', 'rozakiah'],
 ['202304F1701944800', 'alifia yuliani'],
 ['202304E1001625646', 'hamzah maulana'],
 ['202404D1401222944', 'akbar maulana'],
 ['202204G1201140324', 'supriyadi'],
 ['202204A1701305934', 'supiyah'],
 ['202404C1701189048', 'alfajar efendi'],
 ['202404F701387887', 'ahmad saprudin'],
 ['202404C301161984', 'anwar sholeh'],
 ['202204C1601627721', 'umi muslimah'],
 ['202204G1701203205', 'elisa anjani'],
 ['202404B501297795', 'meila nurhidayati'],
 ['202404B1401281974', 'santoso'],
 ['202304A502155370', 'tumi'],
 ['202204H102127990', 'mira mustika'],
 ['202204H1201214717', 'edi suyoto'],
 ['202404B1101150111', 'rikana nurmala desi'],
 ['202204B1001379337', 'zidane dhevan pratama'],
 ['202404B1601128953', 'mariyamah'],
 ['202304C801243624', 'setiawan'],
 ['202204D2301330384', 'sutiono'],
 ['202204D201192978', 'nurhayati'],
 ['202404A1501408083', 'oki aditia saputra'],
 ['202204F101231580', 'hendrio junior'],
 ['202404F1101151351', 'giatno'],
 ['202304D1101972339', 'siti ngaisah'],
 ['202404A1901780993', 'ahmad rasyid'],
 ['202204D1601588854', 'gilang nur bekti'],
 ['202304A1101266245', 'abas suyatno'],
 ['202204C1901257804', 'kholipah'],
 ['202404D2501160865', 'abdul kholik'],
 ['202304B1301147196', 'dede adiyanto'],
 ['202204H2401196089', 'handani nurul hidayah'],
 ['202404A1801142793', 'mustofa'],
 ['202404G1001304833', 'luhur gunawan'],
 ['202204F601335078', 'tri mandrasih'],
 ['202304B2301126887', 'manisem'],
 ['202404D2101228615', 'r. widodo'],
 ['202204H201323800', 'ismanto'],
 ['202204E1201247964', 'tri lestari'],
 ['202304C1001335689', 'kurniawan zam zami'],
 ['202204D301167570', 'raditia saputri'],
 ['202204C1301250375', 'mabruro'],
 ['202304B1702291010', 'mukaromah'],
 ['202304H1001113075', 'vina nailatul izzah'],
 ['202204D1301150619', 'muhammad arwin'],
 ['202204G801309306', 'ulil amri'],
 ['202304H2101895386', 'nurul mubarokah'],
 ['202204G401182094', 'nurisya amara putri'],
 ['202404A1601144037', 'karno'],
 ['202204D901235040', 'asmunah'],
 ['202304B2101152066', 'danang wahyu ananda'],
 ['202204E601281692', 'syamsul huda'],
 ['202204A1002318087', 'tumirah'],
 ['202404G702168896', 'nur qasanah'],
 ['202304D801591748', 'andika dwi pangestu'],
 ['202404G1301180583', 'mhd. yunus'],
 ['202304D1201191989', 'juminah'],
 ['202404B701245270', 'dwi yuliani'],
 ['202204D2201110048', 'chyndi erliani'],
 ['202404E201198430', 'eka putra'],
 ['202404E901328743', 'sri martini'],
 ['202404C1401481177', 'fadilla rahmadani'],
 ['202204F1401319546', 'ananda reyhan pradipta'],
 ['202404E1401224636', 'masinah'],
 ['202404B1801254349', 'd. maulana'],
 ['202204B601171832', 'kasri'],
 ['202204H1601103639', 'salami'],
 ['202404E301281793', 'eko rudiyanto'],
 ['202404D1501118793', 'desi susanti'],
 ['202201C1401853179', 'hafizhan shidqi'],
 ['202401F601359754', 'gandhi wibowo'],
 ['202401E201297920', 'aldio mahendra purwandrarto'],
 ['202401F1401235688', 'benny putra'],
 ['202401G301101004', 'vicky vernando dasta'],
 ['202201C801317909', 'jufianto henri'],
 ['202401A201191724', 'aan nuraini'],
 ['202301F301188942', 'abdur rahman'],
 ['202401D1201107894', 'abdurrahman'],
 ['202201C1202809227', 'ade indra sukma'],
 ['202201A1201426948', 'ade irmayani'],
 ['202401B102234701', 'bakti yoga fiyandana'],
 ['202301D502974343', 'daniel sepra fatama'],
 ['202301F801276693', 'dayu m sandro'],
 ['202401E801252445', 'dean mareti hariani'],
 ['202201F102790146', 'edi kurniawan wibowo'],
 ['202201C1501199660', 'fadil rahmat andini'],
 ['202401E1001106670', 'fahmi iqbal firmananda'],
 ['202301C701179134', 'fairuzi'],
 ['202301A801904281', 'gustian'],
 ['202401B1701109505', "habil sabilla do'a"],
 ['202401F201202238', 'hermawan syah'],
 ['202201G202541683', 'ibnuyohanzah ahmad'],
 ['202201D101158382', 'lia pertiwi'],
 ['202401F1201779217', 'muhammad maksum sugondo'],
 ['202201B601106424', 'muhammad risfandanu'],
 ['202401G801179356', 'adnil riza'],
 ['202301C201982309', 'nadia gustiana'],
 ['202401B701695024', 'nanda aditya'],
 ['202201F902905924', 'nurgivo alfajri'],
 ['202401E901143075', 'pita irul sayekti'],
 ['202401D601653378', 'rahmadi gusri'],
 ['202201B1201113844', 'rahmat'],
 ['202301B1301213627', 'sadra wilis'],
 ['202301B201546846', 'said rio apriadi'],
 ['202201G401244245', 'tania rahmadhini'],
 ['202201G1301253610', 'tarikhul mahfudz'],
 ['202201B1001207358', 'vido idramedi'],
 ['202201D702362677', 'wahyu darmawan'],
 ['202201G1001608779', 'yana famana'],
 ['202401G701246853', 'yusrika dewi'],
 ['202401C401326861', 'zakiah nurviani'],
 ['202301A1502183388', 'aditya dwi nugraha'],
 ['202201F701108260', 'afrian djugi'],
 ['202301G901113940', 'debby jayadi nugroho'],
 ['202401E101318264', 'dede dwi arviyanti'],
 ['202401D301150783', 'della maulina herianda'],
 ['202401B1101243838', 'deny gustriansyah'],
 ['202301C601327311', 'desi fitri'],
 ['202401G1201334212', 'edmund andriano'],
 ['202401A501146235', 'fajar aulia rahman'],
 ['202201A901507026', 'fathiya hasyifah sibarani'],
 ['202301F1502154785', 'fauzar'],
 ['202401A102228816', 'habzer maisera'],
 ['202201F1101221815', 'herzavina'],
 ['202401F1301173506', 'ikbal gazalba'],
 ['202401C1101107649', 'ikhsan firdaus'],
 ['202301C1002133645', 'ilda ikhwana lubis'],
 ['202401D1101627363', 'jayus suryawan'],
 ['202401A1101190007', 'muhammad bagoes samaron'],
 ['202301D801308666', 'muhammad hanafi'],
 ['202401A601280325', 'muhammad ilham akbar khoiri'],
 ['202401E301225335', 'narendra benny'],
 ['202301G102216110', 'naufal abiyyu'],
 ['202201D1301145223', 'nurhikmah'],
 ['202301G501200667', 'fadana bagus harsono'],
 ['202301B901146591', 'rahmi omya ulta'],
 ['202401D201540929', 'rahmi septhianingrum'],
 ['202401B801179872', 'rangga arief putra'],
 ['202201G1401719738', 'rangga dwi nugrawan'],
 ['202301A1001253569', 'saiful wahyudi'],
 ['202401A701148881', 'sari devia agustina'],
 ['202401C501122022', 'taufik oktafiyardi'],
 ['202401E601136387', 'teddy franwijaya'],
 ['202301A401642809', 'vigo farlandi'],
 ['202401C1302208095', 'wahyu ernu setiawan'],
 ['202401E501110403', 'yofaldi laksmana putra'],
 ['202301B301224486', 'zubaidah'],
 ['202401C301167805', 'agus faturrahman'],
 ['202301D901176102', 'agustiando rahmat'],
 ['202201B1401850401', 'aidil badri'],
 ['202201C901322212', 'alfajri'],
 ['202201F1001217139', 'bayu hasan basyir aljawi'],
 ['202401D1001284240', 'desi fransiska'],
 ['202401B1501205318', 'desnando'],
 ['202401G601112118', 'desri ardika'],
 ['202201A301108298', 'dessy masdianata p'],
 ['202201B1601123726', 'destria membrane'],
 ['202401G1101107053', 'eka nur safitri'],
 ['202201E701491693', 'fauziah'],
 ['202201D401300318', 'feny afrisilia'],
 ['202201F501115170', 'hesty afriani srg'],
 ['202401B501203099', 'ilham afandi aziz'],
 ['202401F401167127', 'ilham fajri'],
 ['202201G1501107924', 'indah permata sari'],
 ['202401B401149207', 'jukhri syahputra'],
 ['202201A1301288974', 'm. muawam'],
 ['202201E402758418', 'm. yassir saputra jamina'],
 ['202201C101288165', 'mardiyyat fadliellah'],
 ['202201A1402124801', 'mukhtar lutfi'],
 ['202402A201239827', 'neni anggraeni dalimunthe'],
 ['202202C701229873', 'nurpauliani dewi n'],
 ['202202D1301552394', 'rano abdul rahman'],
 ['202402A1701120005', 'ratih purwasih'],
 ['202302E302100388', 'raynaldi setiawan'],
 ['202402C1701143547', 'shynta dwi afitri'],
 ['202402C801265119', 'siti romlah'],
 ['202302F1302195246', 'teresno maulana'],
 ['202402D1601872975', 'tessa eka fatiwi'],
 ['202202D101962373', 'wendi gusfan hutapea'],
 ['202202C1201172437', 'yovita sari'],
 ['202402E502319942', 'zukri adinalta'],
 ['202202F1101424127', 'alfi sahri'],
 ['202402D1501209193', 'amalia wulandari'],
 ['202402D1101596820', 'amelia novrida'],
 ['202202C501800334', 'andre ganda wilaga putra'],
 ['202402A101166842', 'andre oktora'],
 ['202202A901138368', 'benni setiawan'],
 ['202202A701333112', 'deswanto'],
 ['202202E601336341', 'desy syahputri'],
 ['202402F1502224143', 'eka wulandari'],
 ['202302D901324382', 'ferry ramadhan'],
 ['202302B1701328116', 'firdaus'],
 ['202302A301633979', 'hamdani asril'],
 ['202302C601298963', 'hijrah syahputra'],
 ['202202B601299496', 'indah rahmawati'],
 ['202402B901239731', 'indra firman'],
 ['202202C1001505919', 'indri dian pertiwi'],
 ['202402C901126143', 'kemal pasha'],
 ['202402D202265966', 'muhammad sayuti nur nasution'],
 ['202402B801115149', 'miftahur ridho'],
 ['202402C1801132090', 'mila yuli yanti'],
 ['202202E201297512', 'muhammad wendi hidayat'],
 ['202402E101356311', 'nikawati'],
 ['202402D601307858', 'nofan widiyarna'],
 ['202402E1001179160', 'nurudin rahman'],
 ['202202B501290772', 'puji astuti'],
 ['202302E1301521228', 'refi delia'],
 ['202202D302657812', 'reno mulia sari'],
 ['202302A1801927507', 'resa putri ananda'],
 ['202402B1601131742', 'resi septiani'],
 ['202402F1201315533', 'rudi kurniawan'],
 ['202402E901163144', 'siti zulaiha'],
 ['202202A1501230829', 'sry dhina pohan'],
 ['202302B1001129721', 'thovanni jogga'],
 ['202302C1502813393', 'tian fitra kurniawan'],
 ['202402A1201241707', 'widya ayu azhari'],
 ['202302F101968479', 'yudiatma adrion'],
 ['202402D801748886', 'zukri rahman'],
 ['202402C1102254400', 'andre saputra'],
 ['202402B201317470', 'andrianto'],
 ['202202A602207641', 'andryan dwi cahyono'],
 ['202402B101938680', 'angga wiratama'],
 ['202302F201244676', 'anggi desmita arini'],
 ['202302C1401466789', 'dewi cita rani'],
 ['202302F901987448', 'dewi kartika sari'],
 ['202202D1401138938', 'dewi shinta octariati'],
 ['202202B302731350', 'firdaus'],
 ['202202C102223243', 'fitra andri gunawan'],
 ['202202C2201217456', 'indriani saritsha'],
 ['202402D1201767228', 'inggar wangi r'],
 ['202402E1201290167', 'mira afriani'],
 ['202402A1901159184', 'muhammad adri'],
 ['202202A501223919', 'muhammad alayyubi'],
 ['202402E401651754', 'nony chrisnayanti'],
 ['202302A801305305', 'nora ferwati'],

In [161]:
random.shuffle(contrib)
contrib

[[2024000000158999, 'umi maslikhah'],
 [2024000000958691, 'fahri al farisi'],
 [2024000000306418, 'sunarti'],
 [2024000000440214, 'singgih adi putra'],
 ['202405F602312162', 'vika kumala putri'],
 [2024000000261499, 'rudi febrianto'],
 ['202205D2202159875', 'silvi widya pangesti'],
 [2024000000103898, 'slamet harianto'],
 [2024000000142040, 'siyami'],
 ['202201G1001608779', 'yana famana'],
 ['202304H1001113075', 'vina nailatul izzah'],
 ['202206D2601316002', 'firda ramadan'],
 ['202403A801658283', 'wiwik purwanti'],
 [2024000000123963, 'eka afrilia pujianti'],
 ['202205B601145862', 'mujianto'],
 ['202403G1301219716', 'isti nurjanah'],
 ['202204F1501120952', 'tri adi eko lestanto'],
 ['202203D1801112245', 'dewi cahyati'],
 ['202405D1402221098', 'wahyu iswan arif'],
 ['202303F401246810', 'sumirah'],
 ['202406B1701679487', 'saniri'],
 [2024000000182947, 'al fathir rakha abyan'],
 ['202203H901431797', 'afrianda'],
 [2024000000915867, 'abdul hanafi purba'],
 ['202206E201339961', 'ibnu mirza hamizan alfaeyza'],
 ['202403B1001120987', 'sigit nugroho'],
 [2024000000230887, 'sadiah'],
 [2024000000128094, 'siti juwariyah'],
 [2024000000126826, 'sundari'],
 ['202406E2101215629', 'tesa rismiani'],
 [2024000000141942, 'faiz ahza praditya'],
 ['202405F901292073', 'pratama ade kurniawan'],
 ['202302A1801927507', 'resa putri ananda'],
 ['202206A802223259', 'sukarmin'],
 [2024000000160785, 'bini suharyati'],
 [2024000000504760, 'ali mustopo'],
 ['202204H2501185854', 'suprihatin'],
 [2024000000661189, 'tika ramawati'],
 [2024000000243224, 'eva apriyani'],
 ['202404C301161984', 'anwar sholeh'],
 [2024000000285118, 'samsuri'],
 ['202404E301281793', 'eko rudiyanto'],
 ['202203F1401104557', 'aris pratama putra'],
 [2024000000101381, 'arsy muhammad al habsy'],
 ['202406A1801210953', 'alfia santi sahputri'],
 ['202405E401207239', "mukhammad 'ainurrido"],
 [2024000000134371, 'nur jannah'],
 ['202301C601327311', 'desi fitri'],
 ['202402A1601308211', 'muhammad thoha'],
 ['202405A501461539', 'muhammad rizky aprianto'],
 ['202404D1001829653', 'vika apriliana n. a'],
 [2024000000137373, 'herman'],
 ['202303E801272421', 'zenika pradea'],
 ['202204B2402683619', 'rizki pratama'],
 [2024000000290534, 'tri murtini'],
 ['202203A1001314392', 'ridwan candra'],
 ['202204D301167570', 'raditia saputri'],
 ['202203H1301295709', 'rahmad erwin wibisono'],
 ['202202B302731350', 'firdaus'],
 ['202406C501192063', 'sitti julaeha'],
 [2024000000123162, 'dwi kurniasih'],
 ['202406D1701301372', 'ria rasela'],
 [2024000000274971, 'nova ayu sharafika'],
 ['202303G1101892420', 'arif fasetyo'],
 ['202201C801317909', 'jufianto henri'],
 ['202406D1901170712', 'nuraini'],
 ['202404B401216705', 'sumardi'],
 [2024000000145788, 'andi sofyan'],
 ['202402A1201241707', 'widya ayu azhari'],
 ['202404C201164310', 'nora'],
 [2024000000220545, 'tukini'],
 ['202304A301887019', 'girah'],
 ['202205D2601280272', 'edi susanto'],
 ['202401D601653378', 'rahmadi gusri'],
 ['202406A2001143554', 'muhammad abdul rohman'],
 ['202401B401149207', 'jukhri syahputra'],
 ['202306C1101653287', 'amal fatullah'],
 [2024000000213148, 'sukirman'],
 ['202404F502164267', 'siti masliah'],
 ['202404F1601237891', 'rozakiah'],
 ['202402F1201315533', 'rudi kurniawan'],
 [2024000000143278, 'paryono'],
 ['202405D2901241198', 'marsiti'],
 ['202202D1701182164', 'dias marzal fatama'],
 ['202405D401187664', 'nur sodik'],
 [2024000000274900, 'suparmi'],
 [2024000000293010, 'rahmat tri apriliando'],
 ['202405E1501336632', 'munib alwi abdurohman'],
 [2024000000265745, 'ahmad priyanto'],
 ['202405F1101100006', 'sakiyah'],
 ['202402E502319942', 'zukri adinalta'],
 [2024000000290291, 'agustina muntikawati'],
 ['202206F1102132096', 'reni sriyati'],
 ['202406B1201104445', 'nanang mujahid'],
 ['202204C1901257804', 'kholipah'],
 ['202206A901269732', 'nur kholifah'],
 [2024000000539811, 'suci melia putri'],
 ['202205A1701526396', 'nurdiana saputri'],
 ['202301G501200667', 'fadana bagus harsono'],
 [2024000000790281, 'rusmiyati'],
 ['202304H601186699', 'sumarno'],
 [2024000000263331, 'muhammad susanto'],
 [2024000000315486, 'hariyono'],
 [2024000000211096, 'eria zilan putri'],
 [2024000000286334, 'muhammad aprila'],
 [2024000000107433, 'maisaroh'],
 ['202405F701297344', 'suparno'],
 [2024000000529296, 'salpiah'],
 ['202401A201191724', 'aan nuraini'],
 [2024000000149750, 'luthfi abdillah'],
 ['202301F801276693', 'dayu m sandro'],
 ['202403G1601312097', 'redha fauziah aziz'],
 ['202202C301290842', 'dika aristya linardi'],
 ['202204H1701339447', 'suwarsih'],
 [2024000000787095, 'rizki septiadi'],
 [2024000000317203, 'nina ayu lestari'],
 [2024000000576220, 'harun fadhillah'],
 ['202402D1601872975', 'tessa eka fatiwi'],
 ['202304F401153396', 'sazim saputra'],
 ['202401E801252445', 'dean mareti hariani'],
 [2024000000165286, 'mitro panut'],
 [2024000000643158, 'azizah hanifatur rahma'],
 ['202303F1801368209', 'daryono'],
 ['202402A201239827', 'neni anggraeni dalimunthe'],
 [2024000000199140, 'atun puji rahayu'],
 ['202205G801109789', 'siti umayah'],
 ['202404B1401281974', 'santoso'],
 ['202204D1601588854', 'gilang nur bekti'],
 ['202204A101183585', 'eko kurniawan'],
 [2024000000248839, 'lasmini'],
 [2024000000554343, "mu'alifah"],
 ['202202D101962373', 'wendi gusfan hutapea'],
 [2024000000950185, 'azza nabilla tasya'],
 ['202204A201235672', 'sukma liyana dewi'],
 ['202204H102127990', 'mira mustika'],
 [2024000000231405, 'agung susilo'],
 [2024000000879619, 'swarti'],
 ['202206D801254703', 'suratman'],
 ['202403C901487836', 'ainun isnaini fauziati'],
 [2024000000281225, 'ahmad purwito'],
 [2024000000285934, 'kevin kenzi al firmansyah'],
 ['202303D1501206345', 'ichsyan rizky adi p'],
 ['202405B1101324358', 'auliya nur syahidah'],
 ['202206B1502254951', 'ervi lidya wati'],
 [2024000000801121, 'hani sali sati'],
 ['202201G1401719738', 'rangga dwi nugrawan'],
 [2024000000372269, 'sucipto'],
 ['202206B601226954', 'suyoto'],
 [2024000000236600, 'budiman syahputra'],
 ['202202F602305637', 'yulia ningsih'],
 [2024000000201678, 'aisyah giovani'],
 [2024000000259789, 'anindita keisha azzahra'],
 ['202202C501800334', 'andre ganda wilaga putra'],
 [2024000000382639, 'ujang umin ruhdiansyah'],
 ['202204F201271209', 'noviana anggraeni'],
 ['202306C302955398', 'iqbal akbar ghofur'],
 [2024000000566032, 'diky handriansyah'],
 ['202402D2001152626', 'harika vaizal'],
 [2024000000686909, 'setio purwanto'],
 ['202203D501257426', 'muhammad fajar maulana'],
 ['202406A1701251650', 'pirawati'],
 ['202304B2301126887', 'manisem'],
 [2024000000939806, 'novi ayu sharafina'],
 ['202404E401308752', 'sumono'],
 ['202301D801308666', 'muhammad hanafi'],
 ['202205F301332759', 'fitria lestari'],
 [2024000000457765, 'gino'],
 ['202201F1001217139', 'bayu hasan basyir aljawi'],
 [2024000000177997, 'giono'],
 [2024000000270652, 'sariman'],
 [2024000000281731, 'iman wahyudi'],
 ['202405C1301493744', 'agus nuryanto'],
 ['202403D2501171004', 'yunaldi rizki putra'],
 ['202406D2501255607', 'rhamasya damar'],
 ['202404A1501408083', 'oki aditia saputra'],
 [2024000000222628, 'ngadinem'],
 [2024000000365428, 'supri ani'],
 ['202402E1201290167', 'mira afriani'],
 [2024000000157919, 'ismail'],
 [2024000000792641, 'lukman wibowo. s'],
 ['202203H702309642', 'nur aulia hasanah'],
 [2024000000183048, 'andi baskoro'],
 ['202401E501110403', 'yofaldi laksmana putra'],
 ['202401G601112118', 'desri ardika'],
 [2024000000246801, 'muhammad akbar rizan'],
 [2024000000763424, 'dwi rukiyah'],
 [2024000000203262, 'shela nur diana sari'],
 [2024000000120713, 'abdul rahman'],
 ['202306D2201203796', 'ayu kusmini'],
 [2024000000325601, 'jumali'],
 ['202202C2402312923', 'padli nofrizal'],
 [2024000000892291, 'santi susanti'],
 ['202405B1601121577', 'susi susanti'],
 ['202202C701229873', 'nurpauliani dewi n'],
 ['202202B501290772', 'puji astuti'],
 [2024000000187840, 'roliana silalahi'],
 [2024000000500571, 'ilham setiaji'],
 ['202401A102228816', 'habzer maisera'],
 [2024000000444692, 'ismiyati'],
 ['202206D2401226968', 'madha leli'],
 ['202403D1701146338', 'juli anggraeni'],
 [2024000000340150, 'tumirah'],
 ['202203G202891331', 'sri mulyani'],
 ['202201A1201426948', 'ade irmayani'],
 [2024000000270368, 'yunersen'],
 [2024000000998522, 'niwan'],
 ['202205B701776582', 'ihwanul muslimin'],
 ['202204D2401714192', 'abdul malik'],
 ['202205E1101186690', 'suendik'],
 [2024000000105889, 'azizah hanifatur rahma'],
 ['202405F1001240087', 'debyo widya anggara'],
 [2024000000363071, 'paino'],
 ['202304B1301147196', 'dede adiyanto'],
 ['202303G301213614', 'slamet'],
 ['202402D1801213034', 'kurniawan eka putra'],
 [2024000000280673, 'nur khalim'],
 [2024000000281204, 'suyatno'],
 [2024000000245292, 'tri winarti'],
 [2024000000152531, 'seli hapti anggara'],
 ['202204G1201140324', 'supriyadi'],
 ['202204C901139635', 'desi tri astuti'],
 ['202206D2302190663', 'irma lestari'],
 [2024000000663870, 'misbahatussudury'],
 [2024000000844783, 'sofyan ali syahbana'],
 ['202203D201180421', 'muhammad setyo'],
 [2024000000128207, 'joni kartinus'],
 ['202304D501193423', 'nurtriana yuliastuti'],
 [2024000000332297, 'tawirja'],
 [2024000000320478, 'atik winarni'],
 [2024000000147496, 'rebo'],
 [2024000000289560, 'mukhlis sariadin'],
 ['202406A1201167551', 'fauzi hidayat'],
 [2024000000167698, 'tasminah'],
 ['202401C401326861', 'zakiah nurviani'],
 [2024000000324963, 'khairudin'],
 [2024000000306324, 'nirmala syafira'],
 ['202302C1901335849', 'benny yohanes'],
 [2024000000278043, 'dewi'],
 ['202405A1101349923', 'rina pangastuti'],
 [2024000000279430, 'fauzan adi saputra'],
 [2024000000317411, 'siswanto'],
 [2024000000185188, 'tumidjo'],
 ['202402F1601271253', 'novia kumala sari'],
 ['202304C1801847516', 'erina ramadhani'],
 ['202206D102117970', 'supratman'],
 [2024000000265865, 'yuli yanti'],
 [2024000000266830, 'khairul ilham'],
 ['202304G901425924', 'tri anindita aurellia'],
 ['202401A701148881', 'sari devia agustina'],
 ['202206B1401296048', 'krisno tri widodo'],
 ['202204B901173219', 'nugroho'],
 [2024000000300775, 'siti mudrikah'],
 [2024000000812538, "alfin akbar rifa'i"],
 [2024000000228448, 'siti komariyah'],
 ['202402C401424971', 'rahmi andreni'],
 ['202405E202112760', 'supingatun'],
 ['202204G202152887', 'dewi wulan ningsih'],
 ['202403F1501118123', 'm. charly iman nugroho'],
 [2024000000246800, 'warhan'],
 [2024000000306306, 'sri mulyati'],
 [2024000000341213, 'riki supendi'],
 ['202303A1502209362', 'pikril islami'],
 [2024000000273656, 'murdiansyah'],
 ['202303C1201119547', 'ruwadi saputra'],
 ['202206C202130077', 'nadhirotul khusniah'],
 ['202305E2001336624', 'aqra nabiha anindita'],
 [2024000000336458, 'mariyem'],
 [2024000000316955, 'muhammad albana'],
 [2024000000143083, 'muji syukur'],
 ['202406F502120811', 'hamdan muzakir'],
 ['202205B1001253528', 'imam subaweh'],
 [2024000000245561, 'khairudin'],
 [2024000000250925, 'supri yanto'],
 ['202202F802987140', 'muhammad triyoga sp'],
 [2024000000106687, 'asiva nur aini'],
 ['202305B1501329570', 'agus riyanto'],
 ['202205B901102355', 'wasyaraffa al hafiz'],
 [2024000000270179, 'setio purwanto'],
 ['202404B1601128953', 'mariyamah'],
 ['202403H401873238', 'sufiyani'],
 ['202405G101900114', "soni haji rifa'i"],
 [2024000000233081, 'sukatmi'],
 [2024000000280513, 'sudirman'],
 [2024000000138627, 'silvia ayu nadira rahmawati'],
 ['202206E901169493', 'siti aisyah'],
 [2024000000320786, 'shoffan al fath'],
 ['202206C1001297572', 'olivvia febby santika'],
 ['202403C1101101630', 'dewi safitri'],
 [2024000000879282, 'fauziyah'],
 [2024000000146104, 'muhammad habibullah'],
 [2024000000908632, 'eka restiawati'],
 [2024000000276568, 'tumiati'],
 [2024000000529004, 'mariyem'],
 ['202202F1402326018', 'husnul habib'],
 ['202205E1201125278', 'hadista nadratul zanah'],
 [2024000000271363, 'nur aida dwi ramadhani'],
 ['202205F1201285985', 'astriyah'],
 [2024000000621367, 'listiani'],
 [2024000000286889, 'khoiru nisa aprilia'],
 [2024000000811558, 'm. tri ananta anugrah'],
 ['202405B501315121', 'saputra'],
 [2024000000250553, 'ani'],
 ['202404A1801142793', 'mustofa'],
 ['202305A701116633', 'riswanto'],
 [2024000000255929, 'sudarseh'],
 ['202201G1301253610', 'tarikhul mahfudz'],
 [2024000000254451, 'tika ramawati'],
 [2024000000189036, 'safiq heryanto'],
 ['202204A1201201535', 'devina tria ananda'],
 ['202302E1301521228', 'refi delia'],
 [2024000000293409, 'adiba zahara'],
 ['202403E302102225', 'dwiki apsyarin'],
 ['202305G901277825', 'bagus suryanto'],
 ['202206B701220346', 'saikun'],
 [2024000000195219, 'muhammad rikza rohmana'],
 ['202205A1201200089', "siti arifatul fu'adah"],
 ['202403B1801149933', 'poniyem'],
 ['202404F1302138965', 'ricky prayoga'],
 ['202202B1101246542', 'putri wahyuni'],
 ['202403D1601803577', 'nurfatrianti'],
 ['202201G202541683', 'ibnuyohanzah ahmad'],
 [2024000000109078, 'revianita inka hadi'],
 ['202302C1502813393', 'tian fitra kurniawan'],
 ['202204G801309306', 'ulil amri'],
 ['202306D401115813', 'komsidah'],
 ['202305F201111697', 'ari sarianto'],
 [2024000000235434, 'sri rejeki'],
 ['202404B1801254349', 'd. maulana'],
 ['202404H901425975', 'wahid suprayitno'],
 ['202203B1401152918', 'reza andika ramadhan'],
 ['202203G801100622', 'rosidin'],
 [2024000000703325, 'muhammad rikza rohmana'],
 [2024000000171820, 'slamet'],
 ['202202B701240388', 'elennuari'],
 [2024000000368007, 'surya kusuma'],
 ['202405E101509831', 'faisal'],
 ['202201B1601123726', 'destria membrane'],
 ['202205D1101531840', 'indah kurnia sari'],
 [2024000000110825, 'maulana mujahid'],
 ['202205D201232212', 'parni'],
 ['202306F701120139', 'rubini'],
 ['202206B1302154200', 'saiman'],
 [2024000000127103, 'azuwa fatkur alkholif'],
 ['202204G401182094', 'nurisya amara putri'],
 ['202205D301288532', 'tuti rahayu'],
 [2024000000226515, 'hanifatun nasyroh'],
 ['202206D1201923432', 'wulandari'],
 ['202204C1501285096', 'romadon nur hidayat'],
 [2024000000293939, 'sugianto'],
 [2024000000890499, 'haikal aziz kurniawan'],
 ['202205G402280480', 'imam turmudzi'],
 ['202206D702780727', 'siti khasanah'],
 [2024000000630903, 'shela nur diana sari'],
 ['202306D1402203158', 'katiman'],
 [2024000000270495, 'sahid'],
 ['202402F501168754', 'putri lia lestari'],
 ['202201C1501199660', 'fadil rahmat andini'],
 ['202203D2101228983', 'suwarti'],
 ['202203A1601285586', 'boby rahman'],
 ['202401D301150783', 'della maulina herianda'],
 ['202403D401113526', 'fajar setiawan'],
 ['202206B201218297', 'siti zaenab'],
 ['202204G1401291206', 'puji lestari'],
 ['202302F201244676', 'anggi desmita arini'],
 ['202203D701987639', 'sakiyo'],
 [2024000000140030, 'sariani'],
 [2024000000250303, 'aprilia rahmawati'],
 [2024000000101103, 'dion aldi setiawan'],
 ['202201F1101221815', 'herzavina'],
 [2024000000158827, 'surya dwi syahputra'],
 [2024000000960512, 'ani'],
 ['202201F102790146', 'edi kurniawan wibowo'],
 ['202204B1901256452', 'rasman'],
 ['202403C1402295046', 'muhammad oki'],
 [2024000000269039, 'citra ayu wulandari'],
 ['202305D1801316217', 'warsini'],
 ['202203D2001107296', 'muliadi'],
 ['202205E1601109221', 'suwanter'],
 ['202204H501102478', 'muslimah'],
 ['202204D1801293350', 'suyono'],
 [2024000000231713, 'diana nur fhaisah'],
 ['202403E201571358', 'rohatun'],
 [2024000000188126, 'evi alisma'],
 [2024000000222844, 'sukadi'],
 ['202305D1601150735', 'musaadah'],
 ['202304G1601313448', 'sumiati'],
 ['202203B1902780908', 'rizqi wahyuningsih'],
 [2024000000378938, 'kelvin naszril tri efendi'],
 ['202205B801111631', 'muji astuti'],
 [2024000000186891, 'alisa devi saputri'],
 [2024000000877519, 'ike handayani'],
 ['202206A701138450', 'sulastri'],
 [2024000000336819, 'binti'],
 [2024000000339933, 'desi ratnasari'],
 ['202303A901220966', 'kurniawan rosman a'],
 [2024000000199239, 'sumarno'],
 [2024000000154077, 'rafika oktavianti'],
 ['202201F902905924', 'nurgivo alfajri'],
 ['202404F701387887', 'ahmad saprudin'],
 ['202404F901326641', 'air murya'],
 ['202306C1201110502', 'nur laila'],
 [2024000000307679, 'tumi setiawati'],
 ['202401A501146235', 'fajar aulia rahman'],
 [2024000000262125, 'ibnu haris purba'],
 [2024000000493247, 'taufik usman'],
 ['202203H1901209011', 'dewi wulan sari'],
 ['202402B901239731', 'indra firman'],
 [2024000000993166, 'duwi a. fikri'],
 ['202304F1701944800', 'alifia yuliani'],
 ['202303D802517421', 'arinda oktaviana'],
 ['202306C801324025', 'suparlan'],
 [2024000000100579, 'supri ani'],
 ['202403H2402144237', 'ruswantoro'],
 ['202305E701166824', 'azzah rotun nisa almufidah'],
 ['202206B901124420', 'fajri syahdan naufal'],
 ['202406A301778260', 'lilik mujiati'],
 [2024000000173592, 'irvan maulana'],
 [2024000000132078, 'jaemah'],
 ['202203C602480434', 'ade surahman'],
 ['202406C901313408', 'ahmad suyadi'],
 ['202405G1401159917', 'tumiati'],
 [2024000000116385, 'rafika dewi sari'],
 [2024000000240199, 'asim'],
 [2024000000212127, 'santi susanti'],
 ['202406D2702336165', "mas' ud"],
 ['202204D2201110048', 'chyndi erliani'],
 [2024000000266389, 'sugianto'],
 [2024000000118279, 'ismini'],
 ['202304A401278605', 'warsini'],
 [2024000000192716, 'muhaimin'],
 [2024000000232039, 'bukhori'],
 ['202202C2101117723', 'anggia anfina'],
 ['202402D801748886', 'zukri rahman'],
 ['202402A1901159184', 'muhammad adri'],
 [2024000000297616, 'sutrisno'],
 [2024000000316473, 'teguh ramadhan'],
 ['202203H2302381430', 'ridho rismayanda'],
 [2024000000687788, 'winda aprilia'],
 ['202204D201192978', 'nurhayati'],
 ['202201A1402124801', 'mukhtar lutfi'],
 [2024000000101494, 'titin fatimah'],
 ['202206F1501125594', 'jefri setiadi'],
 [2024000000198889, 'didik siswanto'],
 ['202303H2501280011', 'asri jakawendra'],
 [2024000000266776, 'afni dwi lestari'],
 [2024000000325528, 'mustaqpirin'],
 [2024000000335264, 'salpiah'],
 [2024000000116404, 'iman wahyudi'],
 [2024000000137737, 'sutomo'],
 [2024000000541028, 'singgih adi putra'],
 ['202402B1501327618', 'rahmat hidayat'],
 ['202302E302100388', 'raynaldi setiawan'],
 [2024000000310296, 'yuda aldiansyah'],
 ['202206B401226126', 'siti zaenap'],
 ['202405A1301163228', 'wilmaini'],
 ['202401B801179872', 'rangga arief putra'],
 ['202403A401275540', 'auliya shobrina'],
 ['202305A601188975', 'sumari'],
 ['202404G101282721', 'rumsiyah'],
 [2024000000109752, 'syavira hanzuneira'],
 [2024000000614085, 'dimas dwi fadilah'],
 [2024000000333142, 'haikal aziz kurniawan'],
 [2024000000167763, 'sudin'],
 ['202404E201198430', 'eka putra'],
 ['202303H501220892', 'yuni dwi hastuti'],
 [2024000000656569, 'nafiudin'],
 [2024000000280518, 'arif nova baihaqi'],
 ['202401B102234701', 'bakti yoga fiyandana'],
 ['202302A801305305', 'nora ferwati'],
 ['202306B1101122700', 'jamilatun azizah'],
 [2024000000578537, 'riska sundari'],
 ['202405F101738229', 'm. husmudin'],
 ['202304B1702291010', 'mukaromah'],
 [2024000000884925, 'salim'],
 ['202305A101308240', 'saim'],
 [2024000000324720, 'wahab maulana ramadhan'],
 [2024000000331699, 'syafia zahra aprelia'],
 [2024000000112969, 'siti aisah'],
 ['202206D501839185', 'rensy herwinda'],
 ['202406E1601259473', 'wahidi'],
 ['202205E1402246535', 'meysa nasa'],
 [2024000000133081, 'yusi andriyani'],
 ['202403D2401187867', 'novri sabli saputra'],
 ['202403C1501165303', 'sumirah'],
 ['202402D202265966', 'muhammad sayuti nur nasution'],
 ['202404H801186252', 'trio hamdani'],
 ['202404E1602247621', 'dzul helmi affan ridho'],
 ['202306D1001176872', 'eliyuswisnawaty'],
 ['202304E101756498', 'samiyah'],
 ['202401E1001106670', 'fahmi iqbal firmananda'],
 [2024000000163525, 'alwan supangat'],
 ['202401A1101190007', 'muhammad bagoes samaron'],
 ['202406A102244727', 'pursito'],
 ['202401E301225335', 'narendra benny'],
 ['202205G201787901', 'nafiudin'],
 [2024000000659169, 'gunawan'],
 ['202304C801243624', 'setiawan'],
 [2024000000280999, 'supri yanto'],
 [2024000000247371, 'rubiyati'],
 [2024000000339602, 'somad susanto'],
 ['202203H801263500', 'nelvin adhy renata'],
 ['202305C801166506', 'eni dwi sundari'],
 [2024000000152594, 'kasianto'],
 ['202401F1401235688', 'benny putra'],
 [2024000000500384, 'choiriyah'],
 ['202205G1302218270', 'sutarsih'],
 ['202202D302657812', 'reno mulia sari'],

In [162]:
merchant_review_ = np.c_[merchant_review, review_merchant, contrib[:86]]
merchant_review_

array([['Superindo', '03', '4', ' suasana sangat baik.', '2023-07-12',
        'positive', '2024000000158999', 'umi maslikhah'],
       ['Superindo', '03', '4', ' penyajian sangat baik.', '2023-06-06',
        'positive', '2024000000958691', 'fahri al farisi'],
       ['Nice So', '13', '1',
        'pelayanannya sangat buruk, dimohon untuk pelayanannya ditingkatkan lagi.',
        '2023-10-24', 'negative', '2024000000306418', 'sunarti'],
       ['Miniso', '12', '5', ' harga sangat baik.', '2023-04-19',
        'positive', '2024000000440214', 'singgih adi putra'],
       ['Intermedia', '14', '1', ' pelayanan sangat buruk.',
        '2023-07-18', 'negative', '202405F602312162',
        'vika kumala putri'],
       ['Haus', '05', '1',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-10-08', 'negative', '2024000000261499', 'rudi febrianto'],
       ['Ceria', '10', '3',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-10-04', 'negative', '202205D2202159875',
        'silvi widya pangesti'],
       ['Alfamart', '01', '1',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-07-07', 'negative', '2024000000103898', 'slamet harianto'],
       ['Miniso', '12', '3',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-06-09', 'negative', '2024000000142040', 'siyami'],
       ['Kopi Kenangan', '09', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-06-17', 'positive', '202201G1001608779', 'yana famana'],
       ['Ceria', '10', '4',
        'suasananya baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-01-24', 'positive', '202304H1001113075',
        'vina nailatul izzah'],
       ['Ceria', '10', '1', ' suasana buruk.', '2023-07-30', 'negative',
        '202206D2601316002', 'firda ramadan'],
       ['Haus', '05', '1', ' harga sangat buruk.', '2023-11-19',
        'negative', '202403A801658283', 'wiwik purwanti'],
       ['Kopi Kenangan', '09', '2',
        'suasananya buruk, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-09-16', 'negative', '2024000000123963',
        'eka afrilia pujianti'],
       ['Superindo', '03', '4',
        'suasananya baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-01-30', 'positive', '202205B601145862', 'mujianto'],
       ['Mie Gacoan', '06', '1',
        'suasananya buruk, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-04-05', 'negative', '202403G1301219716', 'isti nurjanah'],
       ['Intermedia', '14', '1', ' suasana buruk.', '2023-07-30',
        'negative', '202204F1501120952', 'tri adi eko lestanto'],
       ['Superindo', '03', '1',
        'suasananya buruk, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-07-21', 'negative', '202203D1801112245', 'dewi cahyati'],
       ['Superindo', '03', '3',
        'barangnya buruk, dimohon untuk barangnya ditingkatkan lagi.',
        '2023-05-14', 'negative', '202405D1402221098',
        'wahyu iswan arif'],
       ['Nice So', '13', '1',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-06-30', 'negative', '202303F401246810', 'sumirah'],
       ['Superindo', '03', '5',
        'harganya sangat baik, dimohon untuk harganya ditingkatkan lagi.',
        '2023-02-02', 'positive', '202406B1701679487', 'saniri'],
       ['Fore Coffee', '08', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-05-01', 'positive', '2024000000182947',
        'al fathir rakha abyan'],
       ['Idolmart', '02', '4',
        'suasananya baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-02-26', 'positive', '202203H901431797', 'afrianda'],
       ['Kopi Kenangan', '09', '5',
        'Saya mengalami pengalaman baik secara keseluruhan.',
        '2023-05-02', 'positive', '2024000000915867',
        'abdul hanafi purba'],
       ['Kopi Kenangan', '09', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-10-31', 'positive', '202206E201339961',
        'ibnu mirza hamizan alfaeyza'],
       ['Fore Coffee', '08', '4',
        'suasananya sangat baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-07-11', 'positive', '202403B1001120987', 'sigit nugroho'],
       ['Mie Gacoan', '06', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-08-03', 'positive', '2024000000230887', 'sadiah'],
       ['Si Bersih', '11', '1',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-03-19', 'negative', '2024000000128094', 'siti juwariyah'],
       ['Kopi Kenangan', '09', '2',
        'harganya buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-03-13', 'negative', '2024000000126826', 'sundari'],
       ['Kopi Kenangan', '09', '3',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-06-17', 'negative', '202406E2101215629', 'tesa rismiani'],
       ['Alfamart', '01', '1', ' makanan dan minuman sangat buruk.',
        '2023-01-31', 'negative', '2024000000141942',
        'faiz ahza praditya'],
       ['Intermedia', '14', '3',
        'Saya mengalami pengalaman sangat buruk secara keseluruhan.',
        '2023-03-04', 'negative', '202405F901292073',
        'pratama ade kurniawan'],
       ['Ceria', '10', '5', ' suasana sangat baik.', '2023-07-13',
        'positive', '202302A1801927507', 'resa putri ananda'],
       ['Ceria', '10', '4',
        'harganya sangat baik, dimohon untuk harganya ditingkatkan lagi.',
        '2023-04-12', 'positive', '202206A802223259', 'sukarmin'],
       ['Kopi Kenangan', '09', '4',
        'harganya baik, dimohon untuk harganya ditingkatkan lagi.',
        '2023-08-30', 'positive', '2024000000160785', 'bini suharyati'],
       ['Idolmart', '02', '5', ' harga sangat baik.', '2023-03-14',
        'positive', '2024000000504760', 'ali mustopo'],
       ['Superindo', '03', '4',
        'penyajiannya sangat baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-08-31', 'positive', '202204H2501185854', 'suprihatin'],
       ['Superindo', '03', '5', ' penyajian sangat baik.', '2023-01-08',
        'positive', '2024000000661189', 'tika ramawati'],
       ['Sederhana', '07', '4',
        'pelayanannya sangat baik, dimohon untuk pelayanannya ditingkatkan lagi.',
        '2023-09-22', 'positive', '2024000000243224', 'eva apriyani'],
       ['Si Bersih', '11', '1', ' penyajian buruk.', '2023-11-01',
        'negative', '202404C301161984', 'anwar sholeh'],
       ['Mie Gacoan', '06', '1',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-10-08', 'negative', '2024000000285118', 'samsuri'],
       ['Intermedia', '14', '4',
        'harganya sangat baik, dimohon untuk harganya ditingkatkan lagi.',
        '2023-06-15', 'positive', '202404E301281793', 'eko rudiyanto'],
       ['Superindo', '03', '5',
        'Saya mengalami pengalaman baik secara keseluruhan.',
        '2023-07-03', 'positive', '202203F1401104557',
        'aris pratama putra'],
       ['Fore Coffee', '08', '4',
        'suasananya baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-02-26', 'positive', '2024000000101381',
        'arsy muhammad al habsy'],
       ['Fore Coffee', '08', '4',
        'penyajiannya sangat baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-08-31', 'positive', '202406A1801210953',
        'alfia santi sahputri'],
       ['Superindo', '03', '5',
        'penyajiannya baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-06-07', 'positive', '202405E401207239',
        "mukhammad 'ainurrido"],
       ['Idolmart', '02', '4',
        'barangnya sangat baik, dimohon untuk barangnya ditingkatkan lagi.',
        '2023-08-15', 'positive', '2024000000134371', 'nur jannah'],
       ['Kopi Kenangan', '09', '5',
        'Saya mengalami pengalaman baik secara keseluruhan.',
        '2023-07-03', 'positive', '202301C601327311', 'desi fitri'],
       ['Kopi Kenangan', '09', '1',
        'harganya sangat buruk, dimohon untuk harganya ditingkatkan lagi.',
        '2023-10-08', 'negative', '202402A1601308211', 'muhammad thoha'],
       ['Nice So', '13', '3', ' penyajian sangat buruk.', '2023-04-28',
        'negative', '202405A501461539', 'muhammad rizky aprianto'],
       ['Alfamart', '01', '1',
        'Saya mengalami pengalaman sangat buruk secara keseluruhan.',
        '2023-09-14', 'negative', '202404D1001829653',
        'vika apriliana n. a'],
       ['Superindo', '03', '3', ' penyajian sangat buruk.', '2023-01-15',
        'negative', '2024000000137373', 'herman'],
       ['Sederhana', '07', '1',
        'pelayanannya sangat buruk, dimohon untuk pelayanannya ditingkatkan lagi.',
        '2023-10-24', 'negative', '202303E801272421', 'zenika pradea'],
       ['Superindo', '03', '1', ' suasana sangat buruk.', '2023-10-17',
        'negative', '202204B2402683619', 'rizki pratama'],
       ['Mie Gacoan', '06', '4',
        'penyajiannya baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-08-25', 'positive', '2024000000290534', 'tri murtini'],
       ['Haus', '05', '3',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-10-16', 'negative', '202203A1001314392', 'ridwan candra'],
       ['Ceria', '10', '5',
        'penyajiannya sangat baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-11-23', 'positive', '202204D301167570', 'raditia saputri'],
       ['Fore Coffee', '08', '3', ' barang buruk.', '2023-10-11',
        'negative', '202203H1301295709', 'rahmad erwin wibisono'],
       ['Haus', '05', '4',
        'penyajiannya baik, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-06-17', 'positive', '202202B302731350', 'firdaus'],
       ['Mixue', '04', '3',
        'penyajiannya sangat buruk, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-10-12', 'negative', '202406C501192063', 'sitti julaeha'],
       ['Miniso', '12', '5',
        'makanan dan minumannya sangat baik, dimohon untuk makanan dan minumannya ditingkatkan lagi.',
        '2023-08-22', 'positive', '2024000000123162', 'dwi kurniasih'],
       ['Mie Gacoan', '06', '3',
        'pelayanannya buruk, dimohon untuk pelayanannya ditingkatkan lagi.',
        '2023-02-28', 'negative', '202406D1701301372', 'ria rasela'],
       ['Miniso', '12', '1',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-06-18', 'negative', '2024000000274971',
        'nova ayu sharafika'],
       ['Miniso', '12', '1',
        'suasananya buruk, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-07-21', 'negative', '202303G1101892420', 'arif fasetyo'],
       ['Indomaret', '00', '3',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-03-26', 'negative', '202201C801317909', 'jufianto henri'],
       ['Si Bersih', '11', '4',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-04-19', 'positive', '202406D1901170712', 'nuraini'],
       ['Kopi Kenangan', '09', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-05-04', 'positive', '202404B401216705', 'sumardi'],
       ['Mie Gacoan', '06', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-01-21', 'positive', '2024000000145788', 'andi sofyan'],
       ['Idolmart', '02', '2',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-03-24', 'negative', '202402A1201241707',
        'widya ayu azhari'],
       ['Fore Coffee', '08', '5', ' pelayanan baik.', '2023-07-03',
        'positive', '202404C201164310', 'nora'],
       ['Alfamart', '01', '2',
        'Saya mengalami pengalaman buruk secara keseluruhan.',
        '2023-10-18', 'negative', '2024000000220545', 'tukini'],
       ['Fore Coffee', '08', '5', ' harga baik.', '2023-05-31',
        'positive', '202304A301887019', 'girah'],
       ['Mixue', '04', '1', ' suasana buruk.', '2023-10-21', 'negative',
        '202205D2601280272', 'edi susanto'],
       ['Alfamart', '01', '4',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-04-19', 'positive', '202401D601653378', 'rahmadi gusri'],
       ['Intermedia', '14', '5',
        'Saya mengalami pengalaman baik secara keseluruhan.',
        '2023-04-01', 'positive', '202406A2001143554',
        'muhammad abdul rohman'],
       ['Intermedia', '14', '4',
        'suasananya baik, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-01-24', 'positive', '202401B401149207', 'jukhri syahputra'],
       ['Superindo', '03', '1',
        'penyajiannya sangat buruk, dimohon untuk penyajiannya ditingkatkan lagi.',
        '2023-09-14', 'negative', '202306C1101653287', 'amal fatullah'],
       ['Superindo', '03', '4',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-02-07', 'positive', '2024000000213148', 'sukirman'],
       ['Fore Coffee', '08', '5', ' pelayanan baik.', '2023-07-03',
        'positive', '202404F502164267', 'siti masliah'],
       ['Idolmart', '02', '2', ' harga buruk.', '2023-06-04', 'negative',
        '202404F1601237891', 'rozakiah'],
       ['Mie Gacoan', '06', '2',
        'suasananya buruk, dimohon untuk suasananya ditingkatkan lagi.',
        '2023-09-16', 'negative', '202402F1201315533', 'rudi kurniawan'],
       ['Mixue', '04', '5', ' harga baik.', '2023-09-10', 'positive',
        '2024000000143278', 'paryono'],
       ['Fore Coffee', '08', '4',
        'harganya sangat baik, dimohon untuk harganya ditingkatkan lagi.',
        '2023-06-15', 'positive', '202405D2901241198', 'marsiti'],
       ['Kopi Kenangan', '09', '3',
        'Saya mengalami pengalaman sangat buruk secara keseluruhan.',
        '2023-01-04', 'negative', '202202D1701182164',
        'dias marzal fatama'],
       ['Si Bersih', '11', '2', ' suasana sangat buruk.', '2023-03-03',
        'negative', '202405D401187664', 'nur sodik'],
       ['Nice So', '13', '5',
        'Saya mengalami pengalaman sangat baik secara keseluruhan.',
        '2023-02-07', 'positive', '2024000000274900', 'suparmi']],
      dtype='<U91')

In [197]:
df_merchant_review = pd.DataFrame(merchant_review_, columns=['name_merchant','merchant_id','rating','review','date','sentiment', 'contrib_id', 'name'])
df_merchant_review = df_merchant_review[['contrib_id', 'name', 'name_merchant', 'merchant_id', 'review','date','rating', 'sentiment']]
df_merchant_review

,contrib_id,name,name_merchant,merchant_id,review,date,rating,sentiment
0,2024000000158999,umi maslikhah,Superindo,03,suasana sangat baik.,2023-07-12,4,positive
1,2024000000958691,fahri al farisi,Superindo,03,penyajian sangat baik.,2023-06-06,4,positive
2,2024000000306418,sunarti,Nice So,13,"pelayanannya sangat buruk, dimohon untuk pelay...",2023-10-24,1,negative
3,2024000000440214,singgih adi putra,Miniso,12,harga sangat baik.,2023-04-19,5,positive
4,202405F602312162,vika kumala putri,Intermedia,14,pelayanan sangat buruk.,2023-07-18,1,negative
...,...,...,...,...,...,...,...,...
81,2024000000143278,paryono,Mixue,04,harga baik.,2023-09-10,5,positive
82,202405D2901241198,marsiti,Fore Coffee,08,"harganya sangat baik, dimohon untuk harganya d...",2023-06-15,4,positive
83,202202D1701182164,dias marzal fatama,Kopi Kenangan,09,Saya mengalami pengalaman sangat buruk secara ...,2023-01-04,3,negative
84,202405D401187664,nur sodik,Si Bersih,11,suasana sangat buruk.,2023-03-03,2,negative
85,2024000000274900,suparmi,Nice So,13,Saya mengalami pengalaman sangat baik secara k...,2023-02-07,5,positive

In [206]:
rating_int = df_merchant_review['rating'].apply(int)

In [207]:
rating_int

0     4
1     4
2     1
3     5
4     1
     ..
81    5
82    4
83    3
84    2
85    5
Name: rating, Length: 86, dtype: int64

In [208]:
df_merchant_review['rating'] = rating_int

In [209]:
df_merchant_review.to_csv('df_merchant_review.csv', index=False)

In [210]:
count_merchant = df_merchant_review['name_merchant'].value_counts().reset_index()
count_merchant

    name_merchant  count
0       Superindo     14
1   Kopi Kenangan     11
2     Fore Coffee      9
3      Mie Gacoan      7
4      Intermedia      6
5           Ceria      6
6          Miniso      5
7        Alfamart      5
8        Idolmart      5
9         Nice So      4
10           Haus      4
11      Si Bersih      4
12          Mixue      3
13      Sederhana      2
14      Indomaret      1

In [211]:
df_merchant_review[['name_merchant','rating']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name_merchant  86 non-null     object
 1   rating         86 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [220]:
mean_merchant = df_merchant_review[['name_merchant','rating']].groupby(['name_merchant']).mean().reset_index()
mean_merchant

    name_merchant    rating
0        Alfamart  1.800000
1           Ceria  3.666667
2     Fore Coffee  4.333333
3            Haus  2.250000
4        Idolmart  3.400000
5       Indomaret  3.000000
6      Intermedia  3.000000
7   Kopi Kenangan  3.636364
8      Mie Gacoan  3.000000
9          Miniso  3.000000
10          Mixue  3.000000
11        Nice So  2.500000
12      Sederhana  2.500000
13      Si Bersih  2.000000
14      Superindo  3.500000

In [226]:
df_merchant

,name_merchant,merchant_id,merchant_group,rating,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,reviews,review
0,Indomaret,0,grocery,4.3,1.3,0.8,1.2,0.8,1.8,0.3,18,4
1,Alfamart,1,grocery,4.8,1.3,1.0,1.5,0.6,1.3,0.8,16,3
2,Idolmart,2,grocery,4.4,1.2,1.5,1.4,0.3,1.4,0.2,11,5
3,Superindo,3,grocery,4.2,1.4,0.9,1.2,0.8,1.2,0.4,12,5
4,Mixue,4,fnb,4.4,0.9,0.5,1.2,0.4,1.1,0.6,17,10
5,Haus,5,fnb,4.5,0.6,0.7,1.8,0.8,1.9,0.9,10,3
6,Mie Gacoan,6,fnb,4.5,1.2,1.6,0.7,0.3,0.8,0.6,15,6
7,Sederhana,7,fnb,4.8,0.3,1.6,1.8,0.9,1.1,0.2,19,9
8,Fore Coffee,8,fnb,4.9,0.5,1.1,1.3,0.6,1.3,0.4,18,8
9,Kopi Kenangan,9,fnb,4.7,1.1,0.8,1.6,0.6,1.2,0.5,15,2
10,Ceria,10,laundry,4.2,0.5,1.1,1.4,0.9,0.9,1.1,12,3
11,Si Bersih,11,laundry,4.4,1.0,0.9,0.8,0.5,1.9,0.2,12,3
12,Miniso,12,retail,4.6,0.8,1.5,1.7,0.6,1.7,0.9,11,10
13,Nice So,13,retail,4.3,1.3,1.2,1.3,0.7,1.8,0.9,11,9
14,Intermedia,14,retail,4.8,0.6,1.1,0.8,0.6,1.8,1.1,14,6

In [227]:
df_merchant_new = df_merchant.drop(columns=['rating','reviews','review'])
df_merchant_new

,name_merchant,merchant_id,merchant_group,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin
0,Indomaret,0,grocery,1.3,0.8,1.2,0.8,1.8,0.3
1,Alfamart,1,grocery,1.3,1.0,1.5,0.6,1.3,0.8
2,Idolmart,2,grocery,1.2,1.5,1.4,0.3,1.4,0.2
3,Superindo,3,grocery,1.4,0.9,1.2,0.8,1.2,0.4
4,Mixue,4,fnb,0.9,0.5,1.2,0.4,1.1,0.6
5,Haus,5,fnb,0.6,0.7,1.8,0.8,1.9,0.9
6,Mie Gacoan,6,fnb,1.2,1.6,0.7,0.3,0.8,0.6
7,Sederhana,7,fnb,0.3,1.6,1.8,0.9,1.1,0.2
8,Fore Coffee,8,fnb,0.5,1.1,1.3,0.6,1.3,0.4
9,Kopi Kenangan,9,fnb,1.1,0.8,1.6,0.6,1.2,0.5
10,Ceria,10,laundry,0.5,1.1,1.4,0.9,0.9,1.1
11,Si Bersih,11,laundry,1.0,0.9,0.8,0.5,1.9,0.2
12,Miniso,12,retail,0.8,1.5,1.7,0.6,1.7,0.9
13,Nice So,13,retail,1.3,1.2,1.3,0.7,1.8,0.9
14,Intermedia,14,retail,0.6,1.1,0.8,0.6,1.8,1.1

In [228]:
df_merchant_new = df_merchant_new.merge(count_merchant,on='name_merchant')
df_merchant_new

,name_merchant,merchant_id,merchant_group,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,count
0,Indomaret,0,grocery,1.3,0.8,1.2,0.8,1.8,0.3,1
1,Alfamart,1,grocery,1.3,1.0,1.5,0.6,1.3,0.8,5
2,Idolmart,2,grocery,1.2,1.5,1.4,0.3,1.4,0.2,5
3,Superindo,3,grocery,1.4,0.9,1.2,0.8,1.2,0.4,14
4,Mixue,4,fnb,0.9,0.5,1.2,0.4,1.1,0.6,3
5,Haus,5,fnb,0.6,0.7,1.8,0.8,1.9,0.9,4
6,Mie Gacoan,6,fnb,1.2,1.6,0.7,0.3,0.8,0.6,7
7,Sederhana,7,fnb,0.3,1.6,1.8,0.9,1.1,0.2,2
8,Fore Coffee,8,fnb,0.5,1.1,1.3,0.6,1.3,0.4,9
9,Kopi Kenangan,9,fnb,1.1,0.8,1.6,0.6,1.2,0.5,11
10,Ceria,10,laundry,0.5,1.1,1.4,0.9,0.9,1.1,6
11,Si Bersih,11,laundry,1.0,0.9,0.8,0.5,1.9,0.2,4
12,Miniso,12,retail,0.8,1.5,1.7,0.6,1.7,0.9,5
13,Nice So,13,retail,1.3,1.2,1.3,0.7,1.8,0.9,4
14,Intermedia,14,retail,0.6,1.1,0.8,0.6,1.8,1.1,6

In [229]:
df_merchant_new = df_merchant_new.merge(mean_merchant,on='name_merchant')
df_merchant_new

,name_merchant,merchant_id,merchant_group,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,count,rating
0,Indomaret,0,grocery,1.3,0.8,1.2,0.8,1.8,0.3,1,3.000000
1,Alfamart,1,grocery,1.3,1.0,1.5,0.6,1.3,0.8,5,1.800000
2,Idolmart,2,grocery,1.2,1.5,1.4,0.3,1.4,0.2,5,3.400000
3,Superindo,3,grocery,1.4,0.9,1.2,0.8,1.2,0.4,14,3.500000
4,Mixue,4,fnb,0.9,0.5,1.2,0.4,1.1,0.6,3,3.000000
5,Haus,5,fnb,0.6,0.7,1.8,0.8,1.9,0.9,4,2.250000
6,Mie Gacoan,6,fnb,1.2,1.6,0.7,0.3,0.8,0.6,7,3.000000
7,Sederhana,7,fnb,0.3,1.6,1.8,0.9,1.1,0.2,2,2.500000
8,Fore Coffee,8,fnb,0.5,1.1,1.3,0.6,1.3,0.4,9,4.333333
9,Kopi Kenangan,9,fnb,1.1,0.8,1.6,0.6,1.2,0.5,11,3.636364
10,Ceria,10,laundry,0.5,1.1,1.4,0.9,0.9,1.1,6,3.666667
11,Si Bersih,11,laundry,1.0,0.9,0.8,0.5,1.9,0.2,4,2.000000
12,Miniso,12,retail,0.8,1.5,1.7,0.6,1.7,0.9,5,3.000000
13,Nice So,13,retail,1.3,1.2,1.3,0.7,1.8,0.9,4,2.500000
14,Intermedia,14,retail,0.6,1.1,0.8,0.6,1.8,1.1,6,3.000000

In [232]:
df_merchant_new['merchant_id'] = ["{:02d}".format(i) for i in range(len(df_merchant['name_merchant'].values.tolist()))]

In [233]:
df_merchant_new

,name_merchant,merchant_id,merchant_group,dist_ancol,dist_kemayoran,dist_darmawangsa,dist_menteng,dist_senayan,dist_thamrin,count,rating
0,Indomaret,00,grocery,1.3,0.8,1.2,0.8,1.8,0.3,1,3.000000
1,Alfamart,01,grocery,1.3,1.0,1.5,0.6,1.3,0.8,5,1.800000
2,Idolmart,02,grocery,1.2,1.5,1.4,0.3,1.4,0.2,5,3.400000
3,Superindo,03,grocery,1.4,0.9,1.2,0.8,1.2,0.4,14,3.500000
4,Mixue,04,fnb,0.9,0.5,1.2,0.4,1.1,0.6,3,3.000000
5,Haus,05,fnb,0.6,0.7,1.8,0.8,1.9,0.9,4,2.250000
6,Mie Gacoan,06,fnb,1.2,1.6,0.7,0.3,0.8,0.6,7,3.000000
7,Sederhana,07,fnb,0.3,1.6,1.8,0.9,1.1,0.2,2,2.500000
8,Fore Coffee,08,fnb,0.5,1.1,1.3,0.6,1.3,0.4,9,4.333333
9,Kopi Kenangan,09,fnb,1.1,0.8,1.6,0.6,1.2,0.5,11,3.636364
10,Ceria,10,laundry,0.5,1.1,1.4,0.9,0.9,1.1,6,3.666667
11,Si Bersih,11,laundry,1.0,0.9,0.8,0.5,1.9,0.2,4,2.000000
12,Miniso,12,retail,0.8,1.5,1.7,0.6,1.7,0.9,5,3.000000
13,Nice So,13,retail,1.3,1.2,1.3,0.7,1.8,0.9,4,2.500000
14,Intermedia,14,retail,0.6,1.1,0.8,0.6,1.8,1.1,6,3.000000

In [235]:
df_merchant_new.to_csv('df_merchant.csv', index=False)